import analytics from "@react-native-firebase/analytics";

export const events = {
  START_SOLO_GAME_CLICK: "START_SOLO_GAME_CLICK",
  START_FRIENDLY_GAME_CLICK: "START_FRIENDLY_GAME_CLICK",
  START_RANKED_GAME_CLICK: "START_RANKED_GAME_CLICK",
  SHARE_CROSSED_CLICK: "SHARE_CROSSED_CLICK",
  FEEDBACK_CLICK: "FEEDBACK_CLICK",
  REMOVE_ADS_CLICK: "REMOVE_ADS_CLICK",
  MY_ACCOUNT_UPGRADE_TO_PRO_CLICK: "MY_ACCOUNT_UPGRADE_TO_PRO_CLICK",
  SUBMIT_SOLO_MATCH_CLICK: "SUBMIT_SOLO_MATCH_CLICK",
  FORFEIT_MATCH_CLICK: "FORFEIT_MATCH_CLICK",
  LEAVE_LOBBY_CLICK: "LEAVE_LOBBY_CLICK",
  RANKED_MATCH_OPPONENT_FOUND: "RANKED_MATCH_OPPONENT_FOUND",
  UPGRADE_CLICK: "UPGRADE_CLICK",
  RESTORE_PURCHASES_CLICK: "RESTORE_PURCHASES_CLICK",
};

export const trackEvent = async (eventName: string) => {
  await analytics().logEvent(eventName);
};
