const { withDangerousMod } = require("@expo/config-plugins");
const path = require("path");
const fs = require("fs");

/**
 * Fixes the EAS build failure:
 *   "include of non-modular header inside framework module 'RNFBApp...'
 *    React/RCTConvert.h [-Werror,-Wnon-modular-include-in-framework-module]"
 *
 * React Native Firebase requires `use_frameworks! :linkage => :static`
 * (we set useFrameworks: "static" in expo-build-properties). Under static
 * frameworks, RNFirebase's Objective-C headers include React-Core headers
 * that aren't modular, and clang promotes that warning to an error.
 *
 * The Podfile is regenerated by `expo prebuild`, so we inject a build-setting
 * override into the existing CocoaPods post_install hook to turn that one
 * warning off for every Pod target.
 */
const SNIPPET = `
    # withModularHeadersFix: allow RN Firebase non-modular header includes
    installer.pods_project.targets.each do |modular_fix_target|
      modular_fix_target.build_configurations.each do |modular_fix_config|
        modular_fix_config.build_settings['CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'] = 'NO'
      end
    end
`;

const withModularHeadersFix = (config) => {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfile = path.join(config.modRequest.platformProjectRoot, "Podfile");
      if (!fs.existsSync(podfile)) {
        console.warn("[withModularHeadersFix] Podfile not found at", podfile);
        return config;
      }
      let contents = fs.readFileSync(podfile, "utf8");
      if (contents.includes("CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE")) {
        return config; // already patched
      }
      const marker = /post_install do \|installer\|\n/;
      if (marker.test(contents)) {
        contents = contents.replace(marker, (m) => m + SNIPPET);
      } else {
        console.warn("[withModularHeadersFix] post_install hook not found; skipping");
        return config;
      }
      fs.writeFileSync(podfile, contents);
      return config;
    },
  ]);
};

module.exports = withModularHeadersFix;
