// Hand-authored word + clue bank (original clues, NYT-mini style: fair, mostly
// definitional with a little wit, doable but not trivial). The generator builds
// fully-interlocked grids using ONLY these words/clues, so every puzzle is made
// of vetted entries. Grouped by length. Keep clues free of the answer word.

export default {
  3: {
    ACE: ["Tennis serve winner", "Top pilot", "Expert"],
    ACT: ["Part of a play", "Do some theater", "Bit of behavior"],
    ADD: ["Find the sum", "Tack on", "Use a plus sign"],
    AGE: ["Years lived", "Grow older", "Era"],
    AID: ["Help out", "Assistance", "First-___ kit"],
    AIM: ["Point a bow", "Goal", "Take careful ___"],
    AIR: ["What we breathe", "Broadcast", "Tire filler"],
    ANT: ["Picnic pest", "Colony insect", "Aardvark's snack"],
    APE: ["Gorilla or chimp", "Mimic", "King Kong, e.g."],
    ARC: ["Curved path", "Rainbow's shape", "Part of a circle"],
    ARM: ["Shoulder-to-hand limb", "Sofa's side", "Supply with weapons"],
    ART: ["Museum display", "Painting and such", "Liberal ___"],
    ASH: ["Fireplace residue", "Cigarette remains", "Volcano output"],
    BAD: ["Not good", "Naughty", "Spoiled, as milk"],
    BAG: ["Grocery carrier", "Sack", "Catch, as game"],
    BAR: ["Pub counter", "Block the way", "Long metal rod"],
    BAT: ["Cave flier", "Slugger's stick", "Nocturnal flier"],
    BAY: ["Coastal inlet", "Hound's cry", "Loading ___"],
    BED: ["Place to sleep", "Garden plot", "Make the ___"],
    BEE: ["Honey maker", "Spelling contest", "Quilting gathering"],
    BIG: "Large",
    BIT: "Small amount",
    BOX: "Cardboard container",
    BOY: "Young lad",
    BUD: "Flower-to-be",
    BUG: "Crawling critter",
    BUS: "City transit ride",
    BUY: "Purchase",
    CAB: "Yellow city ride",
    CAP: "Bottle topper",
    CAR: "Vehicle in a garage",
    CAT: "Purring pet",
    COW: "Milk giver",
    CRY: "Shed tears",
    CUP: "Coffee holder",
    CUT: "Use scissors",
    DAY: "24 hours",
    DEN: "Cozy home room",
    DIG: "Use a shovel",
    DOG: "Loyal pet",
    DOT: "Tiny round mark",
    DRY: "Not wet",
    EAR: "Hearing organ",
    EAT: "Have a meal",
    EGG: "Breakfast staple",
    END: "Finish",
    FAN: "Sports supporter",
    FAR: "A long way off",
    FEW: "Not many",
    FIG: "Newton's fruit",
    FIN: "Shark's feature",
    FIT: "In good shape",
    FIX: "Repair",
    FLY: "Travel by plane",
    FOG: "Thick mist",
    FOX: "Sly woodland animal",
    FUN: "A good time",
    GAP: "Empty space",
    GAS: "Pump fill-up",
    GEM: "Precious stone",
    GUM: "Chewy treat",
    GUN: "Firearm",
    GUY: "Fellow",
    HAM: "Deli meat",
    HAT: "Head cover",
    HEN: "Egg layer",
    HIP: "Trendy",
    HIT: "Smash success",
    HOT: "Like a stove",
    HUG: "Warm embrace",
    ICE: ["Frozen water", "Give the cold shoulder to"],
    ILL: "Under the weather",
    INK: "Pen fluid",
    JAM: ["Toast spread", "Bumper-to-bumper mess"],
    JAR: "Pickle holder",
    JET: "Fast plane",
    JOB: "Daily work",
    JOY: "Great delight",
    KEY: "Lock opener",
    KID: "Young one",
    LAP: "Track circuit",
    LAW: "Rule of the land",
    LEG: "Body's limb for walking",
    LID: "Pot cover",
    LIP: "Mouth's edge",
    LOG: "Firewood piece",
    LOT: "A great deal",
    LOW: "Not high",
    MAD: "Very angry",
    MAN: "Adult male",
    MAP: "Travel guide",
    MAT: "Doormat",
    MIX: "Stir together",
    MOM: "Family parent",
    MUD: "Wet dirt",
    MUG: "Coffee cup",
    NAP: ["Short sleep", "Recharge, eyes closed"],
    NET: "Tennis divider",
    NEW: "Just made",
    NOD: "Yes gesture",
    NUT: "Squirrel's snack",
    OAK: "Sturdy tree",
    OAR: "Rowboat tool",
    ODD: "Strange",
    OIL: "Salad dressing base",
    OLD: "Aged",
    OWL: "Nighttime hooter",
    PAN: "Frying vessel",
    PAW: "Animal's foot",
    PEA: "Pod veggie",
    PEN: "Writing tool",
    PET: "Household animal",
    PIE: "Dessert slice source",
    PIG: "Farm oinker",
    PIN: "Sewing point",
    PIT: "Cherry's center",
    POT: "Cooking vessel",
    PUP: "Baby dog",
    RAG: "Cleaning cloth",
    RAT: "City rodent",
    RAW: "Uncooked",
    RED: "Stop-light color",
    RIB: "Chest bone",
    RIM: "Edge of a cup",
    ROW: "Theater line of seats",
    RUG: "Floor covering",
    RUN: "Jog fast",
    SAD: "Feeling blue",
    SEA: "Vast water body",
    SET: "Tennis match part",
    SIP: "Drink slowly",
    SIT: "Take a seat",
    SKY: "Where clouds float",
    SLY: "Cunning",
    SON: "Male child",
    SPA: "Relaxation retreat",
    SUN: "Daytime star",
    TAG: "Game of chase",
    TAN: "Beach color",
    TAP: "Faucet",
    TAR: "Road sealant",
    TEA: "Brewed drink",
    TEN: "A perfect score",
    TIE: "Necktie",
    TIP: "Waiter's reward",
    TOE: "Foot digit",
    TOP: "Spinning toy",
    TOY: "Child's plaything",
    TUB: "Bathing basin",
    TWO: "A pair",
    USE: "Put to work",
    VAN: "Cargo vehicle",
    VET: "Animal doctor",
    WAR: "Armed conflict",
    WAX: "Candle material",
    WEB: "Spider's trap",
    WET: "Soaked",
    WIN: "Take first place",
    WOW: "Amaze",
    YES: "Affirmative",
    ZIP: "Jacket fastener",
    ZOO: "Animal park",
  },
  4: {
    ABLE: "Capable",
    ACID: "Sour chemical",
    ACRE: "Land measure",
    AREA: "Region",
    ARMY: "Land military force",
    AUNT: "Mom's sister",
    AUTO: "Car, informally",
    BABY: "Newborn",
    BAKE: "Make in the oven",
    BALL: "Round toy",
    BAND: "Musical group",
    BANK: "Money holder",
    BARN: "Farm building",
    BASE: "Foundation",
    BATH: "Soak in the tub",
    BEAD: "Necklace piece",
    BEAM: "Ray of light",
    BEAN: "Coffee unit",
    BEAR: "Forest mammal",
    BEAT: "Drum rhythm",
    BELL: "Ringing instrument",
    BELT: "Waist strap",
    BEST: "Top-ranked",
    BIKE: "Two-wheeler",
    BIRD: "Feathered flier",
    BITE: "Take a chomp",
    BLUE: "Sky color",
    BOAT: "Water vessel",
    BODY: "Physical form",
    BOLD: "Daring",
    BONE: "Skeleton part",
    BOOK: "Reading material",
    BOOT: "Sturdy footwear",
    BORN: "Brought into the world",
    BOSS: "The one in charge",
    BOWL: "Cereal dish",
    CAGE: "Bird's home",
    CAKE: "Birthday treat",
    CALM: "Peaceful",
    CAMP: "Tent getaway",
    CARD: "Deck member",
    CARE: "Look after",
    CART: "Shopping pusher",
    CASH: "Paper money",
    CAVE: ["Underground hollow", "Give in"],
    CHEF: "Kitchen pro",
    CHIN: "Below the mouth",
    CITY: "Urban center",
    CLAP: "Applaud",
    CLAW: "Cat's nail",
    CLAY: "Pottery material",
    COAT: "Winter wear",
    COIN: "Pocket change",
    COLD: "Chilly",
    COOK: "Prepare a meal",
    COOL: "Slightly cold",
    CORN: "Cob crop",
    COZY: "Snug and warm",
    CREW: "Ship's team",
    CROP: "Farmer's yield",
    CUBE: "Six-sided shape",
    CURL: "Hair twist",
    DARK: "Without light",
    DEAL: "Bargain",
    DEEP: "Far down",
    DESK: "Office furniture",
    DIAL: "Phone's old input",
    DICE: "Board-game cubes",
    DISH: "Plate or bowl",
    DOOR: "Room entrance",
    DOVE: "Peace bird",
    DRAW: "Sketch",
    DROP: "Let fall",
    DRUM: "Beat instrument",
    DUCK: "Quacking bird",
    DUST: "Shelf film",
    EACH: "Every one",
    EARN: "Work for pay",
    EAST: "Sunrise direction",
    EASY: "Not hard",
    EDGE: "Border",
    FACE: "Front of the head",
    FACT: "True statement",
    FAIR: "Just",
    FALL: "Autumn",
    FARM: "Crop land",
    FAST: "Speedy",
    FEAR: "Be afraid of",
    FERN: "Leafy plant",
    FILM: "Movie",
    FIRE: "Campsite blaze",
    FISH: "Aquarium swimmer",
    FIST: "Clenched hand",
    FLAG: "Country symbol",
    FLAT: "Level",
    FLEA: "Tiny biting pest",
    FLEW: "Took to the air",
    FOAM: "Bubbly froth",
    FOLD: "Crease",
    FOND: "Affectionate",
    FOOD: "What we eat",
    FOOT: "Twelve inches",
    FORK: "Dinner utensil",
    FORM: "Shape",
    FREE: "At no cost",
    FROG: "Lily-pad hopper",
    FUEL: "Engine's energy",
    FULL: "Filled up",
    GAME: "Match to win",
    GATE: "Fence opening",
    GIFT: "Present",
    GIRL: "Young lass",
    GLAD: "Happy",
    GLOW: "Soft light",
    GOAL: "Aim",
    GOAT: "Mountain climber",
    GOLD: "Olympic medal metal",
    GOOD: "Not bad",
    GRAB: "Snatch",
    GRAY: "Cloudy-sky shade",
    GROW: "Get bigger",
    HALF: "Fifty percent",
    HALL: "Corridor",
    HAND: "End of the arm",
    HARD: "Difficult",
    HEAD: "Top of the body",
    HEAT: "Warmth",
    HERD: "Cattle group",
    HERO: "Brave saver",
    HIDE: "Conceal",
    HIGH: "Up above",
    HILL: "Small mound",
    HINT: "Little clue",
    HIVE: "Bee colony",
    HOLD: "Grasp",
    HOLE: "Gap in the ground",
    HOME: "Where you live",
    HOPE: "Wish for",
    HORN: "Car honker",
    HOUR: "Sixty minutes",
    ICON: "Phone screen symbol",
    IDEA: "Bright thought",
    IRON: "Wrinkle remover",
    ITEM: "List entry",
    JOKE: "Punch-line bit",
    JUMP: "Leap up",
    KICK: "Soccer move",
    KIND: "Caring",
    KING: "Castle ruler",
    KISS: "Smooch",
    KNEE: "Leg joint",
    KNOW: "Be aware of",
    LACE: "Shoe string",
    LAKE: "Inland water",
    LAMP: "Desk light",
    LAND: "Touch down",
    LATE: "Not on time",
    LAWN: "Front-yard grass",
    LEAF: "Tree's green flap",
    LEAP: "Big jump",
    LEFT: ["Not right", "Headed out"],
    LEND: "Loan out",
    LIFE: "Existence",
    LIFT: "Raise up",
    LIME: "Green citrus",
    LINE: "Queue",
    LION: "Jungle king",
    LIST: "To-do items",
    LOAF: "Bread unit",
    LOCK: "Key's partner",
    LONG: "Not short",
    LOOK: "Take a peek",
    LOUD: "Noisy",
    LOVE: "Adore",
    LUCK: "Good fortune",
    MAIL: "Postal delivery",
    MANY: "A lot",
    MASK: "Face cover",
    MAZE: "Puzzle of paths",
    MEAL: "Lunch, e.g.",
    MEAT: "Butcher's offering",
    MELT: "Turn to liquid",
    MENU: "List of dishes",
    MILD: "Gentle",
    MILK: "Dairy drink",
    MIND: "The brain's work",
    MINT: "Fresh herb",
    MOON: "Night sky orb",
    MOST: "The greatest amount",
    MOTH: "Lamp-drawn insect",
    NAME: "What you're called",
    NEAR: "Close by",
    NEAT: "Tidy",
    NEST: "Bird's home",
    NICE: "Pleasant",
    NOON: "Midday",
    NOSE: "Smelling organ",
    NOTE: "Quick message",
    OPEN: "Not shut",
    OVEN: "Baking box",
    PACK: "Fill a suitcase",
    PAGE: "Book leaf",
    PAIL: "Sandcastle bucket",
    PAIN: "Ache",
    PAIR: "A couple",
    PALM: "Beach tree",
    PARK: "Green public space",
    PART: "Piece",
    PATH: "Walking trail",
    PEAK: "Mountain top",
    PEAR: "Bell-shaped fruit",
    PILE: "Heap",
    PINE: "Evergreen tree",
    PINK: "Light red",
    PLAN: "Strategy",
    PLAY: "Have fun",
    PLUM: "Purple fruit",
    PLUS: "Addition sign",
    POEM: "Verse work",
    POND: "Small lake",
    POOL: "Swimming spot",
    POUR: "Tip out liquid",
    PROP: "Stage object",
    PULL: "Tug toward you",
    PUSH: "Press forward",
    QUIZ: "Short test",
    RACE: "Speed contest",
    RAFT: "Floating platform",
    RAIN: "Wet weather",
    RARE: "Uncommon",
    READ: "Look at a book",
    REST: "Take a break",
    RICE: "Sushi grain",
    RICH: "Wealthy",
    RIDE: "Hop in the car",
    RING: ["Finger band", "Boxer's battleground"],
    RIPE: "Ready to eat",
    RISE: "Go up",
    ROAD: "Paved route",
    ROCK: "Stone",
    ROLE: "Actor's part",
    ROOF: "House topper",
    ROOM: "House space",
    ROOT: "Plant's underground part",
    ROPE: "Thick cord",
    ROSE: "Thorny flower",
    RUDE: "Impolite",
    RUSH: "Hurry",
    SAFE: "Out of danger",
    SAIL: "Boat's cloth",
    SALT: "Pepper's partner",
    SAND: "Beach grains",
    SEAT: "Place to sit",
    SEED: "Plant starter",
    SEEK: "Search for",
    SELL: "Offer for money",
    SHIP: "Ocean vessel",
    SHOE: "Foot wear",
    SHOP: "Store",
    SHOW: "Display",
    SHUT: "Close",
    SICK: "Ill",
    SIDE: "Edge or flank",
    SILK: "Smooth fabric",
    SING: "Carry a tune",
    SINK: "Kitchen basin",
    SITE: "Location",
    SIZE: "How big",
    SKIN: "Body covering",
    SLED: "Snow rider",
    SLOW: "Not fast",
    SNOW: "Winter flakes",
    SOAP: "Bath bar",
    SOCK: "Foot warmer",
    SOFT: "Not hard",
    SOIL: "Garden dirt",
    SONG: "Tune with lyrics",
    SOUP: "Bowl of broth",
    SOUR: "Lemon's taste",
    STAR: ["Night sky twinkler", "The headliner"],
    STAY: "Remain",
    STEM: "Flower's stalk",
    STEP: "Stair unit",
    STOP: "Halt",
    SWIM: "Move through water",
    TAIL: "Dog's wagger",
    TALL: "High up",
    TAME: "Not wild",
    TANK: "Fish's home",
    TAPE: "Sticky roll",
    TASK: "Job to do",
    TEAM: "Group of players",
    TEAR: "Eye drop",
    TELL: "Inform",
    TENT: "Camper's shelter",
    TEST: "Exam",
    TIDE: ["Ocean's rise and fall", "It always turns"],
    TIDY: "Neat",
    TIME: "Clock's measure",
    TINY: "Very small",
    TIRE: "Wheel's rubber",
    TONE: "Voice quality",
    TOOL: "Hammer or wrench",
    TORN: "Ripped",
    TOWN: "Small city",
    TREE: "Leafy plant",
    TRIP: "Vacation",
    TRUE: "Not false",
    TUNE: "Melody",
    TURN: "Your go",
    TWIN: "Identical sibling",
    VASE: "Flower holder",
    VAST: "Huge",
    VOTE: "Cast a ballot",
    WAIT: "Be patient",
    WAKE: "Stop sleeping",
    WALK: "Stroll",
    WALL: "Room divider",
    WARM: "Cozy temperature",
    WASH: "Clean with water",
    WAVE: ["Ocean swell", "Stadium ripple"],
    WEAK: "Not strong",
    WEAR: "Put on clothes",
    WEEK: "Seven days",
    WEST: "Sunset direction",
    WIDE: "Broad",
    WILD: "Untamed",
    WIND: "Breeze",
    WING: "Bird's flier",
    WISE: "Smart",
    WISH: "Hope for",
    WOLF: "Howling canine",
    WOOD: "Lumber",
    WORD: "Crossword fill",
    WORK: "Do a job",
    WORM: "Garden wriggler",
    YARD: "Backyard space",
    YEAR: "365 days",
    ZERO: "Nothing",
    ZONE: "Area",
  },
  5: {
    ABOVE: "Higher than",
    ACTOR: "Movie star",
    ADULT: "Grown-up",
    AGREE: "Say yes",
    ALARM: "Morning ringer",
    ALERT: "On guard",
    ALIVE: "Living",
    ALONE: "By oneself",
    ANGEL: "Winged helper",
    ANGER: "Strong rage",
    ANGLE: "Corner's measure",
    APPLE: "Orchard fruit",
    APRON: "Cook's cover",
    ARENA: "Sports venue",
    ARROW: "Bow's projectile",
    AWARD: "Trophy or prize",
    AWARE: "In the know",
    BACON: "Breakfast strips",
    BADGE: "Officer's pin",
    BAKER: "Bread maker",
    BASIC: "Simple",
    BEACH: "Sandy shore",
    BEARD: "Chin hair",
    BEGIN: "Start",
    BENCH: "Park seat",
    BERRY: "Small fruit",
    BIRTH: "Day you're born",
    BLACK: "Night's color",
    BLADE: "Knife's edge",
    BLAME: "Point the finger at",
    BLANK: "Empty space",
    BLAST: "Big explosion",
    BLEND: "Mix together",
    BLINK: "Quick eye shut",
    BLOOM: "Flower's opening",
    BOARD: "Plank of wood",
    BOAST: "Brag",
    BONUS: "Extra reward",
    BOOST: "Lift up",
    BRAIN: "Thinking organ",
    BRAND: "Product label",
    BRAVE: "Courageous",
    BREAD: "Sandwich base",
    BREAK: "Take a rest",
    BRICK: "Wall block",
    BRIEF: "Short",
    BRING: "Carry along",
    BROAD: "Wide",
    BROOM: "Sweeping tool",
    BROWN: "Chocolate shade",
    BRUSH: "Painter's tool",
    BUILD: "Construct",
    BUNCH: "A whole lot",
    CABIN: "Woodsy retreat",
    CANDY: "Sweet treat",
    CARGO: "Ship's load",
    CHAIN: "Linked metal",
    CHAIR: "Seat with a back",
    CHALK: "Blackboard stick",
    CHARM: "Bracelet trinket",
    CHART: "Data graph",
    CHASE: "Run after",
    CHEAP: "Low-priced",
    CHEER: "Root for",
    CHESS: "Board game of kings",
    CHEST: "Treasure box",
    CHILD: "Young kid",
    CHILL: "Relax",
    CIVIC: "Of the city",
    CLAIM: "Assert",
    CLASS: "School session",
    CLEAN: "Spotless",
    CLEAR: "Easy to see through",
    CLICK: "Mouse action",
    CLIFF: "Steep rock face",
    CLIMB: "Go up",
    CLOCK: "Time teller",
    CLOSE: "Shut",
    CLOTH: "Fabric piece",
    CLOUD: "Sky puff",
    CLOWN: "Circus jokester",
    COACH: "Team leader",
    COAST: "Shoreline",
    COLOR: "Red or blue",
    COUCH: "Living-room sofa",
    COUNT: "Tally up",
    COURT: "Tennis playing area",
    COVER: "Put a lid on",
    CRACK: "Thin split",
    CRAFT: "Handmade hobby",
    CRANE: "Tall lifting machine",
    CRASH: "Collide",
    CRAWL: "Move on all fours",
    CRAZY: "Wild and wacky",
    CREAM: "Coffee whitener",
    CRISP: "Crunchy",
    CROSS: "Go over",
    CROWD: "Big gathering",
    CROWN: "Royal headwear",
    CURVE: "Bend",
    DAISY: "White-petaled flower",
    DANCE: "Move to music",
    DEPTH: "How deep",
    DOZEN: "Twelve",
    DRAFT: "Rough version",
    DREAM: "Sleep vision",
    DRESS: "Gown",
    DRINK: "Beverage",
    DRIVE: "Operate a car",
    EAGER: "Keen",
    EAGLE: "Bald national bird",
    EARLY: "Ahead of time",
    EARTH: "Our planet",
    EMPTY: "Nothing inside",
    ENJOY: "Take pleasure in",
    ENTER: "Go in",
    EQUAL: "The same",
    ERROR: "Mistake",
    EVENT: "Happening",
    EVERY: "Each one",
    EXTRA: "Additional",
    FAITH: "Strong belief",
    FANCY: "Elaborate",
    FAULT: "Blame",
    FEAST: "Big meal",
    FENCE: "Yard border",
    FIELD: "Open grassland",
    FIGHT: "Brawl",
    FINAL: "Last",
    FIRST: "Number one",
    FLAME: "Candle's fire",
    FLASH: "Quick burst of light",
    FLOAT: "Stay on water",
    FLOOR: "Room's bottom",
    FLOUR: "Baking powder",
    FLOWER: "Garden bloom",
    FOCUS: "Concentrate",
    FORCE: "Power",
    FRESH: "Just-picked",
    FRONT: "Opposite of back",
    FROST: "Window-pane ice",
    FRUIT: "Apple or pear",
    FUNNY: "Hilarious",
    GHOST: "Spooky spirit",
    GIANT: "Huge being",
    GLASS: "Window pane",
    GLOBE: "Earth model",
    GLOVE: "Hand warmer",
    GRACE: "Elegance",
    GRADE: "Report-card mark",
    GRAIN: "Wheat unit",
    GRAND: "Magnificent",
    GRAPE: "Wine fruit",
    GRASS: "Lawn green",
    GREAT: "Excellent",
    GREEN: "Grass color",
    GRILL: "Backyard cooker",
    GROUP: "Cluster",
    GUARD: "Protector",
    GUESS: "Take a stab",
    GUEST: "Visitor",
    HAPPY: "Joyful",
    HEART: "Love symbol",
    HEAVY: "Weighty",
    HONEY: "Bee's sweet output",
    HORSE: "Stable animal",
    HOTEL: "Travel lodging",
    HOUSE: "Family dwelling",
    HUMAN: "Person",
    HUMOR: "Sense of fun",
    IDEAL: "Perfect",
    IMAGE: "Picture",
    JEWEL: "Precious gem",
    JOINT: "Body's bend",
    JUICE: "Orange drink",
    KNIFE: "Cutting tool",
    LABEL: "Product tag",
    LARGE: "Big",
    LASER: "Focused beam",
    LAUGH: "React to a joke",
    LAYER: "Cake tier",
    LEARN: "Pick up knowledge",
    LEMON: "Sour yellow fruit",
    LEVEL: "Flat and even",
    LIGHT: "Lamp's output",
    LIVER: "Body organ",
    LODGE: "Ski cabin",
    LUCKY: "Fortunate",
    LUNCH: "Midday meal",
    MAGIC: "Wizard's craft",
    MAYOR: "City leader",
    MEDAL: "Winner's award",
    MERCY: "Compassion",
    METAL: "Iron or steel",
    METER: "Distance unit",
    MIGHT: "Power",
    MONEY: "Cash",
    MONTH: "April or May",
    MOUNT: "Climb up",
    MOUSE: "Cheese nibbler",
    MOUTH: "Where you eat",
    MOVIE: "Film",
    MUSIC: "Song and sound",
    NIGHT: "After sunset",
    NOISE: "Loud sound",
    NORTH: "Compass top",
    NOVEL: "Long story",
    NURSE: "Hospital helper",
    OCEAN: "Vast sea",
    OFFER: "Propose",
    ONION: "Tear-causing veggie",
    ORDER: "Restaurant request",
    ORGAN: "Church instrument",
    OTTER: "Playful river mammal",
    OWNER: "One who has it",
    PAINT: "Wall coating",
    PANIC: "Sudden fear",
    PAPER: "Notebook sheet",
    PARTY: "Celebration",
    PASTE: "Glue-like stuff",
    PATCH: "Repair piece",
    PAUSE: "Brief stop",
    PEACE: "Calm and quiet",
    PEACH: "Fuzzy fruit",
    PEARL: "Oyster gem",
    PHONE: "Pocket caller",
    PIANO: "Keyboard instrument",
    PILOT: "Plane flier",
    PIZZA: "Cheesy pie",
    PLACE: "Spot",
    PLAIN: "Simple",
    PLANE: "Sky traveler",
    PLANT: "Garden grower",
    PLATE: "Dinner dish",
    POINT: "Pencil's tip",
    PORCH: "Front step area",
    POUND: "Sixteen ounces",
    POWER: "Strength",
    PRESS: "Push down",
    PRICE: "Cost",
    PRIDE: "Self-respect",
    PRINT: "Newspaper output",
    PRIZE: "Award",
    PROUD: "Pleased with oneself",
    PROVE: "Show to be true",
    PUNCH: "Boxer's blow",
    PUPIL: ["Student", "It widens in the dark"],
    QUEEN: "King's partner",
    QUICK: "Speedy",
    QUIET: "Hushed",
    QUILT: "Patchwork blanket",
    QUITE: "Rather",
    RADIO: "Music box on the dash",
    RANCH: "Cattle spread",
    RANGE: "Mountain chain",
    RAPID: "Very fast",
    REACH: "Stretch toward",
    RELAX: "Unwind",
    REPLY: "Answer back",
    RHYME: "Poem's match",
    RIDGE: "Hill's crest",
    RIVER: "Flowing water",
    ROAST: "Cook in the oven",
    ROBIN: "Red-breasted bird",
    ROBOT: "Mechanical helper",
    ROUND: "Circular",
    ROUTE: "Travel path",
    ROYAL: "Of the crown",
    SALAD: "Leafy dish",
    SAUCE: "Pasta topping",
    SCALE: "Weight checker",
    SCARF: "Neck warmer",
    SCENE: "Movie segment",
    SCORE: "Game tally",
    SCOUT: "Badge earner",
    SENSE: "Sight or smell",
    SHACK: "Small hut",
    SHADE: ["Spot out of the sun", "Subtle dig, in slang"],
    SHAPE: "Form",
    SHARE: "Divide up",
    SHARK: "Ocean predator",
    SHARP: "Knife-like",
    SHEEP: "Wool provider",
    SHEET: "Bed cover",
    SHELF: "Wall ledge",
    SHELL: "Beach find",
    SHINE: "Gleam",
    SHIRT: "Torso wear",
    SHORE: "Beach edge",
    SHORT: "Not tall",
    SHOUT: "Yell",
    SIGHT: "Vision",
    SKATE: "Ice glider",
    SLEEP: "Nighttime rest",
    SLICE: "Pizza piece",
    SLIDE: "Playground feature",
    SMALL: "Little",
    SMART: "Clever",
    SMELL: "Use the nose",
    SMILE: "Happy face",
    SMOKE: "Fire's plume",
    SNACK: "Light bite",
    SNAKE: "Slithering reptile",
    SOLAR: "Of the sun",
    SOLID: "Not liquid",
    SOUND: "What ears detect",
    SOUTH: "Compass bottom",
    SPACE: "Final frontier",
    SPARE: "Extra",
    SPARK: "Tiny flash of fire",
    SPEAK: "Talk",
    SPEED: "Fast pace",
    SPELL: "Order the letters",
    SPEND: "Pay out",
    SPICE: "Cinnamon, e.g.",
    SPILL: "Knock over a drink",
    SPINE: "Backbone",
    SPLIT: "Divide",
    SPOON: "Soup utensil",
    SPORT: "Athletic game",
    STAFF: "Workers",
    STAGE: "Theater platform",
    STAIR: "Step up",
    STAMP: "Letter sticker",
    STAND: "Get on your feet",
    STARE: "Look long and hard",
    START: "Begin",
    STATE: "Texas or Ohio",
    STEAM: "Kettle's vapor",
    STEEL: "Strong metal",
    STERN: "Strict",
    STICK: "Tree twig",
    STING: "Bee's jab",
    STOCK: "Store's supply",
    STONE: "Rock",
    STORE: "Shop",
    STORM: ["Bad weather", "Burst in angrily"],
    STORY: "Tale",
    STOVE: "Kitchen cooker",
    STUDY: "Hit the books",
    STYLE: "Fashion sense",
    SUGAR: "Sweetener",
    SUNNY: "Cloudless",
    SUPER: "Fantastic",
    SWEET: "Sugary",
    SWING: "Playground seat",
    TABLE: "Dining furniture",
    TASTE: "Tongue's sense",
    TEACH: "Give lessons",
    THANK: "Show gratitude",
    THICK: "Not thin",
    THINK: "Use your head",
    THREE: "A trio",
    THROW: "Toss",
    TIGER: "Striped big cat",
    TIGHT: "Snug",
    TITLE: "Book's name",
    TOAST: "Browned bread",
    TODAY: "This very day",
    TOOTH: "Smile feature",
    TORCH: "Handheld flame",
    TOUCH: "Feel with a finger",
    TOWEL: "Beach drier",
    TOWER: "Tall structure",
    TRACK: "Runner's loop",
    TRADE: "Swap",
    TRAIL: "Hiking path",
    TRAIN: "Railway ride",
    TREAT: "Special goody",
    TREND: "Latest fad",
    TRICK: "Sneaky move",
    TRUCK: "Big hauler",
    TRUST: "Have faith in",
    TRUTH: "Honest fact",
    UNCLE: "Aunt's spouse",
    UNDER: "Below",
    UNITE: "Join together",
    UPPER: "Higher one",
    VALUE: "Worth",
    VIDEO: "Recorded clip",
    VOICE: "Speaking sound",
    WAGON: "Pull-along cart",
    WATCH: "Wrist clock",
    WATER: "H2O",
    WHALE: "Ocean giant",
    WHEAT: "Bread grain",
    WHEEL: "Round roller",
    WHITE: "Snow's color",
    WHOLE: "Entire",
    WOMAN: "Adult female",
    WORLD: "The globe",
    WORTH: "Value",
    WOUND: "Injury",
    WRIST: "Hand joint",
    WRITE: "Put on paper",
    YOUNG: "Not old",
    YOUTH: "Young person",
    ZEBRA: "Striped grazer",
    ADOBE: "Sun-dried brick",
    AGENT: "Spy or rep",
    AISLE: "Store walkway",
    ALBUM: "Photo collection",
    ALLOW: "Permit",
    ALONG: "Beside",
    ALPHA: "First Greek letter",
    AMUSE: "Make laugh",
    ANKLE: "Foot joint",
    APART: "Separated",
    ARGUE: "Bicker",
    ARISE: "Get up",
    ASIDE: "Off to one side",
    ATTIC: "Top-floor storage",
    AUDIO: "Sound part",
    AVOID: "Steer clear of",
    AWAKE: "Not asleep",
    BARGE: "Flat cargo boat",
    BASIN: "Sink bowl",
    BATCH: "Group baked at once",
    BLOCK: "City square",
    BLUSH: "Cheek redness",
    BOOTH: "Diner seat",
    BOUND: "Tied up",
    BRACE: "Support beam",
    BRAKE: "Pedal to stop",
    BRASS: "Trumpet's metal",
    BREED: "Dog type",
    BROKE: "Out of cash",
    BUGLE: "Army horn",
    BUNNY: "Easter hopper",
    CABLE: "TV wire",
    CANAL: "Boat channel",
    CARVE: "Cut a turkey",
    CHIME: "Doorbell sound",
    CHOIR: "Singing group",
    CHORD: "Musical notes together",
    CHUNK: "Big piece",
    CIDER: "Apple drink",
    CLASP: "Necklace catch",
    CLOAK: "Hooded wrap",
    CLUMP: "Cluster",
    COMET: ["Tailed space rock", "Halley's, famously"],
    CORAL: "Reef builder",
    COUGH: "Cold symptom",
    CRANK: "Hand turner",
    CRATE: "Wooden box",
    CREEK: "Small stream",
    CREST: "Wave's top",
    CRUMB: "Cookie bit",
    CURRY: "Spiced dish",
    DAIRY: "Milk section",
    DECAY: "Rot",
    DELTA: "River mouth",
    DENIM: "Jeans fabric",
    DIGIT: "0 through 9",
    DITCH: "Roadside trench",
    DODGE: "Dart away from",
    DOUGH: "Bread base",
    DRAIN: "Sink hole",
    DRIFT: "Float aimlessly",
    DUSTY: "Needing a cleaning",
    DWELL: "Live somewhere",
    ELBOW: "Arm joint",
    ELDER: "Older one",
    ELECT: "Vote in",
    ELITE: "Top tier",
    EXILE: "Banish",
    FABLE: "Moral tale",
    FETCH: "Go get",
    FIBER: "Diet roughage",
    FINCH: "Small songbird",
    FLOCK: "Sheep group",
    FLUSH: "Toilet action",
    FORTY: "Four times ten",
    FROWN: "Unhappy face",
    GLOOM: "Darkness",
    GRIEF: "Deep sorrow",
    GRIND: "Crush to bits",
    GROAN: "Moan",
    HATCH: "Egg opening",
    HAVEN: "Safe place",
    HEDGE: "Bush row",
    HOVER: "Float in place",
    HUMID: "Muggy",
    IGLOO: "Ice dome",
    INDEX: "Book's word list",
    INLET: "Small bay",
    IVORY: "Elephant tusk",
    KOALA: "Eucalyptus muncher",
    LATCH: "Gate fastener",
    LEDGE: "Narrow shelf",
    LINEN: "Bed fabric",
    LLAMA: "Andes pack animal",
    LOYAL: "Faithful",
    MAPLE: "Syrup tree",
    MARSH: "Wetland",
    MEDIA: "Press and TV",
    MELON: "Cantaloupe, e.g.",
    MERIT: "Deserve",
    MOTEL: "Roadside inn",
    MOTOR: "Engine",
    MOUND: "Pile of dirt",
    MOURN: "Grieve",
    MOVER: "Furniture hauler",
    NIECE: "Brother's daughter",
    NOBLE: "Honorable",
    NUDGE: "Gentle push",
    OLIVE: "Martini garnish",
    PADDLE: "Canoe oar",
    PEDAL: "Bike pusher",
    PERCH: "Bird's roost",
    PETAL: "Flower leaf",
    PILOT: "Cockpit pro",
    PIVOT: "Turn on a point",
    PLUMP: "Chubby",
    POLAR: "Of the icy ends",
    PRINT: "Newspaper output",
    PRONG: "Fork tine",
    PROWL: "Sneak around",
    PULSE: "Heartbeat",
    PUREE: "Blended food",
    QUACK: "Duck's call",
    QUARK: "Tiny particle",
    RAVEN: "Black bird",
    REBEL: "One who revolts",
    REIGN: "Rule as king",
    RINSE: "Wash lightly",
    RIVAL: "Competitor",
    ROOST: "Hen's perch",
    ROUGH: "Not smooth",
    SCALP: "Top of the head",
    SCENT: "Aroma",
    SCOLD: "Tell off",
    SCOOP: "Ice cream serving",
    SCRAP: "Leftover bit",
    SCRUB: "Clean hard",
    SHALE: "Layered rock",
    SHELF: "Wall ledge",
    SHRUB: "Small bush",
    SKULL: "Head bone",
    SLEET: "Icy rain",
    SLOPE: "Ski hill",
    SMELT: "A small fish",
    SNAIL: "Slow shelled crawler",
    SNORE: "Sleep sound",
    SNOUT: "Pig's nose",
    SPADE: "Digging tool",
    SPRAY: "Fine mist",
    SQUID: "Inky sea creature",
    STALK: "Plant stem",
    STASH: "Hidden supply",
    STEEP: "Sharply sloped",
    STILT: "Tall leg pole",
    STOOL: "Backless seat",
    STRAW: "Sipping tube",
    STRIP: "Long thin piece",
    STUMP: "Tree base",
    SWEAT: "Workout drip",
    SWEEP: "Use a broom",
    SWIRL: "Spiral pattern",
    SWORD: "Knight's blade",
    THORN: "Rose's prickle",
    THUMB: "Hand's stubby digit",
    TIMER: "Countdown clock",
    TONIC: "Gin's partner",
    TOPIC: "Subject",
    TRACE: "Faint mark",
    TRAIT: "Characteristic",
    TRIBE: "People group",
    TROUT: "Stream fish",
    TULIP: "Spring bulb flower",
    TUTOR: "Private teacher",
    TWIST: "Turn sharply",
    USHER: "Theater guide",
    VAPOR: "Mist",
    VIGOR: "Energy",
    VINYL: "Old record material",
    VOWEL: "A, E, I, O, or U",
    WAGER: "Bet",
    WALTZ: "Ballroom dance",
    WEARY: "Tired out",
    WEAVE: "Make cloth",
    WEDGE: "Door stopper",
    WHARF: "Boat dock",
    WHISK: "Egg beater",
    WIDOW: "She lost her husband",
    WINCE: "Flinch in pain",
    WOVEN: "Made on a loom",
    YACHT: "Luxury boat",
    YEAST: "Bread riser",
    YIELD: "Give way",
  },
  6: {
    ANIMAL: "Zoo creature",
    ANSWER: "Reply to a question",
    AUTUMN: "Fall season",
    BANANA: "Yellow peel fruit",
    BASKET: "Woven carrier",
    BEAUTY: "Loveliness",
    BLOSSOM: "Spring flower",
    BOTTLE: "Drink container",
    BRANCH: "Tree limb",
    BREATH: "Lungful of air",
    BRIDGE: "River crosser",
    BRIGHT: "Full of light",
    BROKEN: "In pieces",
    BUBBLE: "Soap sphere",
    BUCKET: "Pail",
    BUTTER: "Toast spread",
    BUTTON: "Shirt fastener",
    CAMERA: "Photo taker",
    CANDLE: "Wax light",
    CANYON: "Deep gorge",
    CARPET: "Floor rug",
    CASTLE: "Royal fortress",
    CHANCE: "Opportunity",
    CHANGE: "Make different",
    CHEESE: "Pizza topping",
    CHERRY: "Pie fruit",
    CIRCLE: "Round shape",
    CLEVER: "Smart",
    CLOSET: "Clothes storage",
    COFFEE: "Morning brew",
    COOKIE: "Sweet baked disc",
    CORNER: "Where walls meet",
    COTTON: "Soft fabric fiber",
    COUSIN: "Aunt's child",
    DANGER: "Risk",
    DECIDE: "Make a choice",
    DESERT: "Sandy expanse",
    DINNER: "Evening meal",
    DOLLAR: "Greenback",
    DONKEY: "Stubborn pack animal",
    DRAGON: "Fire-breathing beast",
    DREAMS: "Sleep visions",
    EASILY: "Without trouble",
    ENGINE: "Car's motor",
    ESCAPE: "Break free",
    FAMILY: "Kin",
    FATHER: "Male parent",
    FELLOW: "Guy",
    FINGER: "Hand digit",
    FLOWER: "Garden bloom",
    FOREST: "Wooded area",
    FRIEND: "Pal",
    FROZEN: "Iced over",
    GARAGE: "Car shelter",
    GARDEN: "Flower plot",
    GENTLE: "Soft and mild",
    GOLDEN: "Made of gold",
    GROUND: "Earth underfoot",
    GUITAR: "Strummed instrument",
    HAMMER: "Nail driver",
    HANDLE: "Door grip",
    HAPPEN: "Take place",
    HEALTH: "Wellness",
    HEAVEN: "Sky paradise",
    HELMET: "Head protector",
    HONEST: "Truthful",
    ISLAND: "Land in the sea",
    JACKET: "Light coat",
    JUNGLE: "Dense forest",
    KETTLE: "Tea boiler",
    KITTEN: "Baby cat",
    LADDER: "Climbing rungs",
    LETTER: "Mailed note",
    LISTEN: "Pay attention to sound",
    LITTLE: "Small",
    MARBLE: "Shooter in a game",
    MARKET: "Place to shop",
    MASTER: "Expert",
    MIDDLE: "Center",
    MINUTE: "Sixty seconds",
    MIRROR: "Reflecting glass",
    MODERN: "Up-to-date",
    MONKEY: "Banana lover",
    MOTHER: "Female parent",
    MUFFIN: "Breakfast cake",
    NEEDLE: "Sewing point",
    NIGHTS: "Evenings",
    ORANGE: "Citrus fruit",
    PALACE: "Royal home",
    PARENT: "Mom or dad",
    PARROT: "Talking bird",
    PEANUT: "Ballpark snack",
    PEBBLE: "Small stone",
    PENCIL: "Writing stick",
    PEOPLE: "Folks",
    PEPPER: "Salt's partner",
    PILLOW: "Head cushion",
    PLANET: "Mars or Venus",
    PLENTY: "More than enough",
    POCKET: "Pants pouch",
    POTATO: "Mashed spud",
    PRETTY: "Attractive",
    PURPLE: "Grape color",
    PUZZLE: "Brain teaser",
    RABBIT: "Hopping pet",
    REASON: "The why",
    REMOTE: "Channel changer",
    RESCUE: "Save",
    RIBBON: "Gift bow material",
    RIVERS: "Flowing waters",
    ROCKET: "Space launcher",
    SADDLE: "Horse seat",
    SAFELY: "Without harm",
    SALMON: "Pink fish",
    SAUCER: "Cup's plate",
    SCHOOL: "Place to learn",
    SEASON: "Spring or fall",
    SECOND: "Right after first",
    SECRET: "Hidden info",
    SHADOW: "Cast outline",
    SILENT: "Making no sound",
    SILVER: "Shiny gray metal",
    SIMPLE: "Easy",
    SINGER: "Vocalist",
    SISTER: "Female sibling",
    SMOOTH: "Not bumpy",
    SPIDER: "Eight-legged spinner",
    SPRING: ["Bouncy season", "Leap suddenly"],
    SQUARE: "Four equal sides",
    STREET: "Paved road",
    STRONG: "Powerful",
    SUMMER: "Beach season",
    SUNSET: "Dusk sky show",
    TEMPLE: "Place of worship",
    TENNIS: "Racket sport",
    THIRTY: "Three times ten",
    THREAD: "Sewing strand",
    TICKET: "Show pass",
    TISSUE: "Nose wiper",
    TOMATO: "Salad red",
    TONGUE: "Taste organ",
    TURTLE: "Shelled reptile",
    VALLEY: "Low land between hills",
    VELVET: "Plush fabric",
    WALLET: "Cash holder",
    WALNUT: "Hard-shelled nut",
    WINDOW: "Glass pane",
    WINNER: "Contest victor",
    WINTER: "Cold season",
    WISDOM: "Deep knowledge",
    WIZARD: "Spell caster",
    WONDER: "Marvel",
    YELLOW: "Banana color",
    ZIPPER: "Jacket fastener",
  },
  7: {
    ACTIONS: "Things done",
    AIRPORT: "Plane hub",
    ANCIENT: "Very old",
    ANIMALS: "Zoo dwellers",
    ANOTHER: "One more",
    BALLOON: "Party floater",
    BEDROOM: "Sleeping space",
    BICYCLE: "Pedal-powered ride",
    BLANKET: "Bed cover",
    BROTHER: "Male sibling",
    CABBAGE: "Leafy green head",
    CAPTAIN: "Ship's leader",
    CEILING: "Room's top",
    CHEETAH: "Fastest land animal",
    CHICKEN: "Coop bird",
    CLIMATE: "Region's weather",
    COMPANY: "Business firm",
    COMPUTE: "Do the math",
    CONCERT: "Live music show",
    COTTAGE: "Small country house",
    COUNTRY: "Nation",
    COURAGE: "Bravery",
    CRAYONS: "Coloring sticks",
    CRYSTAL: "Clear gem",
    CULTURE: "Way of life",
    CUPCAKE: "Frosted small cake",
    CURTAIN: "Window cover",
    DENTIST: "Tooth doctor",
    DESSERT: "Sweet course",
    DIAMOND: "Hard gem",
    DOLPHIN: "Smart sea mammal",
    DRAWING: "Pencil art",
    EVENING: "After dusk",
    FACTORY: "Goods maker",
    FEATHER: "Bird's plume",
    FORTUNE: "Great wealth",
    FREEDOM: "Liberty",
    GARDENS: "Flower plots",
    GENERAL: "Top officer",
    GIRAFFE: "Long-necked grazer",
    HARVEST: "Crop gathering",
    HEALTHY: "In good shape",
    HISTORY: "Study of the past",
    HOLIDAY: "Day off",
    JOURNEY: "Long trip",
    JUSTICE: "Fairness",
    KITCHEN: "Cooking room",
    LANTERN: "Carried light",
    LIBRARY: "Book hall",
    MACHINE: "Mechanical device",
    MEASURE: "Take dimensions of",
    MINUTES: "Hour's parts",
    MORNING: "Day's start",
    MOUNTED: "Got on a horse",
    MUSTARD: "Hot-dog topping",
    NATURAL: "From nature",
    NETWORK: "Linked system",
    NOTHING: "Zilch",
    OCTOPUS: "Eight-armed sea creature",
    OUTDOOR: "Open-air",
    PACKAGE: "Mailed parcel",
    PAINTER: "One with a brush",
    PARTNER: "Teammate",
    PATTERN: "Repeating design",
    PENGUIN: "Tuxedoed bird",
    PERFECT: "Flawless",
    PICTURE: "Photo",
    PILLOWS: "Bed cushions",
    POPCORN: "Movie snack",
    PRESENT: "Wrapped gift",
    PROBLEM: "Math question",
    PROMISE: "Solemn vow",
    PROTECT: "Keep safe",
    PUMPKIN: "Halloween gourd",
    RAINBOW: "Sky's color arch",
    READING: "Book time",
    RECIPES: "Cooking guides",
    RESPECT: "High regard",
    SANDALS: "Summer footwear",
    SCIENCE: "Lab study",
    SEASONS: "Spring, summer, fall, winter",
    SERVICE: "Help provided",
    SHELTER: "Place of safety",
    SOLDIER: "Army member",
    SPARKLE: "Glitter",
    STATION: "Train stop",
    STORAGE: "Where things are kept",
    STUDENT: "Class attendee",
    SUNRISE: "Dawn",
    SUNSHINE: "Bright daylight",
    TEACHER: "Class leader",
    THUNDER: "Storm's boom",
    TONIGHT: "This evening",
    TROPHY: "Winner's cup",
    USEFUL: "Handy",
    VICTORY: "A big win",
    VILLAGE: "Small town",
    WEATHER: "Rain or shine",
    WEEKEND: "Saturday and Sunday",
    WELCOME: "Greeting at the door",
    WHISPER: "Soft speech",
    WINNERS: "First-place finishers",
  },
};
