export default {
  3: {
    "ACE": ["Pilot with five kills","Unreturnable serve","Nail the exam","Hole-in-one, to a golfer"],
    "ACT": ["One of five in 'Hamlet'","Put on airs","The 'A' in a triple threat","Circus performer's turn"],
    "ADD": ["Stir in, as an ingredient","Do some carrying, perhaps","Throw in for good measure","Total a column of figures"],
    "AGE": ["What fine wine does","The Stone ___, for one","Number you might fib about","Grow older over time"],
    "AID": ["Band-___, scrape cover","What the Red Cross sends","Visual ___, classroom prop","Lend a hand to"],
    "AIM": ["Take careful ___, line it up","Cupid's specialty","What a mission statement states","A goal one strives for"],
    "AIR": ["Put on the ___, broadcast","Open one's lungs to it","What hot ones rise in","Voice openly, as views"],
    "AKA": "Also known as",
    "ANT": ["Picnic crasher","Aesop's industrious one","Hill dweller","Tiny colony dweller"],
    "APE": ["Mimic to a tee","Tarzan's adoptive kin","Go ___, lose it","Chimp or gorilla"],
    "ARC": ["Noah's vessel, minus an h","Welder's bright flash","A story's character ___"],
    "ARM": ["Twist one to persuade","Branch of the military","Supply with weapons","Limb that ends in a hand"],
    "ART": ["The Louvre's stock-in-trade","State of the ___, cutting-edge","Andy Warhol's field","Painting and sculpture, collectively"],
    "ASH": ["What the phoenix rises from","Wednesday before Lent","Cigar's crumbly end"],
    "ATM": "Cash-dispensing machine",
    "ATV": "Off-road four-wheeler",
    "BAD": ["Michael Jackson album of 1987","Gone off, as milk","My ___, an apology","Naughty, like a misbehaving pup"],
    "BAG": ["In the ___, a sure thing","Old ___, an insult","Land, as a big catch","Tote at the grocery store"],
    "BAR": ["Raise it, set a standard","Behind ___s, jailed","Pass it to practice law","Pub counter where drinks are poured"],
    "BAT": ["Cave-dwelling flier","Go to ___ for, defend","Right off the ___, immediately","Louisville Slugger, e.g."],
    "BAY": ["Hold at ___, keep away","Tampa or Hudson","Sick puppy's mournful sound"],
    "BBQ": "Backyard grilling event",
    "BED": ["Hit the ___, turn in","Oyster's home on the ocean floor","Flower plot","Where you sleep at night"],
    "BEE": ["Spelling contest","Quilting get-together","Busy as a ___","Honey maker in the garden"],
    "BFF": "Closest pal, in texts",
    "BIG": ["The ___ Apple, NYC","Make it ___, hit stardom","Mr. ___, in 'Sex and the City'","Large in size"],
    "BIT": ["Champed at the ___, was eager","Eight make a byte","A horse's mouthpiece"],
    "BOX": ["Spar in the ring","Idiot ___, the TV","Pandora's was trouble","Cardboard shipping container"],
    "BOY": ["Oh ___!, exclamation","Old chap, in Britspeak","Whipping ___, scapegoat","A young lad"],
    "BRB": "'Stepping away briefly' in chat",
    "BTW": "Aside introducer in chat",
    "BUD": ["Pal, casually","Nip it in the ___","What blooms in spring"],
    "BUG": ["Plant a hidden mic","Software glitch","Catch the travel ___","Creepy-crawly critter"],
    "BUS": ["Wheels on it go round and round","Clear the diner table","Throw under the ___, betray","Yellow vehicle for schoolkids"],
    "BUY": ["A good ___, a bargain","Accept as true","___ time, stall","Purchase at the store"],
    "CAB": ["Yellow NYC hailer","Where the trucker sits","Sauvignon, for short"],
    "CAP": ["Put a lid on spending","Graduation toss-up","Feather in one's ___","Baseball headwear with a brim"],
    "CAR": ["Cable ___, hillside ride","Box on a train","Uber arrival","Sedan or coupe"],
    "CAT": ["Let it out of the bag","Cool ___, hep fellow","Jazz musician, in slang","Feline pet that purrs"],
    "CEO": "Top corporate boss",
    "CGI": "A movie's digital effects",
    "COW": ["Sacred one in Hinduism","Cash ___, money-maker","Intimidate into submission","Moo-er in the pasture"],
    "CPR": "Chest-compression rescue method",
    "CRY": ["A far ___ from, very different","Battle ___, rallying shout","For ___ing out loud!","Weep with tears"],
    "CUP": ["Stanley one in hockey","Half a pint, in recipes","It runneth over, in Psalms","Mug for your morning coffee"],
    "CUT": ["Skip, as class","The director's ___ of a film","A ___ above, superior","Slice with scissors"],
    "DAY": ["Carpe diem's 'diem'","Doris of old Hollywood","Call it a ___, knock off","A 24-hour span"],
    "DEN": ["Lion's lair","Man ___, basement retreat","Cub scout group"],
    "DIG": ["Subtle insult","Archaeologist's site","Really ___ it, love it"],
    "DIY": "Build-it-yourself approach",
    "DNA": "Genetic code molecule",
    "DOG": ["Man's best friend","Hot ___ at the ballpark","Fido or Rover","Barking, tail-wagging pet"],
    "DOT": ["Connect the ___s","On the ___, exactly on time","The 'period' in a URL"],
    "DRY": ["Like a sense of humor that's deadpan","Sahara-like","On the wagon","Not at all wet"],
    "EAR": ["Lend an ___, listen","Cob unit of corn","Have an ___ for music","Part you whisper into"],
    "EAT": ["___ crow, admit error","What acid does to metal","Dig in","Consume a meal"],
    "EGG": ["Goose that lays a golden one","Nest ___, savings","___ on, urge forward","Breakfast staple, fried or scrambled"],
    "END": ["The ___ justifies the means","Wits' ___, frustration","Football lineman position","The finish or conclusion"],
    "EOD": "Deadline meaning quitting time",
    "ETA": "Expected arrival time",
    "FAN": ["Devoted follower","Stir up, as flames","It cools you in summer","Concert-goer who adores the band"],
    "FAQ": "Help-page question-and-answer list",
    "FAR": ["A ___ cry, quite different","So ___, so good","Way out yonder","A great distance away"],
    "FEW": ["The Marine motto's 'the ___'","Quite a ___, many","A select handful"],
    "FIG": ["Newton's fruit, in cookies","Don't give a ___, don't care","Biblical leaf"],
    "FIN": ["Shark's giveaway above water","Slangy five-dollar bill","Scuba diver's footwear"],
    "FIT": ["Throw a ___, tantrum","Survival of the ___test","If the shoe ___s","Trim and in good shape"],
    "FIX": ["A quick ___, stopgap","In a ___, in trouble","Rig, as a race","Repair what's broken"],
    "FLY": ["___ on the wall, secret observer","Soup-spoiling insect","Pants zipper area","Travel by plane"],
    "FOG": ["In a ___, dazed","What rolls in off the bay","London's famous pea-souper","Thick mist you can't see through"],
    "FOX": ["Sly one in fables","___ in the henhouse, trouble","Outwit cleverly","Bushy-tailed woodland animal"],
    "FUN": ["Poke ___ at, mock","___ and games, lightheartedness","A barrel of laughs","A good time, enjoyment"],
    "FYI": "Heads-up tag on an email",
    "GAP": ["Generation ___","Mind the ___, subway warning","Khaki retailer","An empty space or opening"],
    "GAS": ["Step on the ___, accelerate","Pass ___, in chemistry class","Run out of ___, tire out","What fuels the car"],
    "GEM": ["Hidden ___, a find","Polished beauty in a ring","Stand-out player, slangily"],
    "GPS": "Navigation satellite system",
    "GUM": ["Where teeth are rooted","Chiclet, e.g.","___ up the works, jam"],
    "GUN": ["Jump the ___, act too soon","Rev, as an engine","Top ___, ace pilot","A pistol or rifle"],
    "GUY": ["Wise ___, smart aleck","Fall ___, scapegoat","Mr. Right, hopefully","A fellow or dude"],
    "HAM": ["Overactor on stage","Radio hobbyist","Easter dinner centerpiece","Pork cut for sandwiches"],
    "HAT": ["Throw one's ___ in the ring","Magician's bunny holder","Old ___, outdated","Headwear like a fedora"],
    "HEN": ["___ party, ladies' night out","Egg producer","Mother of chicks"],
    "HIP": ["With it, dated slang","Joint replaced in surgery","Shoot from the ___, be blunt"],
    "HIT": ["Chart-topper","___ the road, leave","A smash at the box office","Strike with a fist"],
    "HOT": ["Caught red-handed, slangily","In ___ water, in trouble","All the rage","Like a summer scorcher"],
    "HUG": ["Bear's tight squeeze","Hold close","What XOXO's O stands for","A warm embrace"],
    "ICE": ["Put on ___, postpone","Break the ___, ease tension","Skater's surface","Frozen water in cubes"],
    "ICU": "Critical-care hospital ward",
    "IDO": "Altar promise",
    "ILL": ["Speak ___ of, badmouth","Under the weather","House M.D.'s patients, e.g."],
    "INK": ["Get some, at a tattoo parlor","Squid's smokescreen","Sign on the dotted line, with it"],
    "IOU": "Note for borrowed cash",
    "JAM": ["Traffic snarl","In a ___, in trouble","Musicians' impromptu session","Fruit spread for toast"],
    "JAR": ["Cookie holder","Set one's nerves on edge","Mason's container","Glass container with a lid"],
    "JET": ["Set ___, world traveler","Pitch-black hue","Whirlpool tub spout","Fast passenger plane"],
    "JOB": ["The daily grind","Snow ___, deception","Patient one of the Bible","Nine-to-five employment"],
    "JOY": ["Pride and ___","Dishwashing liquid brand","Holiday emotion in carols","Great happiness"],
    "KEY": ["Florida's Largo or West","It works the lock","The legend on a map","A piano has 88 of them"],
    "KID": ["Pull one's leg","New ___ on the block","Young goat","A child or youngster"],
    "LAP": ["Once around the track","Cat's favorite perch","___ of luxury, comfort","Where you sit on Santa"],
    "LAW": ["___ of the land","Brother- or mother-in- ___","Murphy's, famously","A rule you must obey"],
    "LEG": ["Pull one's ___, kid","Final ___ of a journey","Shake a ___, hurry","Limb you walk on"],
    "LID": ["Put a ___ on it, quiet down","Eye cover","Flip one's ___, get angry"],
    "LIP": ["Stiff upper ___, composure","Sass, as in 'don't give me ___'","Read my ___s","Rim of a cup or pitcher"],
    "LOG": ["Captain's daily record","Sleep like a ___","Saw one, snore","Firewood chunk"],
    "LOL": "Online sign of amusement",
    "LOT": ["A ___ riding on it, much at stake","Used-car ___","Drew the short straw, met one's ___","A whole bunch, a great deal"],
    "LOW": ["Make a cattle sound","Lying ___, hiding","At an all-time ___"],
    "MAD": ["___ as a hatter","Steaming, angrily","___ Men, ad-world drama","Angry and furious"],
    "MAN": ["Staff, as a post","The ___, authority","Best ___ at a wedding","An adult male"],
    "MAP": ["Put on the ___, make famous","Folding glovebox item","Outline, as a plan","A guide to roads and cities"],
    "MAT": ["Welcome ___ at the door","Wrestler's surface","Yoga prop"],
    "MIA": "Battlefield disappearance status",
    "MIX": ["___ it up, scuffle","Trail ___, hiker's snack","What a DJ does","Stir ingredients together"],
    "MOM": ["The boss of the house, often","Her day is in May","Palindromic parent","Mother, affectionately"],
    "MRI": "Magnetic body-imaging scan",
    "MUD": ["Throw ___, sling insults","Clear as ___, confusing","Pig's bath of choice"],
    "MUG": ["Make a face for the camera","Hold-up artist's verb","Beer stein cousin"],
    "MVP": "Standout player's award",
    "NAP": ["Cat's quick rest","Power ___, midday recharge","Velvety fabric surface","Short daytime sleep"],
    "NDA": "Secrecy contract, for short",
    "NET": ["After taxes, take-home","Trawler's catcher","Safety ___, fallback","Tennis divider over the court"],
    "NEW": ["Brand-___, just-bought","What's ___?, greeting","Turn over a ___ leaf"],
    "NOD": ["Get the ___, gain approval","Off to dreamland, with off","Yes, silently"],
    "NUT": ["Hard ___ to crack","Bolt's partner","Sports ___, big fan"],
    "OAK": ["Mighty acorn dropper","Sturdy furniture wood","Knock on it for luck"],
    "OAR": ["Put one's ___ in, meddle","Rower's tool","Galley slave's job"],
    "ODD": ["The ___ one out","Like 1, 3, and 5","___ jobs, miscellaneous tasks"],
    "OIL": ["Pour ___ on troubled waters","Texas tea","Burn the midnight ___"],
    "OLD": ["Same ___ story","Up in years","___ hat, passé"],
    "OMG": "Texted gasp of surprise",
    "OWL": ["Night ___, late riser","Wise bird in fables","Hooter in the dark"],
    "PAN": ["Trash, as a review","Out of the frying ___","Peter ___, Neverland boy"],
    "PAW": ["Lion's foot","Handle clumsily","Cat's velvet toucher"],
    "PEA": ["Princess felt one under mattresses","___ in a pod, identical","Pod's tiny green sphere"],
    "PEN": ["Mightier than the sword, they say","Pig's enclosure","Slammer, slangily"],
    "PET": ["Teacher's favorite","___ peeve, irritation","Stroke gently"],
    "PIE": ["Easy as ___","Humble ___, contrition","Pizza, essentially"],
    "PIG": ["Hog the spotlight, like one","___ out, overeat","When ___s fly, never"],
    "PIN": ["Bowler's target","On ___s and needles, anxious","Wrestler's win move"],
    "PIT": ["The ___s, the worst","Where racers refuel","Peach's hard center"],
    "POT": ["Sweeten the ___, raise the stakes","Poker's center stash","Go to ___, decline"],
    "POV": "Narrative viewpoint, briefly",
    "PTA": "School parents' group",
    "PTO": "Worker's paid days off",
    "PUP": ["Kennel newcomer","___ tent, small shelter","Sea lion's young"],
    "RAG": ["Tabloid, dismissively","___ on, tease","Chew the ___, chat"],
    "RAT": ["Snitch on, slangily","Smell a ___, sense trouble","Lab maze runner"],
    "RAW": ["Sushi-grade state","Get a ___ deal, be wronged","In the buff, with 'the'"],
    "RED": ["In the ___, losing money","Caught ___-handed","Paint the town ___"],
    "RIB": ["Tease good-naturedly","Adam gave one up, in Genesis","Barbecue rack piece"],
    "RIM": ["Pacific ___, ocean border","Hoop without a net","Glass's salty edge, for margaritas"],
    "RIP": "Tombstone abbreviation",
    "ROW": ["Skid ___, rough district","Pull the oars","A ___ to hoe, hard task"],
    "RUG": ["Sweep it under the ___, hide","Toupee, slangily","Persian floor cover"],
    "RUN": ["Make a break for it","Hit a home ___","___ for office"],
    "SAD": ["Down in the dumps","___ sack, gloomy sort","A ___ state of affairs"],
    "SEA": ["The seven ___s","Lost at ___, confused","Briny deep"],
    "SET": ["Ready, ___, go!","Tennis match unit","The sun does it in the west"],
    "SIP": ["Take a small taste","Nurse a drink slowly","Wine taster's bit"],
    "SIT": ["Pose for a portrait","Take a load off","Command to Fido"],
    "SKY": ["The ___'s the limit","Pie in the ___, fantasy","Where larks soar"],
    "SLY": ["On the ___, secretly","Crafty as a fox","Stallone, to fans"],
    "SON": ["Like father, like ___","Prodigal one of parable","Heir, often"],
    "SOS": "Distress signal in dots and dashes",
    "SPA": ["Place to get pampered","Hot-tub haven","Day of facials and massages"],
    "SUN": ["Make hay while it shines","A place in the ___, glory","Sol, to us"],
    "SUV": "Bulky family vehicle, briefly",
    "TAG": ["Playground chase game","Price marker","You're it!, in a game"],
    "TAN": ["Beach goal","Khaki shade","___ someone's hide, scold"],
    "TAP": ["On ___, available","Fred Astaire's dance","Phone surveillance"],
    "TAR": ["Beat the ___ out of, thrash","Road-sealing goo","Old salt, a sailor"],
    "TBD": "Not yet decided, on a schedule",
    "TBH": "Candid-admission text tag",
    "TEA": ["Spill the ___, share gossip","Boston Harbor's 1773 dump","Afternoon British ritual"],
    "TEN": ["Perfect gymnast's score","Hang ___, surf","A Bo Derek, looks-wise"],
    "TIE": ["Deadlock, no winner","Windsor knot wear","Railroad track support"],
    "TIP": ["Iceberg's visible bit","Gratuity for the waiter","Hot ___, inside scoop"],
    "TLC": "Gentle care and attention",
    "TOE": ["___ the line, conform","Stub it painfully","Pinky's foot counterpart"],
    "TOP": ["Over the ___, excessive","Big ___, circus tent","Outdo, surpass"],
    "TOY": ["Lap dog breed, like a poodle","Play around with an idea","FAO Schwarz stock"],
    "TUB": ["Rub-a-dub-dub spot","Butter container","Hot ___ on the deck"],
    "TWO": ["It takes ___ to tango","Put in one's ___ cents","A couple"],
    "UFO": "Mysterious sky object",
    "URL": "Web address, briefly",
    "USE": ["No ___ crying over spilt milk","What's it good for?","Put to work"],
    "VAN": ["Moving-day rental","In the ___guard, leading","Down by the river ___, in song"],
    "VET": ["Pet's doctor","Check out carefully","Former soldier, for short"],
    "VIP": "Honored guest, for short",
    "WAR": ["___ and Peace, Tolstoy epic","Tug of ___","All's fair in love and it"],
    "WAX": ["Wane's opposite, for the moon","Buff to a shine","Candle's makeup"],
    "WEB": ["Charlotte spun one","The worldwide one","Tangled one of deceit"],
    "WET": ["___ blanket, party pooper","Fresh-paint warning","All ___, mistaken"],
    "WIN": ["___ hands down, dominate","Take the gold","A ___-___ for everyone"],
    "WOW": ["Bowl over, impress","Palindromic gasp","Knock one's socks off"],
    "WWW": "Web address opener",
    "YES": ["Affirmative","___-man, sycophant","Nod's spoken version"],
    "ZIP": ["Nada, zero","Jacket fastener's job","Move with pep"],
    "ZOO": ["Madhouse, figuratively","San Diego's famous one","Where pandas draw crowds"],
  },
  4: {
    "ABIT": "Somewhat",
    "ABLE": ["Got the chops for it","Up to the task"],
    "ACID": ["It turns litmus paper red","Vinegar's sour component"],
    "ACRE": "About a football field in size",
    "AREA": ["Length times width, in math","A region or zone"],
    "ARMY": ["G.I. Joe's branch","Soldiers' fighting force"],
    "ASAP": "Right away, in a memo",
    "ASIF": "Sarcastic 'yeah, right'",
    "ASIS": "Sold with no returns",
    "ATAD": "Just a little",
    "AUNT": "Em, to Dorothy",
    "AUTO": "Car, for short",
    "AWOL": "Gone from the army without leave",
    "BABY": ["It cries for a 2 a.m. feeding","Newborn in a crib"],
    "BAKE": "Pop it in the oven",
    "BALL": ["What you bounce or throw","Round toy you kick"],
    "BAND": ["Rockers out on tour","Musical group with a drummer"],
    "BANK": ["Place with a big vault","Where you deposit money"],
    "BARK": ["Dog's sound","Reputedly worse than the actual bite"],
    "BARN": "Where the cows turn in",
    "BASE": ["First, second, or third, on the diamond","The bottom support of a column"],
    "BATH": ["A good long soak","A tub full of suds"],
    "BEAD": "One on an abacus",
    "BEAM": "Smile from ear to ear",
    "BEAN": "Coffee, before it's ground",
    "BEAR": ["Wall Street pessimist","Honey-loving forest beast"],
    "BEAT": ["What a cop walks","The rhythm of a song"],
    "BELL": ["It tolls for thee","It rings at the front door"],
    "BELT": ["Black one, in karate","It holds up your pants"],
    "BEST": ["Tops, the cream of the crop","Number one, the finest"],
    "BIKE": ["Handlebars and two pedals","Pedal-powered two-wheeler"],
    "BIRD": ["One in the hand, they say","Feathered, winged creature"],
    "BITE": ["Bark is worse than it","Take a chomp of an apple"],
    "BLUE": ["How you feel when down","The sky's color on a clear day"],
    "BOAT": ["We're all in the same one, they say","A canoe or yacht"],
    "BODY": ["The whole physical you","Your skeleton, muscles, and all"],
    "BOLD": ["Brave and daring","Fearless and gutsy"],
    "BONE": ["What you pick with someone","What the dog buries in the yard"],
    "BOOK": ["Don't judge it by its cover","A novel on the shelf"],
    "BOOT": ["Italy's shape on the map","Footwear for hiking"],
    "BORN": "First entered the world",
    "BOSS": "The big cheese in charge",
    "BOWL": "It holds your cereal",
    "CAGE": "Nicolas of Hollywood",
    "CAKE": ["Have it and eat it too, they say","Birthday dessert with candles"],
    "CALM": ["Cool and unruffled","Peaceful and serene"],
    "CAMP": "Where the tents go up",
    "CARD": ["One in a deck of 52","Greeting mailed on birthdays"],
    "CARE": ["Look after lovingly","Tend to lovingly"],
    "CART": "What you push at the store",
    "CASH": ["Cold, hard greenbacks","Bills and coins, not credit"],
    "CAVE": ["Underground hollow","Finally give in after holding out"],
    "CHEF": "The boss of the kitchen",
    "CHIN": "Keep yours up",
    "CITY": ["The Big Apple, e.g.","A metropolis with skyscrapers"],
    "CLAP": "Applaud with both hands",
    "CLAW": "A crab's pincer",
    "CLAY": "What a potter shapes",
    "CLUB": ["Golfer's choice","Night spot for dancing"],
    "COAT": ["What you grab when it's cold","Winter outerwear"],
    "COIN": ["Heads-or-tails flipper","A penny or a nickel"],
    "COLD": ["Jacket weather","Freezing, like deep winter"],
    "COOK": ["The one at the stove","One who prepares the meals"],
    "COOL": ["Cucumber's comparison","Pleasantly chilly"],
    "CORN": ["It's eaten off the cob","Yellow kernels at a barbecue"],
    "COZY": "Snug as a bug",
    "CREW": "The rowing team",
    "CROP": ["The farmer's yield","What a farmer harvests"],
    "CUBE": "Rubik's puzzle shape",
    "CURL": "A ringlet of hair",
    "DARK": ["Lights-out black","Without any light"],
    "DEAL": ["A real steal of a bargain","A bargain at the store"],
    "DEEP": ["Down at the bottom of the sea","Far down, not shallow"],
    "DESK": ["Where the office work happens","Where you do your homework"],
    "DIAL": "Spin it on a rotary phone",
    "DICE": "A pair tumbles in Vegas",
    "DISH": ["Spill it, as gossip","A plate at the dinner table"],
    "DOOR": ["When one closes, another opens","You knock before entering it"],
    "DOVE": "Peace's feathered symbol",
    "DRAW": ["What a tied game ends in","Sketch with a pencil"],
    "DROP": ["Let it slip and fall","A single bead of rain"],
    "DRUM": ["Beat it in the band","A snare in a marching band"],
    "DUCK": ["Get out of the way, fast","A quacker at the pond"],
    "DUST": "Bite the ___, in a saying",
    "EACH": "Every last one",
    "EARN": ["Work to get it","Bring home a paycheck"],
    "EAST": ["Where the sun rises","The opposite of west"],
    "EASY": ["A walk in the park","Simple, not hard at all"],
    "ECHO": ["Bounced-back sound","The canyon's habit of repeating you"],
    "EDGE": ["The very brink","The sharp side of a knife"],
    "ETAL": "‘And others,’ in a citation",
    "FACE": ["What a clock has","Your eyes, nose, and mouth"],
    "FACT": ["It's stranger than fiction, they say","A proven, true statement"],
    "FAIR": ["Even-handed and just","Just and impartial"],
    "FALL": ["Pride comes before it","Autumn, season of raking"],
    "FARM": ["Where the crops grow","Where pigs and cows live"],
    "FAST": ["Quick as lightning","Speedy, like a race car"],
    "FEAR": ["What a horror flick stirs up","Being scared"],
    "FERN": "Feathery shade-loving plant",
    "FILM": ["What's shot in Hollywood","A feature at the cinema"],
    "FIRE": ["The campsite's crackling blaze","Flames in the hearth"],
    "FISH": ["Plenty of them in the sea, they say","What you catch with a rod"],
    "FIST": ["A clenched, ready-to-bump hand","A balled-up hand"],
    "FLAG": ["Old Glory, e.g.","Star-spangled banner on a pole"],
    "FLAT": ["How a pancake lies","Level and even"],
    "FLEA": "Tiny hopper on a dog",
    "FLEW": "Took to the skies",
    "FOAM": "Froth atop a cappuccino",
    "FOLD": ["Quit the poker hand","Crease the laundry"],
    "FOND": "Holding someone dear",
    "FOOD": ["Fuel for the body","Groceries to eat"],
    "FOOT": ["A ruler's length","Where your toes are"],
    "FORK": ["A road might have one","Utensil beside the knife"],
    "FORM": ["Shape or figure","Fill out a paper application"],
    "FREE": ["Without a price tag","Costing nothing"],
    "FROG": "Prince in disguise, in tales",
    "FUEL": "What you pump at the station",
    "FULL": ["Stuffed after the feast","Filled to the brim"],
    "GAME": ["A match to be won","Monopoly or chess"],
    "GATE": ["Swing it open at the fence","Entrance in a fence"],
    "GIFT": ["It's the thought that counts with it","A present with a bow"],
    "GIRL": "A young lass",
    "GLAD": "Tickled pink",
    "GLOW": "A firefly's soft light",
    "GOAL": "What the striker aims for",
    "GOAT": "The greatest, in sports slang",
    "GOLD": "What the first-place medal is",
    "GOOD": "The opposite of evil",
    "GRAB": "Snatch it in a hurry",
    "GRAY": "Neither black nor white",
    "GROW": "Shoot up, as a sunflower",
    "HALF": "What two quarters make",
    "HALL": "Where the monitor patrols",
    "HAND": "Round of applause, or what gives it",
    "HARD": "Tough as nails",
    "HEAD": "Lead the expedition",
    "HEAT": "Miami NBA team",
    "HERD": "Round 'em up, cowboy",
    "HERO": "The one in the cape",
    "HIDE": "Play seek's partner",
    "HIGH": "Cloud nine feeling",
    "HILL": "Capitol ___, D.C. power center",
    "HINT": "Nudge in the right direction",
    "HIVE": "Where the queen holds court",
    "HOLD": "Don't hang up just yet",
    "HOLE": "The golfer's target",
    "HOME": "Where the heart is, they say",
    "HOPE": "Springs eternal, per Pope",
    "HORN": "What the impatient driver leans on",
    "HOUR": "Happy ___ at the bar",
    "ICON": "Tap-to-open little picture",
    "IDEA": "Lightbulb moment",
    "IMHO": "Opinion-flagging chat acronym",
    "IMIN": "Count me as participating",
    "INON": "Aware of, as a secret",
    "IRON": "Pump it at the gym, or press with it",
    "ITEM": "A couple, in gossip columns",
    "JOKE": "It's no laughing matter when it bombs",
    "JUMP": "Bungee, e.g.",
    "KICK": "What gives a drink its strong jolt",
    "KIND": "The milk-of-human variety",
    "KING": "Top card, or top chess piece",
    "KISS": "Hershey's teardrop treat",
    "KNEE": "What you bend to propose",
    "KNOW": "Be in the ___, clued in",
    "LACE": "Delicate trim, or what to tie",
    "LAKE": "Tahoe or Erie",
    "LAMP": "Genie's old address",
    "LAND": "Touch down at last",
    "LATE": "Better than never, they say",
    "LAWN": "What the suburbanite mows",
    "LEAF": "It turns in the fall",
    "LEAP": "What you do before you look, ideally not",
    "LEFT": ["Not right","Already headed out the door"],
    "LEND": "Give, with the expectation of return",
    "LIFE": "Cereal with Mikey, famously",
    "LIFT": "Spot me on this last ___",
    "LIME": "What tops a Corona",
    "LINE": "Wait in it at the DMV",
    "LION": "Cowardly one in Oz",
    "LIST": "What Santa checks twice",
    "LOAF": "Do nothing, or a whole bread",
    "LOCK": "A sure thing, in slang",
    "LONG": "What the wait at the DMV is",
    "LOOK": "Steal a glance",
    "LOUD": "Turned up to eleven",
    "LOVE": "Tennis score of nothing",
    "LUCK": "What the four-leaf clover brings",
    "MAIL": "Snail ___, the old-fashioned kind",
    "MANY": "More than a few",
    "MASK": "Halloween face cover",
    "MAZE": "Where the rat hunts for cheese",
    "MEAL": "Square one, ideally three a day",
    "MEAT": "Where's the beef? Right here",
    "MELT": "What the ice cream does in July",
    "MENU": "What the waiter hands you",
    "MILD": "Salsa's tamest setting",
    "MILK": "It does a body good, per ads",
    "MIND": "Mom said never to lose it",
    "MINT": "Where money is made, or a fresh herb",
    "MOON": "What the cow jumped over",
    "MOST": "The lion's share",
    "MOTH": "It heads straight for the flame",
    "NAIL": ["Hammer's target","To absolutely crush it, slangily"],
    "NAME": "Drop it to seem connected",
    "NASA": "American space agency",
    "NEAR": "Within arm's reach",
    "NEAT": "How the whiskey purist takes it",
    "NEST": "Empty ___, after the kids leave",
    "NICE": "French Riviera city, or just plain pleasant",
    "NOON": "When the clock hands point straight up",
    "NOSE": "It knows, in old ads",
    "NOTE": "Leave it on the fridge",
    "OHNO": "Yikes!",
    "OPEN": "The sign flips to it at nine",
    "ORSO": "Approximately, after a number",
    "OVEN": ["Baking box","Where cookies catch their golden tan"],
    "PACK": "What the wolves run in",
    "PAGE": "Summon over the intercom, or a sheet to turn",
    "PAIL": "Jack and Jill's water carrier",
    "PAIN": "No gain without it, they say",
    "PAIR": "What two of a kind make",
    "PALM": "Where the fortune teller looks",
    "PARK": "Leave the car here, or a green space",
    "PART": "The actor's role, or a piece of the whole",
    "PATH": "The road less traveled, perhaps",
    "PEAK": "Where the climber plants the flag",
    "PEAR": "Partridge's tree, in song",
    "PILE": "What leaves make in autumn",
    "PINE": "Yearn, or a Christmas tree",
    "PINK": "Tickled ___, delighted",
    "PLAN": "What best-laid ones go awry",
    "PLAY": "Shakespeare wrote 37 of them",
    "PLUM": "A cushy assignment, figuratively",
    "PLUS": "The good side of the ledger",
    "POEM": "Roses are red, e.g.",
    "POND": "The big ___, the Atlantic, informally",
    "POOL": "Where you do laps, or a shared fund",
    "POUR": "It never rains but it does this",
    "PROP": "The skull Hamlet holds, e.g.",
    "PULL": "Have some ___, or some clout",
    "PUSH": "Come to shove's partner",
    "QUIZ": "Pop ___, the surprise kind",
    "RACE": "The tortoise won it, slowly",
    "RAFT": "Huck Finn's river ride",
    "RAIN": "What April brings before May flowers",
    "RARE": "How the carnivore likes the steak",
    "READ": "What you do with the room, idiomatically",
    "REST": "What the weary need, or musical silence",
    "RICE": "Aromatic basmati, e.g.",
    "RICH": "Filthy ___, loaded",
    "RIDE": "Cool wheels, in slang",
    "RING": ["Finger band","Boxer's battleground"],
    "RIPE": "Ready for picking",
    "RISE": "What dough does, or what stars do",
    "ROAD": "Where the rubber meets it",
    "ROCK": "Between a hard place and this",
    "ROLE": "The lead one, in a film",
    "ROOF": "Hit the ___, lose your temper",
    "ROOM": "Elbow ___, breathing space",
    "ROOT": "Cheer for the home team, or what anchors a plant",
    "ROPE": "Learn the ___s, get the hang of it",
    "ROSE": "What's by any other name, per the Bard",
    "RSVP": "Invitation reply request",
    "RUDE": "Awakening that's unwelcome",
    "RUSH": "Gold ___ of 1849",
    "SAFE": "The vault, or out of danger",
    "SAIL": "Set ___, ship out",
    "SALT": "Worth one's ___, deserving",
    "SAND": "What the hourglass measures with",
    "SEAL": ["Arctic swimmer","Shut it so no air escapes"],
    "SEAT": "Take a load off in it",
    "SEED": "From this an oak grows",
    "SEEK": "Hide-and-___ partner",
    "SELL": "Hard ___, pushy pitch",
    "SHIP": "Abandon it when it's sinking",
    "SHOE": "If it fits, wear it",
    "SHOP": "Talk ___, discuss work",
    "SHOW": "Steal the ___, upstage everyone",
    "SHUT": "___ the door, the cold's getting in",
    "SICK": "Out ___, calling in",
    "SIDE": "Fries, e.g., with the main",
    "SILK": "Smooth as ___, very smooth",
    "SING": "Spill the beans, in mob slang",
    "SINK": "Everything but the kitchen ___",
    "SITE": "Where the building goes up",
    "SIZE": "Cut someone down to it",
    "SKIN": "Saved by the ___ of one's teeth",
    "SLED": "Rosebud, in 'Citizen Kane'",
    "SLOW": "How molasses moves in January",
    "SNOW": "What the plow clears",
    "SOAP": "A daytime drama, for short",
    "SOCK": "Where the thrifty hide cash, idiomatically",
    "SOFT": "Have a ___ spot for, be fond of",
    "SOIL": "What the farmer tills",
    "SONG": "Going for a ___, dirt cheap",
    "SOSO": "Just okay",
    "SOUP": "From ___ to nuts, start to finish",
    "SOUR": "How grapes turn in Aesop",
    "STAR": ["Night sky twinkler","The one with top billing tonight"],
    "STAY": "Granted by the judge to delay",
    "STEM": "From this the flower rises",
    "STEP": "Watch your ___, mind the gap",
    "STOP": "What the bus does at the corner",
    "SWIM": "Sink or ___, do or die",
    "TAIL": "What the dog chases in circles",
    "TALL": "A ___ order, a big ask",
    "TAME": "Domesticate the lion",
    "TANK": "Where Nemo ended up, in Pixar",
    "TAPE": "Red ___, bureaucratic delay",
    "TASK": "Take someone to ___, scold them",
    "TEAM": "There's no 'I' in it",
    "TEAR": "It rolls down at the sad movie",
    "TELL": "The poker giveaway, or to inform",
    "TENT": "Big ___ revival, or campsite shelter",
    "TEST": "Stand the ___ of time",
    "TGIF": "End-of-workweek cheer",
    "TIDE": ["Ocean's rise and fall","It rolls in, then slips away"],
    "TIDY": "A ___ sum, a lot of money",
    "TIME": "It flies when you're having fun",
    "TINY": "Tim of Dickens, or very small",
    "TIRE": "It goes flat at the worst time",
    "TONE": "Set the ___, establish the mood",
    "TOOL": "The right one for the job",
    "TORN": "Can't decide, pulled both ways",
    "TOWN": "Go to ___, do it with gusto",
    "TREE": "Bark up the wrong one",
    "TRIP": "Guilt ___, manipulation tactic",
    "TRUE": "Blue's partner, in loyalty",
    "TUNE": "Carry a ___, sing on key",
    "TURN": "It's mine, not yours, in a game",
    "TWIN": "One of two peas in a pod",
    "UPTO": "It’s ___ you",
    "VASE": "Where the roses go on display",
    "VAST": "A ___ wasteland, said of early TV",
    "VOTE": "Cast it on the first Tuesday",
    "WAIT": "Lie in ___, ambush",
    "WAKE": "Smell the coffee and do this",
    "WALK": "Take a hike, more genteelly",
    "WALL": "Off the ___, eccentric",
    "WARM": "Getting ___, close to the answer",
    "WASH": "It'll all come out in the ___",
    "WAVE": ["Ocean swell","Stadium ripple"],
    "WEAK": "A ___ link in the chain",
    "WEAR": "___ and tear, gradual damage",
    "WEEK": "Span of seven days",
    "WEST": "Go ___, young man, per Greeley",
    "WIDE": "Far and ___, everywhere",
    "WIFI": "Wireless internet access",
    "WILD": "Run ___, get out of control",
    "WIND": "Second ___, renewed energy",
    "WING": "Buffalo ___, game-day snack",
    "WISE": "Old and ___, like the owl",
    "WISH": "Blow out the candles and make one",
    "WOLF": "Cry ___, raise a false alarm",
    "WOOD": "Knock on it for luck",
    "WORD": "Keep your ___, honor a promise",
    "WORK": "All ___ and no play, per the proverb",
    "WORM": "The early bird gets it",
    "YARD": "The whole nine ___s, everything",
    "YEAR": "A trip around the sun",
    "YOLO": "You only live once, in textspeak",
    "ZERO": "___ in, take aim",
    "ZONE": "In the ___, totally focused",
  },
  5: {
    "ABBEY": "Monastery for monks or nuns",
    "ABOVE": "Up over your head",
    "ACORN": "Oak tree's seed",
    "ACTOR": "One always playing a part",
    "ACTUP": "Misbehave loudly",
    "ADDUP": "Total a column",
    "ADMIT": "Confess to",
    "ADOBE": "Sun-dried brick, or a software giant",
    "ADULT": "No longer a kid",
    "AGAIN": "Once more",
    "AGENT": "007, for one",
    "AGILE": "Nimble and quick",
    "AGREE": "See eye to eye",
    "AHEAD": "In front",
    "AISLE": "Window's seat alternative",
    "ALARM": "It goes off at the crack of dawn",
    "ALBUM": "The Beatles' 'Abbey Road,' e.g.",
    "ALERT": "Wide awake and watchful",
    "ALIVE": "Still kicking",
    "ALLIN": "Fully committed",
    "ALLOW": "Give the green light to",
    "ALONE": "Flying solo",
    "ALONG": "Tag ___, come too",
    "ALPHA": "Top dog in the pack",
    "AMUSE": "Tickle the funny bone",
    "ANGEL": "One with a halo and wings",
    "ANGER": "What you count to ten to cool",
    "ANGLE": "A right one is ninety degrees",
    "ANGRY": "Filled with rage",
    "ANKLE": "It gets twisted on a curb",
    "APART": "Worlds ___, far from alike",
    "APPLE": "It keeps the doctor away, they say",
    "APPLY": "Submit a job request",
    "APRON": "It keeps the chef's shirt clean",
    "ARENA": "Where gladiators once fought",
    "ARGUE": "Go back and forth",
    "ARISE": "Come up, as a problem",
    "ARRAY": "Impressive display",
    "ARROW": "Cupid's pointed tool",
    "ASIDE": "A whisper to the audience",
    "ASSET": "Valuable possession",
    "ATALL": "In any way whatsoever",
    "ATTIC": "Where keepsakes gather dust",
    "AUDIO": "The sound half of a video",
    "AUDIT": "Financial examination",
    "AVOID": "Give a wide berth to",
    "AWAKE": "Up at 3 a.m., say",
    "AWARD": "What the winner takes home",
    "AWARE": "Hip to what's going on",
    "BACON": "It brings home the paycheck, in a saying",
    "BADGE": "A detective flashes it",
    "BADLY": "Poorly done",
    "BAKER": "A dozen-plus-one namesake",
    "BARGE": "___ in, interrupt rudely",
    "BASIC": "Nothing fancy about it",
    "BASIL": "Herb in pesto",
    "BASIN": "Bowl under the faucet",
    "BATCH": "What cookies bake in, by the dozen",
    "BEACH": "Where you build sandcastles",
    "BEARD": "Santa's white whiskers",
    "BEAST": "Wild animal",
    "BEGIN": "Get the ball rolling",
    "BELLY": "Stomach area",
    "BELOW": "Underneath",
    "BENCH": "Where the subs sit",
    "BERET": "Flat French cap",
    "BERRY": "Straw- or blue- ender",
    "BIBLE": "Christian holy book",
    "BIRTH": "The very start of life",
    "BLACK": "Color of a starless night",
    "BLADE": "The sharp part of a razor",
    "BLAME": "Pin the fault on",
    "BLANK": "Fill-in-the-___ space",
    "BLAST": "A real ball of a time",
    "BLAZE": "Roaring fire",
    "BLEND": "What a smoothie maker does",
    "BLINK": "It happens in the ___ of an eye",
    "BLOCK": "Writer's ___, creative stall",
    "BLOOD": "Red fluid in veins",
    "BLOOM": "What a rose does in spring",
    "BLOWN": "Past tense of blow",
    "BLUFF": "Fake confidence in poker",
    "BLUNT": "Not sharp",
    "BLURB": "Promotional book-jacket text",
    "BLUSH": "Turn red at a compliment",
    "BOARD": "Plank you might walk",
    "BOAST": "Toot your own horn",
    "BONUS": "A little extra in the paycheck",
    "BOOST": "A leg up",
    "BOOTH": "Diner seat, or a phone relic",
    "BOUND": "Honor-___, duty-driven",
    "BRACE": "___ for impact, prepare",
    "BRAID": "Woven plait of hair",
    "BRAIN": "The body's command center",
    "BRAKE": "Pump it to stop",
    "BRAND": "Nike or Apple, e.g.",
    "BRASS": "Top ___, the higher-ups",
    "BRAVE": "Not scared one bit",
    "BREAD": "What you knead and bake",
    "BREAK": "What you give a tired worker",
    "BREED": "Lab or poodle, e.g.",
    "BRIBE": "Illegal payment for a favor",
    "BRICK": "One unit in a wall",
    "BRIDE": "Woman at her wedding",
    "BRIEF": "Over in no time",
    "BRING": "Tote it along",
    "BROAD": "Wide open",
    "BROKE": "Flat ___, penniless",
    "BROOK": "Small stream",
    "BROOM": "A witch's ride",
    "BROTH": "Clear soup base",
    "BROWN": "UPS truck color",
    "BRUSH": "What an artist wields",
    "BUDDY": "Close pal",
    "BUGLE": "It sounds reveille at dawn",
    "BUILD": "Raise from the ground up",
    "BULLY": "Schoolyard tormentor",
    "BUNCH": "A whole slew of them",
    "BUNNY": "Easter's hopping mascot",
    "BURST": "Pop suddenly",
    "BUYER": "One who purchases",
    "CABIN": "Log home in the woods",
    "CABLE": "How TV used to come in",
    "CAMEL": "Humped desert animal",
    "CANAL": "Panama's famous one",
    "CANDY": "Halloween haul",
    "CANOE": "Paddled narrow boat",
    "CARGO": "What a freighter hauls",
    "CAROL": "Christmas song",
    "CARVE": "___ out a niche, make your mark",
    "CATCH": "Grab a thrown ball",
    "CAUSE": "Reason something happens",
    "CEDAR": "Fragrant evergreen wood",
    "CHAIN": "Links joined together",
    "CHAIR": "Musical ___s prize",
    "CHALK": "It squeaks on the board",
    "CHARM": "Bracelet dangler",
    "CHART": "It tracks the ups and downs",
    "CHASE": "Give hot pursuit",
    "CHEAP": "Light on the wallet",
    "CHEEK": "Side of the face",
    "CHEER": "What fans do for the home team",
    "CHESS": "Game with a king and queen",
    "CHEST": "Where the loot gets buried",
    "CHIEF": "Tribal leader",
    "CHILD": "Not yet grown",
    "CHILI": "Spicy bean stew",
    "CHILL": "Kick back and relax",
    "CHIME": "___ in, add your two cents",
    "CHOIR": "Preach to the ___, tell the converted",
    "CHORD": "Strike a ___, resonate",
    "CHORE": "Household task",
    "CHUNK": "A big ___ of change",
    "CHUTE": "Sliding passage for laundry",
    "CIDER": "Hard or sweet apple drink",
    "CIVIC": "___ duty, like jury service",
    "CIVIL": "Polite and courteous",
    "CLAIM": "Stake your ___",
    "CLAMP": "Tool that holds tight",
    "CLASP": "Necklace's little hook",
    "CLASS": "Where the teacher teaches",
    "CLEAN": "Squeaky and spotless",
    "CLEAR": "See-through, like glass",
    "CLERK": "Store counter worker",
    "CLICK": "Sound of the mouse",
    "CLIFF": "Edge you don't go over",
    "CLIMB": "Make your way up",
    "CLOAK": "___-and-dagger, like a spy",
    "CLOCK": "It's got hands but can't clap",
    "CLOSE": "Shut tight",
    "CLOTH": "What a tailor cuts",
    "CLOUD": "It might have a silver lining",
    "CLOWN": "Send in the ___s",
    "CLUMP": "A stuck-together wad",
    "COACH": "The one with the playbook",
    "COAST": "Where the surfers head",
    "COCOA": "Hot chocolate powder",
    "COLOR": "A crayon's job",
    "COMET": ["Tailed space rock","Halley's, famously"],
    "COMIC": "Stand-up performer",
    "COMMA": "Pause-marking punctuation",
    "CORAL": "Reef-building polyp colony",
    "CORGI": "Short-legged herding dog",
    "COUCH": "Where a potato might sit",
    "COUGH": "___ up, pay reluctantly",
    "COUNT": "What Dracula is, fittingly",
    "COURT": "Where the judge presides",
    "COVER": "Put a lid on it",
    "CRACK": "Hairline split",
    "CRAFT": "Etsy's specialty",
    "CRANE": "Long-necked construction lifter",
    "CRANK": "___ it up, raise the volume",
    "CRASH": "Fender-bender result",
    "CRATE": "Wooden shipping box",
    "CRAVE": "Desire intensely",
    "CRAWL": "Move at a snail's pace",
    "CRAZY": "Off the wall",
    "CREAM": "The ___ of the crop",
    "CREEK": "Up the ___ without a paddle",
    "CREEP": "Move stealthily",
    "CREST": "Colgate's toothpaste rival",
    "CRISP": "Fresh and crunchy",
    "CROAK": "Frog's sound",
    "CROOK": "Petty criminal",
    "CROSS": "Get to the other side",
    "CROWD": "A real sea of people",
    "CROWN": "It sits heavy, they say",
    "CRUEL": "Deliberately mean",
    "CRUMB": "Trail of them, like Hansel's",
    "CRUSH": "Smash flat",
    "CUBIC": "Measured in three dimensions",
    "CURLY": "Having ringlets",
    "CURRY": "___ favor, suck up",
    "CURVE": "Pitcher's breaking ball",
    "CYCLE": "Recurring sequence",
    "DAILY": "Happening every day",
    "DAIRY": "Milk-and-cheese aisle",
    "DAISY": "Petal-plucking flower",
    "DANCE": "Cut a rug",
    "DANDY": "Just fine, as in 'fine and ____'",
    "DEALT": "Distributed cards",
    "DEBUT": "First public appearance",
    "DECAY": "What the dentist fights",
    "DECOY": "Duck-shaped hunting lure",
    "DELAY": "Postpone",
    "DELTA": "Greek letter, or an airline",
    "DENIM": "Levi's material",
    "DEPOT": "Train station",
    "DEPTH": "How far down it goes",
    "DEVIL": "Satan",
    "DIARY": "Personal daily journal",
    "DIGIT": "A finger, or a 0 through 9",
    "DINER": "Roadside greasy-spoon eatery",
    "DINGO": "Australian wild dog",
    "DIRTY": "Covered in grime",
    "DISCO": "1970s dance music",
    "DITCH": "Last-___ effort, final try",
    "DIVER": "One who plunges underwater",
    "DODGE": "Truck make, or to evade",
    "DONOR": "One who gives blood",
    "DOUBT": "Uncertainty",
    "DOUGH": "Slang for money, or what you knead",
    "DOZEN": "Egg-carton count",
    "DRAFT": "First crack at the essay",
    "DRAIN": "___ed, completely exhausted",
    "DRAMA": "Serious play genre",
    "DREAM": "What you have while asleep",
    "DRESS": "Ball gown",
    "DRIFT": "Catch my ___?, get my meaning?",
    "DRINK": "Wet your whistle",
    "DRIVE": "Take the wheel",
    "DROVE": "Operated a car, past tense",
    "DRUNK": "Intoxicated",
    "DRYER": "Laundry appliance after the wash",
    "DUMMY": "Store mannequin",
    "DUSTY": "Like a long-untouched shelf",
    "DWARF": "Snow White's little companion",
    "DWELL": "___ on it, brood",
    "EAGER": "Champing at the bit",
    "EAGLE": "Two under par, to a golfer",
    "EARLY": "Beating the rush",
    "EARTH": "The third rock from the sun",
    "EATEN": "Consumed, past participle",
    "EERIE": "Spookily strange",
    "EIGHT": "Number after seven",
    "ELBOW": "___ grease, hard effort",
    "ELDER": "Respected community senior",
    "ELECT": "Vote into office",
    "ELITE": "The cream of the crop",
    "ELOPE": "Run off to marry",
    "EMAIL": "Electronic message",
    "EMPTY": "Running on ___, no gas left",
    "ENDUP": "Eventually arrive at",
    "ENEMY": "A foe",
    "ENJOY": "Have a ball",
    "ENTER": "Step inside",
    "ENVOY": "Diplomatic representative",
    "EPOCH": "Notable era in history",
    "EQUAL": "Even-steven",
    "ERASE": "Rub out pencil marks",
    "ERROR": "What an eraser fixes",
    "ESSAY": "Written school composition",
    "EVADE": "Skillfully avoid",
    "EVENT": "A big to-do",
    "EVERY": "Each and all",
    "EXACT": "Perfectly precise",
    "EXCEL": "Perform exceptionally",
    "EXERT": "Apply, as effort",
    "EXILE": "Napoleon's fate on Elba",
    "EXIST": "To be, to live",
    "EXTRA": "One to spare",
    "FABLE": "Aesop's specialty",
    "FAINT": "Pass out cold",
    "FAITH": "Belief without proof",
    "FALSE": "Not true",
    "FANCY": "Dressed to the nines",
    "FATAL": "Causing death",
    "FAULT": "Whose ___ is it",
    "FAVOR": "A kind, helpful act",
    "FEAST": "A spread fit for a king",
    "FENCE": "Where you sit when undecided",
    "FETCH": "Rover's stick game",
    "FEVER": "High body temperature",
    "FEWER": "Not as many",
    "FIBER": "What keeps you regular",
    "FIELD": "Where the ballgame is played",
    "FIGHT": "Throw down, fists up",
    "FINAL": "The very last one",
    "FINCH": "Atticus, in a Harper Lee novel",
    "FIRST": "Blue-ribbon position",
    "FLAKE": "Bit of falling snow",
    "FLAME": "A candle's flicker",
    "FLARE": "Emergency signal light",
    "FLASH": "Quick pop of light",
    "FLEET": "Group of ships",
    "FLESH": "Soft body tissue",
    "FLOAT": "Bob along on the water",
    "FLOCK": "Birds of a feather ___ together",
    "FLOOD": "Overflowing water disaster",
    "FLOOR": "What you sweep underfoot",
    "FLOUR": "What the baker sifts",
    "FLUID": "A liquid",
    "FLUSH": "Poker hand all one suit",
    "FLUTE": "Silver woodwind instrument",
    "FOCUS": "Zero in on it",
    "FORCE": "A Jedi's energy field",
    "FORGE": "Blacksmith's furnace",
    "FORTY": "___ winks, a catnap",
    "FOUND": "Located what was lost",
    "FRAME": "Border around a picture",
    "FRANK": "Honest and direct",
    "FRESH": "Just off the vine",
    "FRIED": "Cooked in hot oil",
    "FRONT": "Opposite of the rear",
    "FROST": "Lacework on a cold window",
    "FROWN": "It takes more muscles than a smile",
    "FROZE": "Turned to ice, past tense",
    "FRUIT": "An apple or a pear",
    "FUDGE": "Rich chocolate candy",
    "FUNNY": "Good for a laugh",
    "GAUGE": "Measuring dial",
    "GECKO": "Wall-climbing lizard",
    "GENIE": "Lamp-dwelling wish-granter",
    "GETUP": "Rise from bed",
    "GHOST": "The thing that says boo",
    "GIANT": "Towering big fellow",
    "GLASS": "Pane in the window",
    "GLOBE": "A mini model of Earth",
    "GLOOM": "Doom's frequent partner",
    "GLOVE": "Boxer's padded hand-cover",
    "GOTIT": "Understood!",
    "GRACE": "Said before digging in",
    "GRADE": "Letter on a report card",
    "GRAIN": "A single bit of rice",
    "GRAND": "A thousand bucks, slangily",
    "GRAPE": "What wine starts out as",
    "GRASS": "What you mow on Sunday",
    "GREAT": "A cut above the rest",
    "GREEN": "What 'go' means at a light",
    "GRIEF": "Good ___!, exasperated cry",
    "GRILL": "Where burgers sizzle outside",
    "GRIND": "The daily ___, routine toil",
    "GROAN": "Bad-pun reaction",
    "GROUP": "A bunch lumped together",
    "GUARD": "One who stands watch",
    "GUESS": "Take a shot in the dark",
    "GUEST": "One on the invite list",
    "HAPPY": "Grinning ear to ear",
    "HATCH": "Down the ___, bottoms up",
    "HAVEN": "Tax ___, offshore spot",
    "HEART": "What Cupid aims for",
    "HEAVY": "A real ton to lift",
    "HEDGE": "___ your bets, play it safe",
    "HONEY": "What the bees make",
    "HORSE": "It races at the track",
    "HOTEL": "Where you check in for the night",
    "HOUSE": "It's got a roof and four walls",
    "HOVER": "Hang in midair",
    "HUMAN": "Not a robot",
    "HUMID": "Sticky, like August air",
    "HUMOR": "What a comedian's loaded with",
    "IDEAL": "Just about perfect",
    "IGLOO": "Inuit ice dwelling",
    "IMAGE": "What a mirror throws back",
    "INDEX": "Pointing finger, or a book's back matter",
    "INLAW": "Relative by marriage",
    "INLET": "Small arm of the sea",
    "IVORY": "Soap brand, or tusk material",
    "JEWEL": "A sparkler in the crown",
    "JOINT": "Where two bones meet",
    "JUICE": "What you squeeze from an orange",
    "KNIFE": "What you spread butter with",
    "KOALA": "Eucalyptus muncher Down Under",
    "LABEL": "Tag with the price",
    "LARGE": "Super-sized",
    "LASER": "Pointed beam of light",
    "LATCH": "___ onto, cling to",
    "LAUGH": "What a good joke gets",
    "LAYER": "One tier of the cake",
    "LEARN": "Pick up a new skill",
    "LEDGE": "Where the pigeon perches",
    "LEMON": "What life hands you, in a saying",
    "LETGO": "Release one's grip",
    "LEVEL": "Flat and even, no tilt",
    "LIGHT": "What a lamp gives off",
    "LINEN": "Air one's dirty ___, spill secrets",
    "LIVER": "Organ that filters toxins",
    "LLAMA": "Andean cousin of the alpaca",
    "LODGE": "Cabin up at the ski hill",
    "LOGIN": "Sign-on credentials",
    "LOYAL": "True-blue and faithful",
    "LUCKY": "Born under a good star",
    "LUNCH": "The meal at midday",
    "MAGIC": "A wizard's stock in trade",
    "MAPLE": "Canada's flag leaf",
    "MARSH": "Boggy lowland",
    "MAYOR": "City hall's top dog",
    "MEDAL": "Gold, silver, or bronze",
    "MEDIA": "The fourth estate",
    "MELON": "Honeydew or cantaloupe",
    "MERCY": "A break given to the guilty",
    "MERIT": "Scout's badge earner",
    "METAL": "Iron, gold, or steel",
    "METER": "A bit more than a yard",
    "METOO": "Same here!",
    "MIGHT": "Sheer brute strength",
    "MONEY": "It talks, they say",
    "MONTH": "June, for one",
    "MOTEL": "Bates, in 'Psycho'",
    "MOTOR": "What hums under the hood",
    "MOUND": "Pitcher's perch",
    "MOUNT": "Climb up onto",
    "MOURN": "Grieve a loss",
    "MOUSE": "It clicks on your desk",
    "MOUTH": "Where the words come out",
    "MOVER": "___ and shaker, big wheel",
    "MOVIE": "A flick at the theater",
    "MUSIC": "What fills your earbuds",
    "NIECE": "Aunt's little girl",
    "NIGHT": "When the owls come out",
    "NIMBY": "Anti-development local, for short",
    "NOBLE": "Duke or earl, e.g.",
    "NOISE": "Unwanted racket",
    "NOONE": "Nobody",
    "NORTH": "Where a compass points",
    "NOTME": "I’m innocent!",
    "NOTSO": "Hardly the case",
    "NOVEL": "A long page-turner",
    "NOWAY": "Absolutely not!",
    "NUDGE": "A gentle elbow",
    "NURSE": "One in scrubs at the hospital",
    "OCEAN": "The deep blue sea",
    "OFFER": "Put it on the table",
    "OLIVE": "Martini garnish, or Popeye's gal",
    "ONAIR": "Currently broadcasting",
    "ONEND": "Standing upright",
    "ONION": "It brings tears to your eyes",
    "ONTOP": "In the lead",
    "OPTIN": "Choose to join",
    "ORDER": "What you give the waiter",
    "ORGAN": "Pipes in a church",
    "OTTER": "Playful river swimmer",
    "OWNER": "The one who holds the deed",
    "PAINT": "What rolls onto a wall",
    "PANIC": "Go into a frenzy",
    "PAPER": "A sheet from the printer",
    "PARTY": "Bash to celebrate",
    "PASTE": "Sticky stuff for crafts",
    "PATCH": "What covers a hole in jeans",
    "PAUSE": "Hit the button to freeze it",
    "PEACE": "What a dove symbolizes",
    "PEACH": "Fuzzy-skinned fruit",
    "PEARL": "What an oyster makes",
    "PEDAL": "Put the ___ to the metal",
    "PERCH": "Where a parrot sits",
    "PETAL": "Loves-me-not pluck",
    "PHONE": "It's always in your pocket",
    "PIANO": "88-key instrument",
    "PILOT": "A show's first episode",
    "PITCH": ["Throw to the batter","A salesperson's spiel"],
    "PIVOT": "Change course, in startup-speak",
    "PIZZA": "Pie with a cheesy top",
    "PLACE": "A particular spot",
    "PLAIN": "Nothing fancy",
    "PLANE": "It cruises at 30,000 feet",
    "PLANT": "It needs sun and water",
    "PLATE": "What dinner's served on",
    "PLUMP": "Pleasingly chubby",
    "POINT": "Sharp end of the pencil",
    "POLAR": "___ opposites, total contrasts",
    "PORCH": "Where the rocking chair sits",
    "POUND": "Sixteen ounces' worth",
    "POWER": "Juice that runs the grid",
    "PRESS": "Push down firmly",
    "PRICE": "What the tag tells you",
    "PRIDE": "A group of lions",
    "PRINT": "What detectives dust for",
    "PRIZE": "What the winner claims",
    "PRONG": "Fork's point",
    "PROUD": "Standing tall",
    "PROVE": "Back it up with facts",
    "PROWL": "On the ___, hunting",
    "PULSE": "Finger-on-the-___, in tune with trends",
    "PUNCH": "A jab from a boxer",
    "PUPIL": ["Student","It widens in the dark"],
    "PUREE": "Baby-food consistency",
    "QUACK": "A duck's call, or a sham doctor",
    "QUARK": "Subatomic building block",
    "QUEEN": "The king's royal partner",
    "QUICK": "Fast as a wink",
    "QUIET": "Library-level hush",
    "QUILT": "Patchwork bed cover",
    "QUITE": "More than a little",
    "RADAR": "Aircraft-detecting system",
    "RADIO": "It plays tunes on the drive",
    "RANCH": "Spread where cattle roam",
    "RANGE": "A chain of mountains",
    "RAPID": "Lightning-fast",
    "RAVEN": "Poe's 'nevermore' bird",
    "REACH": "Stretch out for it",
    "REBEL": "___ without a cause, James Dean",
    "REIGN": "Sit on the throne",
    "RELAX": "Let it all unwind",
    "REPLY": "Shoot back a response",
    "RHYME": "What 'cat' and 'hat' do",
    "RIDGE": "The crest of a hill",
    "RINSE": "Lather, ___, repeat",
    "RIVAL": "Head-to-head foe",
    "RIVER": "It flows down to the sea",
    "ROAST": "Slow-cook in the oven",
    "ROBIN": "Early bird of spring",
    "ROBOT": "A mechanical worker",
    "ROOST": "Rule the ___, be in charge",
    "ROUGH": "___ around the edges, unpolished",
    "ROUND": "Shaped like a ball",
    "ROUTE": "The way you go",
    "ROYAL": "Fit for a king",
    "SALAD": "Bowl of greens",
    "SAUCE": "What tops the spaghetti",
    "SCALE": "Step on it to weigh in",
    "SCALP": "Ticket reseller's verb",
    "SCARF": "Wrap for a cold neck",
    "SCENE": "One bit of the movie",
    "SCENT": "Bloodhound's trail clue",
    "SCOLD": "Give a tongue-lashing",
    "SCOOP": "Exclusive news, or an ice cream serving",
    "SCORE": "What you rack up in a game",
    "SCOUT": "One who earns merit badges",
    "SCRAP": "Junkyard metal, or to ditch a plan",
    "SCRUB": "A launch cancellation",
    "SCUBA": "Underwater breathing gear",
    "SENSE": "Sight, smell, or hearing",
    "SETUP": "Arrangement of equipment",
    "SHACK": "A run-down little hut",
    "SHADE": ["Spot out of the sun","Subtle dig, in slang"],
    "SHALE": "Rock that yields oil",
    "SHAPE": "A circle or a square, e.g.",
    "SHARE": "Split it with a friend",
    "SHARK": "Top predator of the deep",
    "SHARP": "Keen as a tack",
    "SHEEP": "Counted to fall asleep",
    "SHEET": "What you tuck around a mattress",
    "SHELF": "Off the ___, ready-made",
    "SHELL": "What you find on the beach",
    "SHINE": "Buff it to a gleam",
    "SHIRT": "What you button up top",
    "SHORE": "Where the waves break",
    "SHORT": "On the low end of the ruler",
    "SHOUT": "Yell at the top of your lungs",
    "SHRUB": "A low garden bush",
    "SIGHT": "One of the five senses",
    "SITUP": "Ab-strengthening exercise",
    "SKATE": "Glide across the ice rink",
    "SKULL": "What a helmet protects",
    "SLEEP": "Catch some shut-eye",
    "SLEET": "Wintry mix of rain and ice",
    "SLICE": "One wedge of pizza",
    "SLIDE": "Playground chute",
    "SLOPE": "Bunny ___, beginner's run",
    "SMALL": "On the tiny side",
    "SMART": "Sharp as a tack",
    "SMELL": "What the nose knows",
    "SMELT": "Liquefied the ore, or a small fish",
    "SMILE": "Say cheese for it",
    "SMOKE": "Where there's fire, there's this",
    "SNACK": "A bite between meals",
    "SNAIL": "___ mail, postal delivery",
    "SNAKE": "Slithering, legless reptile",
    "SNORE": "Sawing logs, so to speak",
    "SNOUT": "Pig's nose",
    "SOFAR": "Up to this point",
    "SOLAR": "Powered by the sun",
    "SOLID": "Not liquid or gas",
    "SOUND": "What the ears pick up",
    "SOUTH": "Down on the compass",
    "SPACE": "The final frontier",
    "SPADE": "Call a ___ a ___, be blunt",
    "SPARE": "An extra one on hand",
    "SPARK": "Tiny flash that starts a fire",
    "SPEAK": "Say a few words",
    "SPEED": "How fast you're going",
    "SPELL": "Put the letters in order",
    "SPEND": "Lay out some cash",
    "SPICE": "Cinnamon or nutmeg",
    "SPILL": "Knock the milk over",
    "SPINE": "The body's backbone",
    "SPLIT": "Cut it down the middle",
    "SPOON": "What you eat soup with",
    "SPORT": "Tennis or soccer, e.g.",
    "SPRAY": "Mist from a can",
    "SQUID": "Calamari source",
    "STAFF": "The folks on the payroll",
    "STAGE": "Where the actors perform",
    "STAIR": "One step on the way up",
    "STALK": "Celery's string, or to follow creepily",
    "STAMP": "It mails the letter",
    "STAND": "Rise to your feet",
    "STARE": "Give a long, hard look",
    "START": "Get things going",
    "STASH": "A hidden cache",
    "STATE": "Texas or Ohio, e.g.",
    "STEAM": "What rises off a hot kettle",
    "STEEL": "Tough metal in a skyscraper",
    "STEEP": "Let the tea ___, or a sharp grade",
    "STERN": "No-nonsense and strict",
    "STICK": "A twig snapped off a tree",
    "STILT": "Circus walker's leg-extender",
    "STING": "What an angry bee does",
    "STOCK": "What's on the store's shelves",
    "STONE": "A solid hunk of rock",
    "STOOL": "Bar seat with no back",
    "STORE": "Where you go shopping",
    "STORM": ["Bad weather","Burst in angrily"],
    "STORY": "A tale to tell",
    "STOVE": "Where the pots get hot",
    "STRAW": "Scarecrow's stuffing",
    "STRIP": "Sunset ___, an L.A. boulevard",
    "STUDY": "Hit the books hard",
    "STUMP": "Leave one ___ed, baffle",
    "STYLE": "One's sense of fashion",
    "SUGAR": "What sweetens your coffee",
    "SUNNY": "Not a cloud in the sky",
    "SUPER": "Better than great",
    "SWEAT": "No ___, no problem",
    "SWEEP": "Win every game in a series",
    "SWEET": "Like sugar",
    "SWING": "Seat on the playground",
    "SWIRL": "A spiral pattern",
    "SWORD": "Cross ___s, do battle",
    "TABLE": "Where the family eats",
    "TASTE": "What the tongue does",
    "TEACH": "Show someone the ropes",
    "THANK": "Say a grateful word",
    "THICK": "On the heavy side",
    "THINK": "Use the old noggin",
    "THORN": "A ___ in one's side, a nuisance",
    "THREE": "A trio's count",
    "THROW": "Hurl it across the room",
    "THUMB": "Green ___, gardening knack",
    "TIGER": "Big cat with stripes",
    "TIGHT": "Snug as can be",
    "TIMER": "Kitchen countdown gadget",
    "TITLE": "The name of the book",
    "TOAST": "What pops up at breakfast",
    "TODAY": "Not yesterday or tomorrow",
    "TONIC": "Gin's bubbly partner",
    "TOOTH": "The dentist checks it",
    "TOPIC": "The subject at hand",
    "TORCH": "Flame you carry by hand",
    "TOUCH": "Feel with a fingertip",
    "TOWEL": "What you dry off with",
    "TOWER": "It leans, over in Pisa",
    "TRACE": "Without a ___, vanished completely",
    "TRACK": "The runner's oval",
    "TRADE": "Swap one for another",
    "TRAIL": "Path through the woods",
    "TRAIN": "It runs on the rails",
    "TRAIT": "Inherited characteristic",
    "TREAT": "A little something special",
    "TREND": "The latest fad",
    "TRIBE": "A close-knit group",
    "TRICK": "A sneaky maneuver",
    "TROUT": "Fish in a mountain stream",
    "TRUCK": "Eighteen-wheeler, e.g.",
    "TRUNK": ["Elephant's nose","Road-trip packing spot"],
    "TRUST": "Put your faith in",
    "TRUTH": "The honest-to-goodness fact",
    "TULIP": "Holland's iconic bloom",
    "TUTOR": "A one-on-one teacher",
    "TWIST": "Plot ___, story surprise",
    "UNCLE": "What you cry when you give up",
    "UNDER": "Down below",
    "UNITE": "Band together as one",
    "UPPER": "The higher of the two",
    "USHER": "Theater guide, or an R&B star",
    "VALUE": "What something's worth",
    "VAPOR": "Steam, essentially",
    "VIDEO": "A clip you hit play on",
    "VIGOR": "Vim and ___, energy",
    "VINYL": "Records revived by hipsters",
    "VOICE": "What you sing with",
    "VOWEL": "Buy one on 'Wheel of Fortune'",
    "WAGER": "Put money on it",
    "WAGON": "Little red pull-along",
    "WALTZ": "Three-four time dance",
    "WATCH": "Clock on your wrist",
    "WATER": "What fills the ocean",
    "WEARY": "Bone-tired",
    "WEAVE": "Bob and ___, dodge",
    "WEDGE": "Doorstop shape, or a golf club",
    "WHALE": "The biggest beast of the sea",
    "WHARF": "Where the boats tie up",
    "WHEAT": "Grain ground into flour",
    "WHEEL": "What rolls under the car",
    "WHISK": "It beats the eggs",
    "WHITE": "The color of fresh snow",
    "WHOLE": "Every last bit",
    "WIDOW": "Black ___, deadly spider",
    "WINCE": "Flinch at the pain",
    "WOMAN": "A grown female",
    "WORLD": "The planet and all on it",
    "WORTH": "How much it's valued at",
    "WOUND": "A cut that needs a bandage",
    "WOVEN": "Made on a loom",
    "WRIST": "Joint that wears the watch",
    "WRITE": "Put pen to paper",
    "YACHT": "A rich person's pleasure boat",
    "YEAST": "What makes the dough rise",
    "YIELD": "Triangular road sign",
    "YOUNG": "Still in your prime",
    "YOUTH": "A young person",
    "ZEBRA": "Striped cousin of the horse",
  },
  6: {
    "ACCEPT": "Say yes to",
    "ACCESS": "Way in",
    "ACROSS": "From one side to the other",
    "ACTION": "Lights, camera, ___!",
    "ACTIVE": "Full of energy",
    "ACTUAL": "Real, not imagined",
    "ADJUST": "Fine-tune",
    "ADMIRE": "Look up to",
    "ADVICE": "What a wise friend gives",
    "ADVISE": "Give counsel to",
    "AFFAIR": "Romantic fling",
    "AFFORD": "Have enough money for",
    "AFRAID": "Scared stiff",
    "AGENCY": "The FBI or CIA, e.g.",
    "ALMOST": "Not quite there",
    "ALWAYS": "Forever and ever",
    "AMOUNT": "Sum or quantity",
    "ANCHOR": "Ship's heavy hook",
    "ANIMAL": "A creature at the zoo",
    "ANNUAL": "Once a year",
    "ANSWER": "What you give to a question",
    "APPEAL": "Plea to a higher court",
    "APPEAR": "Show up",
    "AROUND": "Surrounding",
    "ARRIVE": "Reach a destination",
    "ARTIST": "One handy with a brush",
    "ASLEEP": "Catching z's",
    "ASPECT": "A facet or feature",
    "ASSIGN": "Hand out, as homework",
    "ASSIST": "Lend a hand",
    "ASSUME": "Take for granted",
    "ATTACK": "Go on the offensive",
    "ATTEND": "Show up for",
    "AUTHOR": "The one with the byline",
    "AUTUMN": "When the leaves turn and fall",
    "AVENUE": "Wide city street",
    "BACKUP": "Spare copy of files",
    "BAKERY": "Where bread is sold",
    "BALLET": "Dance on pointe",
    "BANANA": "Peel-and-eat yellow fruit",
    "BANNER": "Hanging sign or flag",
    "BARELY": "Just hardly",
    "BASKET": "What you sink a hoops shot in",
    "BATTLE": "Uphill ___",
    "BEACON": "Guiding light",
    "BEAUTY": "Stunning good looks",
    "BEAVER": "Dam-building rodent",
    "BECOME": "Turn into",
    "BEFORE": "Ahead of",
    "BEHIND": "Bringing up the rear",
    "BELONG": "Have a rightful place",
    "BESIDE": "Next to",
    "BETTER": "On the mend",
    "BISHOP": "Diagonal chess piece",
    "BORDER": "The line between countries",
    "BOTTLE": "It holds a message at sea",
    "BOTTOM": "Rock ___",
    "BOUNCE": "Spring back up",
    "BRANCH": "A limb off the tree trunk",
    "BREACH": "A gap or break",
    "BREATH": "A lungful of fresh air",
    "BREEZE": "A total cinch",
    "BRIDGE": "It gets you over the river",
    "BRIGHT": "Shining with light",
    "BROKEN": "Snapped into pieces",
    "BRONZE": "The third-place metal",
    "BRUNCH": "Late-morning meal",
    "BUBBLE": "A floating soap sphere",
    "BUCKET": "What you kick, in a saying",
    "BUDGET": "Money plan to stick to",
    "BUNDLE": "Cost a small fortune, with 'a'",
    "BUREAU": "Chest of drawers",
    "BURGER": "Patty in a bun",
    "BUTTER": "What you spread on toast",
    "BUTTON": "It fastens your shirt",
    "CACTUS": "Prickly desert plant",
    "CAMERA": "What snaps the photo",
    "CANCEL": "Call off",
    "CANDLE": "Wax stick that you light",
    "CANYON": "A deep, grand gorge",
    "CAREER": "Lifelong profession",
    "CARPET": "The red one's rolled out for stars",
    "CARROT": "Bugs Bunny's snack",
    "CARTON": "Box for eggs or milk",
    "CASTLE": "A king's stone fortress",
    "CASUAL": "Dressed down",
    "CAUGHT": "Snagged or grabbed",
    "CAVERN": "Large underground hollow",
    "CELERY": "Crunchy green stalk",
    "CELLAR": "Where the wine ages",
    "CEMENT": "Sidewalk material",
    "CENTER": "The exact middle",
    "CEREAL": "Breakfast in a bowl",
    "CHANCE": "A roll-of-the-dice shot",
    "CHANGE": "Coins jingling in your pocket",
    "CHAPEL": "Small place of worship",
    "CHARGE": ["Rush forward","What's on your credit card"],
    "CHEEKY": "Saucy and bold",
    "CHEESE": "Say it for the camera",
    "CHERRY": "What tops off the sundae",
    "CHOICE": "An option",
    "CHORUS": "Song's repeated part",
    "CHROME": "Shiny metal trim",
    "CHUNKY": "Thick and lumpy",
    "CHURCH": "Sunday worship place",
    "CINEMA": "The movies",
    "CIRCLE": "Round as a wheel",
    "CIRCUS": "The three-ring show",
    "CLEVER": "Quick-witted and sharp",
    "CLINIC": "Walk-in medical office",
    "CLOSET": "Where the clothes hang",
    "CLOUDY": "Overcast",
    "CLOVER": "Lucky four-leaf plant",
    "CLUTCH": "Grab tightly",
    "COBWEB": "Spider's dusty leftover",
    "COFFEE": "The morning's wake-up brew",
    "COLLAR": "Hot under the ___",
    "COLONY": "Settlement abroad",
    "COLUMN": "Tall supporting pillar",
    "COMBAT": "Armed fighting",
    "COMEDY": "Sitcom genre",
    "COMEON": "Plea of 'be serious!'",
    "COMING": "On its way",
    "COMMIT": "Pledge yourself",
    "COMMON": "Garden-variety",
    "COOKIE": "Sweet disc from the jar",
    "COPPER": "A penny's metal",
    "CORNER": "Where two walls meet",
    "COSMIC": "Relating to the universe",
    "COSTLY": "Expensive",
    "COTTON": "Soft fiber in a T-shirt",
    "COUPLE": "An item, romantically",
    "COUSIN": "Your aunt and uncle's kid",
    "COWBOY": "Rodeo rider",
    "CRADLE": "Rock-a-bye spot",
    "CRANKY": "Grumpy",
    "CRAYON": "Crayola stick",
    "CREAMY": "Smooth and rich",
    "CREATE": "Bring into being",
    "CREDIT": "Buy-now-pay-later plan",
    "CRISPY": "Crunchy when bitten",
    "CRUISE": "Vacation by ship",
    "CRUNCH": "Sound of a chip bite",
    "CUDDLE": "Snuggle up",
    "CURFEW": "Be-home-by time",
    "CUSTOM": "A tradition",
    "DAMAGE": "What's the ___? (the total cost?)",
    "DANGER": "Will Robinson's warning",
    "DAZZLE": "Amaze and impress",
    "DEALER": "Card distributor",
    "DEBATE": "Podium face-off",
    "DECADE": "A ten-year span",
    "DECENT": "Pretty good",
    "DECIDE": "Make up your mind",
    "DEFEAT": "Hand a loss to",
    "DEFEND": "Protect from attack",
    "DEFINE": "Give the meaning of",
    "DEGREE": "What a diploma confers",
    "DELUXE": "Fancy and high-end",
    "DENTAL": "Tooth-related",
    "DEPART": "Leave",
    "DEPEND": "Rely (on)",
    "DEPUTY": "Sheriff's right-hand",
    "DESERT": "A vast sea of sand",
    "DESIGN": "Blueprint work",
    "DETAIL": "Where the devil is, they say",
    "DETECT": "Notice or sense",
    "DEVICE": "Phone or tablet, e.g.",
    "DEVOTE": "Dedicate, as time",
    "DIESEL": "Truck fuel type",
    "DIGEST": "Break down food",
    "DIMPLE": "Cheek dent when smiling",
    "DINNER": "The evening's main meal",
    "DIVIDE": "Split into parts",
    "DIVINE": "Godlike or heavenly",
    "DOCTOR": "The one who'll see you now",
    "DOLLAR": "A buck in your wallet",
    "DOMAIN": "Area of expertise",
    "DONATE": "Give to charity",
    "DONKEY": "Stubborn long-eared beast",
    "DOODLE": "Absent-minded sketch",
    "DOOVER": "Second chance",
    "DOUBLE": "A stunt stand-in",
    "DRAGON": "Fire-breathing scaly beast",
    "DREAMS": "Visions while you sleep",
    "DROWSY": "Sleepy",
    "EARNED": "Worked for and got",
    "EARTHY": "Down to earth",
    "EASIER": "Less difficult",
    "EASILY": "Without breaking a sweat",
    "EATING": "Having a meal",
    "EDIBLE": "Safe to eat",
    "EDITOR": "Red-pen wielder",
    "EFFECT": "A result",
    "EFFORT": "Old college ___",
    "EITHER": "One or the other",
    "ELEVEN": "Number after ten",
    "EMBARK": "Board a ship",
    "EMBERS": "Glowing fire remains",
    "EMERGE": "Come into view",
    "EMPIRE": "What strikes back, in film",
    "EMPLOY": "Give a job to",
    "ENABLE": "Make possible",
    "ENERGY": "Get-up-and-go",
    "ENGINE": "What's under the hood",
    "ENROLL": "Sign up for class",
    "ENSURE": "Make certain",
    "ENTIRE": "Whole",
    "EQUALS": "Is the same as",
    "ERRAND": "A quick task to run",
    "ESCAPE": "Make a clean getaway",
    "ESCORT": "Accompany for safety",
    "ESTATE": "A sprawling property",
    "EXCEED": "Go beyond a limit",
    "EXCUSE": "A lame justification",
    "EXHALE": "Breathe out",
    "EXOTIC": "Strange and foreign",
    "EXPAND": "Grow larger",
    "EXPECT": "Anticipate",
    "EXPERT": "Old hand",
    "EXPOSE": "Uncover or reveal",
    "EXTEND": "Stretch out",
    "FABRIC": "Cloth material",
    "FACING": "Looking toward",
    "FAIRLY": "Justly",
    "FALCON": "The Maltese bird, in film",
    "FALLEN": "Dropped down",
    "FAMILY": "Your kith and kin",
    "FAMOUS": "A household name",
    "FASTEN": "Buckle up or attach",
    "FATHER": "The male parent",
    "FATHOM": "Understand fully",
    "FAUCET": "Kitchen sink tap",
    "FELINE": "Cat-like",
    "FELLOW": "A regular guy",
    "FIESTA": "Festive celebration",
    "FIGURE": "Go ___! (who'd have guessed!)",
    "FILTER": "Coffee maker insert",
    "FINALE": "The grand ending",
    "FINGER": "One of ten on your hands",
    "FLAVOR": "Taste sensation",
    "FLEECE": "Sheep's wool coat",
    "FLOPPY": "Limp and droopy",
    "FLOWER": "A rose or a tulip",
    "FLUFFY": "Soft and airy",
    "FLYING": "Soaring through the air",
    "FOLDER": "Manila file holder",
    "FOLLOW": "Go after",
    "FOREST": "Can't see it for the trees",
    "FORGET": "Slip one's mind",
    "FORMAL": "Black-tie",
    "FORMAT": "Layout or arrangement",
    "FOURTH": "After third",
    "FRIDGE": "Where the milk lives",
    "FRIEND": "A buddy through thick and thin",
    "FROSTY": "Icy and cold",
    "FROZEN": "Iced over solid",
    "FUMBLE": "Drop clumsily",
    "GADGET": "A handy gizmo",
    "GALAXY": "The Milky Way, for one",
    "GAMBLE": "Roll the dice",
    "GARAGE": "Where the car spends the night",
    "GARDEN": "Plot where the veggies grow",
    "GARLIC": "Vampire repellent",
    "GENIUS": "Brilliant mind",
    "GENTLE": "Soft, mild, and tender",
    "GINGER": "Snap cookie spice",
    "GLOOMY": "Dark and depressing",
    "GOBLIN": "Spooky little imp",
    "GOLDEN": "Made of the precious metal",
    "GOSSIP": "Tea, slangily",
    "GRAVEL": "Driveway crunch",
    "GROCER": "Food shop owner",
    "GROOVE": "In the ___ (in the zone)",
    "GROUND": "The dirt under your feet",
    "GROWTH": "A teenager's spurt",
    "GUITAR": "Six-string strummer",
    "HAMMER": "It drives the nail home",
    "HANDLE": "What you grip on a door",
    "HAPPEN": "Come to pass",
    "HARBOR": "Where the ships dock",
    "HAZARD": "Occupational ___",
    "HEALTH": "The state of being well",
    "HEATER": "Radiator, e.g.",
    "HEAVEN": "Paradise up above",
    "HELMET": "What a biker buckles on",
    "HOCKEY": "The puck sport",
    "HOLDON": "Wait a moment",
    "HOLLOW": "Empty inside",
    "HONEST": "Telling the whole truth",
    "HUMBLE": "Eat ___ pie",
    "HUNGRY": "Ready for seconds",
    "IMPACT": "Collision force",
    "INFANT": "Newborn",
    "INSECT": "Six-legged critter",
    "INVENT": "Dream up",
    "INVITE": "What an RSVP answers",
    "ISLAND": "A speck of land in the sea",
    "JACKET": "A light coat for cool days",
    "JAGUAR": "Spotted big cat",
    "JUNGLE": "Dense tropical forest",
    "JUNIOR": "The III, versus the II",
    "KETTLE": "It whistles when it boils",
    "KIDNEY": "Bean-shaped organ",
    "KITTEN": "A baby cat",
    "KNIGHT": "Round Table member",
    "LADDER": "Rungs you climb up",
    "LAPTOP": "Portable computer",
    "LAUNCH": "Blast off",
    "LAWYER": "One who's passed the bar",
    "LAYOUT": "Page design arrangement",
    "LEGEND": "A map's key, or a hero",
    "LENGTH": "Go to great ___s",
    "LESSON": "A teachable moment",
    "LETSGO": "Time to move!",
    "LETTER": "Mail you drop in the box",
    "LINEUP": "Roster of players",
    "LISTEN": "Lend an ear",
    "LITTLE": "On the small side",
    "LIZARD": "Gecko, e.g.",
    "LOGOUT": "Sign off a session",
    "LOUNGE": "Airport waiting spot",
    "LOVELY": "Easy on the eyes",
    "LUXURY": "A real indulgence",
    "MAGNET": "Fridge-note holder",
    "MAKEUP": "Cosmetics on a face",
    "MAMMAL": "A whale or a human, e.g.",
    "MANAGE": "Get by",
    "MARBLE": "Glass shooter in a kid's game",
    "MARGIN": "A page's edge",
    "MARKET": "Where the produce is sold",
    "MASCOT": "Team's costumed cheerleader",
    "MASTER": "A true expert at it",
    "MATTER": "Gray ___ (brains)",
    "MEADOW": "Wildflower field",
    "MEMORY": "Trip down ___ lane",
    "METHOD": "There's a ___ to the madness",
    "MIDDLE": "Right in the center",
    "MINUTE": "Sixty ticks of the clock",
    "MIRROR": "It shows you yourself",
    "MODERN": "Up to the minute",
    "MOMENT": "Senior ___, a brief lapse",
    "MONKEY": "Banana-loving climber",
    "MOTHER": "The female parent",
    "MUFFIN": "Breakfast's little cake",
    "MUSCLE": "Flex it at the gym",
    "MUSEUM": "Where the art hangs",
    "NATURE": "Mother ___",
    "NEEDLE": "Hard to find in a haystack",
    "NICKEL": "Five-cent piece",
    "NIGHTS": "Dark hours after dusk",
    "NOTICE": "Two weeks' ___",
    "NOTYET": "'Be patient, hold on'",
    "OFFICE": "The corner ___, a perk",
    "OPTOUT": "Decline to participate",
    "ORANGE": "Both a fruit and a color",
    "ORCHID": "Exotic bloom",
    "OUTPUT": "What a factory churns out",
    "OXYGEN": "What we breathe",
    "PALACE": "Where royalty resides",
    "PARADE": "Rain on one's ___",
    "PARCEL": "Porch package",
    "PARENT": "Your mom or your dad",
    "PARROT": "Bird that repeats you",
    "PASTRY": "A Danish, e.g.",
    "PAYOUT": "Winnings disbursed",
    "PEANUT": "Shell snack at the ballpark",
    "PEBBLE": "A little smooth stone",
    "PENCIL": "What you sharpen to write",
    "PEOPLE": "Folks, all of us",
    "PEPPER": "Salt's shaker partner",
    "PICKLE": "In a ___ (in a jam)",
    "PICKUP": "Light hauling truck",
    "PIGEON": "City park bird",
    "PILLOW": "Where you rest your head",
    "PIRATE": "Walk-the-plank type",
    "PISTOL": "Six-shooter",
    "PLANET": "Earth, Mars, or Venus",
    "PLENTY": "More than enough to spare",
    "POCKET": "Where you stash your keys",
    "POLICE": "The boys in blue",
    "POSTER": "Wall art held up with tape",
    "POTATO": "Spud you mash",
    "POWDER": "Take a ___ (leave abruptly)",
    "PRETTY": "Easy on the eyes",
    "PRINCE": "The 'Purple Rain' singer",
    "PRISON": "The big house",
    "PUBLIC": "The average Joe, with 'the'",
    "PUPPET": "Hand-or-string toy",
    "PURPLE": "The color of a grape",
    "PUZZLE": "A brain-teasing challenge",
    "QUARTZ": "Watch crystal",
    "RABBIT": "Pulled from a magician's hat",
    "RACKET": "A loud din",
    "RANDOM": "Out of the blue",
    "REASON": "The why behind it",
    "RECIPE": "Cooking instructions",
    "RECORD": "Vinyl spinner",
    "REDUCE": "Cut back",
    "REGION": "Neck of the woods",
    "REMOTE": "What you lose in the couch",
    "REPAIR": "Fix up",
    "REPORT": "A book ___, school assignment",
    "RESCUE": "Swoop in to save",
    "RESORT": "Last ___",
    "RESULT": "Bottom line",
    "RETURN": "Point of no ___",
    "REVEAL": "The big ___, a surprise",
    "REWARD": "Risk versus ___",
    "RHYTHM": "I got ___, per Gershwin",
    "RIBBON": "It's cut at a grand opening",
    "RIPPLE": "Pebble-in-pond effect",
    "RIVERS": "Flowing waterways",
    "ROBBER": "Bank holdup artist",
    "ROCKET": "It blasts off into space",
    "ROTATE": "Spin on an axis",
    "RUBBER": "Where it meets the road",
    "RUMBLE": "A hungry stomach's sound",
    "SADDLE": "Where the cowboy sits",
    "SAFELY": "Without any harm done",
    "SALMON": "Pink fish that swims upstream",
    "SAMPLE": "Free taste at the store",
    "SANDAL": "Open-toed summer shoe",
    "SAUCER": "Little plate under the cup",
    "SAVAGE": "Ruthless",
    "SCHEME": "Crafty plan",
    "SCHOOL": "Where the kids go to learn",
    "SCREEN": "The silver ___, the movies",
    "SCRIPT": "An actor's lines",
    "SEASON": "Winter, spring, summer, or fall",
    "SECOND": "A blink of the clock",
    "SECRET": "Something kept hush-hush",
    "SELECT": "Cream of the crop",
    "SENATE": "Capitol Hill chamber",
    "SHADOW": "Your dark outline on the ground",
    "SHIELD": "A knight's defense",
    "SHOVEL": "Snow clearer",
    "SHRIMP": "Cocktail crustacean",
    "SHUTUP": "Demand for silence",
    "SIGNAL": "A green light, e.g.",
    "SILENT": "Quiet as the grave",
    "SILVER": "The metal of second place",
    "SIMPLE": "Plain and easy",
    "SINGER": "One who carries the tune",
    "SISTER": "Your female sibling",
    "SKETCH": "Quick drawing",
    "SLEEVE": "Where an ace is hidden",
    "SMOOTH": "Without a single bump",
    "SOCCER": "World Cup sport",
    "SOCKET": "Where the plug goes",
    "SONNET": "A 14-line poem",
    "SPEECH": "Podium address",
    "SPHERE": "A ball's shape",
    "SPIDER": "Eight-legged web-spinner",
    "SPIRIT": "Team ___, pep",
    "SPLASH": "Make a ___ (a big impression)",
    "SPONGE": "SquarePants, for one",
    "SPRING": ["Bouncy season","Suddenly leap up from a crouch"],
    "SPROUT": "A bean's first shoot",
    "SQUARE": "Shape with four equal sides",
    "SQUASH": "Gourd, or to crush",
    "STABLE": "Where the horses bunk",
    "STAPLE": "A bread-and-butter item",
    "STATUE": "The ___ of Liberty",
    "STEREO": "Hi-fi system",
    "STITCH": "A ___ in time saves nine",
    "STREAM": "Babbling brook",
    "STREET": "Where you live, address-wise",
    "STRESS": "Pressure's toll",
    "STRONG": "Tough as an ox",
    "STUDIO": "Recording space",
    "SUBWAY": "Underground train",
    "SUMMER": "The season for the beach",
    "SUNDAY": "The day of rest",
    "SUNSET": "The sky's evening show",
    "SUPPER": "The Last ___, da Vinci's",
    "SWITCH": "Bait and ___",
    "SYMBOL": "A logo, e.g.",
    "TACKLE": "Bring down, in football",
    "TALENT": "A show of skill",
    "TANGLE": "Knotted mess",
    "TARGET": "Where the bullseye lives",
    "TATTOO": "Inked art",
    "TAVERN": "Old-time pub",
    "TEMPLE": "A house of worship",
    "TENNIS": "Court sport with a net",
    "THEORY": "Scientist's educated guess",
    "THIRTY": "Three times ten",
    "THREAD": "What you put through a needle",
    "THRIVE": "Flourish",
    "THROAT": "A frog in one's ___",
    "THRONE": "Where the king sits",
    "TICKET": "Your pass into the show",
    "TIMBER": "A logger's warning shout",
    "TISSUE": "Reached for with a sneeze",
    "TOMATO": "Fruit or veggie, debatably",
    "TONGUE": "What does the tasting",
    "TRAVEL": "See the world",
    "TRENCH": "A deep ditch",
    "TRICKY": "Not so simple",
    "TRIPLE": "Three-bagger, in baseball",
    "TROPHY": "Hardware for the champ",
    "TUMBLE": "Take a ___ (a fall)",
    "TUNNEL": "Light at the end of the ___",
    "TURKEY": "Thanksgiving bird",
    "TURNIP": "Root veggie",
    "TURTLE": "Slow reptile in a shell",
    "TUXEDO": "A penguin's look",
    "TWELVE": "A dozen",
    "TWENTY": "A score",
    "UNFAIR": "Not playing by the rules",
    "UNIQUE": "One of a kind",
    "UNLOCK": "Open with a key",
    "UPDATE": "Bring current",
    "UPLOAD": "Send to the cloud",
    "USEFUL": "Handy to have around",
    "VACUUM": "What nature abhors",
    "VALLEY": "Low land between two hills",
    "VANISH": "Disappear into thin air",
    "VELVET": "Soft, plush fabric",
    "VENDOR": "Street cart seller",
    "VESSEL": "A ship, or a blood tube",
    "VICTIM": "The wronged party",
    "VIOLET": "Shrinking ___, a shy one",
    "VIOLIN": "Fiddle, formally",
    "VIRTUE": "Patience is one",
    "VISION": "20/20, ideally",
    "VOLUME": "Turn down the ___",
    "VOYAGE": "Bon ___!",
    "WAFFLE": "Go back and forth",
    "WAKEUP": "Morning alarm's job",
    "WALLET": "Where your cash and cards go",
    "WALNUT": "Brain-shaped nut in a shell",
    "WALRUS": "Tusked sea mammal",
    "WANDER": "Roam aimlessly",
    "WARMTH": "Cozy heat",
    "WARMUP": "Pre-game stretching",
    "WEAPON": "A secret ___",
    "WEASEL": "___ out (wriggle free)",
    "WEIGHT": "Pull one's ___",
    "WHATIF": "A hypothetical's opener",
    "WHYNOT": "'Sure, let's do it'",
    "WIGGLE": "Squirm",
    "WILLOW": "Weeping tree",
    "WINDOW": "You look out through it",
    "WINNER": "The one who takes first",
    "WINTER": "The coldest season",
    "WISDOM": "Hard-won knowledge",
    "WIZARD": "A pointy-hatted spell-caster",
    "WONDER": "A jaw-dropping marvel",
    "WORKER": "A bee or an ant, e.g.",
    "WORTHY": "Deserving",
    "WRENCH": "Throw a ___ in the works",
    "WRITER": "Wordsmith",
    "YELLOW": "The color of a school bus",
    "YOGURT": "Greek ___, a tart snack",
    "ZIGZAG": "Lightning's path",
    "ZIPPER": "Jacket fastener",
    "ZOMBIE": "The walking dead",
  },
  7: {
    "ACADEMY": "School, often a military one",
    "ACROBAT": "Tumbling circus performer",
    "ACTIONS": "They speak louder than words",
    "AIRPORT": "Where the flights take off",
    "ANCIENT": "Old as the hills",
    "ANIMALS": "The zoo's residents",
    "ANOTHER": "Just one more",
    "ANTENNA": "Rooftop TV signal catcher",
    "AVOCADO": "Main ingredient in guacamole",
    "BALANCE": "Steadiness on a beam",
    "BALLOON": "It floats up at a party",
    "BANDAGE": "Wrap for a wound",
    "BEDROOM": "Where you sleep",
    "BEDTIME": "When the kids go to sleep",
    "BICYCLE": "Two wheels and a set of pedals",
    "BISCUIT": "Buttery bread with gravy",
    "BLANKET": "What you pull up when cold",
    "BLISTER": "Fluid bubble on burned skin",
    "BLOSSOM": "What the cherry tree does in spring",
    "BROTHER": "Your male sibling",
    "BURNOUT": "Exhaustion from overwork",
    "CABBAGE": "Leafy head in the coleslaw",
    "CABINET": "Storage unit in a kitchen",
    "CALCIUM": "Bone-building mineral",
    "CANDLES": "Wax sticks you blow out on a cake",
    "CAPTAIN": "The one steering the ship",
    "CAPTURE": "Take prisoner",
    "CARAMEL": "Chewy candy of melted sugar",
    "CEILING": "What you stare at in bed",
    "CHAMBER": "Compartment of the heart",
    "CHARITY": "Giving to those in need",
    "CHECKUP": "Routine doctor visit",
    "CHEDDAR": "Sharp orange cheese",
    "CHEETAH": "The fastest cat on land",
    "CHICKEN": "It crossed the road, famously",
    "CLARITY": "Clearness of thought",
    "CLIMATE": "A region's long-term weather",
    "COMPANY": "Misery loves it, they say",
    "COMPASS": "Tool with a north-pointing needle",
    "COMPUTE": "Crunch the numbers",
    "CONCERT": "A live show by the band",
    "COSTUME": "Outfit worn on Halloween",
    "COTTAGE": "Small house in the country",
    "COUNTRY": "A nation on the map",
    "COURAGE": "What the Cowardly Lion sought",
    "CRACKER": "Cheese's crunchy partner",
    "CRAYONS": "What fills the coloring box",
    "CRYSTAL": "Clear-as-glass gem",
    "CULTURE": "A people's way of life",
    "CUPCAKE": "Frosted single-serving cake",
    "CURTAIN": "It falls at the play's end",
    "CUSTARD": "Creamy egg-based dessert",
    "DECLINE": "Politely turn down",
    "DELIGHT": "Great pleasure",
    "DENTIST": "The one who checks your teeth",
    "DESKTOP": "Computer's home screen",
    "DESSERT": "The sweet end to a meal",
    "DIAMOND": "A girl's best friend, they say",
    "DIVIDED": "Split into parts",
    "DOLPHIN": "Brainy, friendly sea mammal",
    "DOORWAY": "Opening you walk through",
    "DRAGONS": "Fire-breathing mythical beasts",
    "DRAWING": "A sketch done in pencil",
    "DROPOUT": "One who quit school",
    "DRUMMER": "The band's beat keeper",
    "EARDRUM": "Membrane that vibrates with sound",
    "EARRING": "Jewelry for the lobe",
    "ECLIPSE": "When the moon hides the sun",
    "ELEVATE": "Raise up higher",
    "EMPRESS": "Female ruler of an empire",
    "EVENING": "The hours after dusk",
    "EXPLORE": "Venture into the unknown",
    "EYEBROW": "Arch of hair above the eye",
    "FACTORY": "Where the goods get made",
    "FALLOUT": "Nuclear blast debris",
    "FANTASY": "Make-believe daydream",
    "FEATHER": "What tickles, off a bird",
    "FERMENT": "Turn sugar into alcohol",
    "FIREFLY": "Bug that glows on summer nights",
    "FORTUNE": "A vast pile of wealth",
    "FREEDOM": "Liberty and independence",
    "FREEZER": "Where you keep the ice cream",
    "GARDENS": "Plots where flowers grow",
    "GENERAL": "The army's top brass",
    "GIRAFFE": "Tallest animal at the zoo",
    "GLACIER": "Slow-moving river of ice",
    "GLITTER": "Sparkly craft sprinkles",
    "GRAVITY": "Force that pulls things down",
    "GROCERY": "Food bought at the market",
    "HABITAT": "An animal's natural home",
    "HALLWAY": "Corridor between rooms",
    "HAMSTER": "Pet rodent on a wheel",
    "HANGOUT": "Casual spot to gather",
    "HARMONY": "Pleasing blend of musical notes",
    "HARVEST": "When the crops come in",
    "HEADSUP": "Advance warning",
    "HEALTHY": "Fit as a fiddle",
    "HISTORY": "The study of the past",
    "HOLIDAY": "A day off the calendar",
    "HORIZON": "Line where sky meets land",
    "ICEBERG": "Floating chunk of frozen sea",
    "ILLNESS": "A sickness or disease",
    "IMAGINE": "Picture in your mind",
    "IMPULSE": "Sudden urge to act",
    "INFERNO": "A raging fire",
    "ISLANDS": "Lands surrounded by water",
    "JACKPOT": "Lottery's top prize",
    "JAVELIN": "Spear hurled in track and field",
    "JEALOUS": "Green with envy",
    "JOURNAL": "Private daily diary",
    "JOURNEY": "A long trek from A to B",
    "JOYRIDE": "Reckless drive just for fun",
    "JUGGLER": "One keeping balls in the air",
    "JUMPING": "Leaping up and down",
    "JUSTICE": "Fairness under the law",
    "KARAOKE": "Singing along to a backing track",
    "KETCHUP": "Red topping for fries",
    "KEYHOLE": "Where you insert a door key",
    "KEYNOTE": "Main speech at a conference",
    "KINGDOM": "Realm ruled by a monarch",
    "KITCHEN": "Where the cooking happens",
    "KITTENS": "Baby cats",
    "KNUCKLE": "Joint in your finger",
    "LADYBUG": "Red beetle with black spots",
    "LANTERN": "A light you carry by hand",
    "LAUNDRY": "Pile of dirty clothes to wash",
    "LEOPARD": "Spotted big cat",
    "LIBRARY": "Where you check out books",
    "LOBSTER": "Clawed sea crustacean",
    "LOOKOUT": "Sentry on watch",
    "MACHINE": "A device with moving parts",
    "MAGICAL": "Enchanting and wondrous",
    "MAGNETS": "Things that stick to the fridge",
    "MAILBOX": "Where letters get delivered",
    "MARBLES": "Glass shooters in a kids' game",
    "MEASURE": "Break out the tape to do this",
    "MEERKAT": "Desert mongoose that stands upright",
    "MERMAID": "Half-woman, half-fish of the sea",
    "MINUTES": "The hour's sixty parts",
    "MONSTER": "Scary creature under the bed",
    "MORNING": "The start of the day",
    "MOUNTED": "Climbed up on the horse",
    "MUFFINS": "Breakfast cousins of cupcakes",
    "MUSEUMS": "Places that display art and relics",
    "MUSTARD": "Yellow squeeze on a hot dog",
    "NARWHAL": "Arctic whale with a long tusk",
    "NATURAL": "Straight from nature",
    "NETWORK": "A web of connections",
    "NEUTRAL": "Taking no side in a dispute",
    "NOODLES": "Strands twirled on a fork",
    "NOSTRIL": "Opening in your nose",
    "NOTHING": "Zip, zero, zilch",
    "NUGGETS": "Bite-sized chicken pieces",
    "OATMEAL": "Warm bowl of breakfast porridge",
    "OCTOPUS": "Eight-armed inky swimmer",
    "OPENING": "First night of a show",
    "OPOSSUM": "Marsupial that plays dead",
    "ORCHARD": "Grove of fruit trees",
    "ORCHIDS": "Exotic potted flowers",
    "OSTRICH": "World's largest flightless bird",
    "OUTDOOR": "Out in the open air",
    "PACKAGE": "Parcel left on the porch",
    "PADDOCK": "Fenced field for horses",
    "PAINTER": "One who wields a brush",
    "PANCAKE": "Flat round breakfast cake",
    "PARSLEY": "Green garnish on a plate",
    "PARTIES": "Festive gatherings",
    "PARTNER": "Your other half on a team",
    "PATTERN": "A design that repeats",
    "PEACOCK": "Bird with a showy fanned tail",
    "PEANUTS": "Ballpark snack in shells",
    "PELICAN": "Big-billed coastal fisher",
    "PENGUIN": "Bird in a natural tuxedo",
    "PERFECT": "Without a single flaw",
    "PIANIST": "One who plays the keys",
    "PICTURE": "Worth a thousand words",
    "PILLOWS": "Cushions for your head",
    "POPCORN": "Buttery snack at the movies",
    "PRESENT": "What's under the tree",
    "PRETZEL": "Twisted, salted snack",
    "PROBLEM": "Houston, we have one",
    "PROFILE": "Your page on a social app",
    "PROMISE": "A solemn pinky vow",
    "PROTECT": "Shield from harm",
    "PUMPKIN": "Carved gourd at Halloween",
    "PUPPIES": "Baby dogs",
    "PYRAMID": "Egyptian pharaoh's tomb",
    "QUALITY": "Standard of excellence",
    "QUARTER": "Twenty-five cent coin",
    "QUITTER": "One who gives up",
    "RACCOON": "Masked raider of trash cans",
    "RAILWAY": "Route the trains run on",
    "RAINBOW": "Arc of color after the rain",
    "RAVIOLI": "Stuffed little pasta pockets",
    "READING": "Curling up with a book",
    "RECIPES": "Step-by-step cooking guides",
    "REPTILE": "Cold-blooded scaly animal",
    "RESPECT": "Aretha spelled it out",
    "ROOSTER": "Crowing bird at the farm",
    "ROUTINE": "Same set of daily habits",
    "SANDALS": "Open-toed summer shoes",
    "SAPLING": "A young tree",
    "SARDINE": "Tiny fish sold in a tin",
    "SAUSAGE": "Link beside the breakfast eggs",
    "SCIENCE": "What you study in the lab",
    "SEAGULL": "Squawking bird at the beach",
    "SEASONS": "The calendar's four phases",
    "SERVICE": "Help given with a smile",
    "SHELTER": "A roof over your head",
    "SLIPPER": "Cozy shoe worn at home",
    "SOLDIER": "One who serves in the army",
    "SOPRANO": "Highest female singing voice",
    "SPARKLE": "Glittery shine",
    "SPINACH": "Popeye's strength-giving green",
    "STADIUM": "Big venue for a ballgame",
    "STANDBY": "Ready and waiting",
    "STATION": "Where you catch the train",
    "STORAGE": "Where extra stuff is kept",
    "STUDENT": "One who hits the books",
    "SUNRISE": "The dawn's first light",
    "TAKEOUT": "Restaurant food to go",
    "TANGENT": "Wandering off the topic",
    "TEACHER": "The one at the front of class",
    "TEXTILE": "Woven cloth",
    "TEXTURE": "How a surface feels to the touch",
    "THEATER": "Where a play is staged",
    "THUNDER": "The boom after the lightning",
    "TICKETS": "Passes for admission",
    "TIMEOUT": "A game's brief pause",
    "TONIGHT": "This very evening",
    "TORNADO": "Spinning funnel of a storm",
    "TRACTOR": "Vehicle that plows a field",
    "TRAPEZE": "Swinging bar high in the circus",
    "TRUMPET": "Brass horn of jazz",
    "TURTLES": "Slow reptiles with shells",
    "UMPIRES": "Officials behind home plate",
    "UNICORN": "Mythical horse with a horn",
    "UPGRADE": "Move to a better version",
    "UPSTAGE": "Steal the spotlight from",
    "VAMPIRE": "Blood-drinking creature of the night",
    "VANILLA": "Classic plain ice cream flavor",
    "VAULTED": "Leaped over a barrier",
    "VICTORY": "A sweet, hard-won win",
    "VILLAGE": "A small cluster of homes",
    "VITAMIN": "Nutrient in a daily pill",
    "VOLCANO": "Mountain that spews lava",
    "VOYAGER": "One on a long sea trip",
    "WAFFLES": "Breakfast squares that hold syrup",
    "WALLETS": "Where you stash cash and cards",
    "WEATHER": "Today's rain or shine",
    "WEDDING": "A marriage ceremony",
    "WEEKEND": "Saturday and Sunday off",
    "WELCOME": "What the doormat says",
    "WHIPPED": "Beaten, as cream",
    "WHISKER": "Stiff hair on a cat's face",
    "WHISPER": "Talk under your breath",
    "WHISTLE": "Referee's noisemaker",
    "WINNERS": "The first-place finishers",
    "WIZARDS": "Spell-casting sorcerers",
    "WORKOUT": "A gym session",
    "ZOMBIES": "The walking dead",
  },
};
