// Hand-authored word + clue bank (original clues, NYT-mini style: fair, mostly
// definitional with a little wit, doable but not trivial). The generator builds
// fully-interlocked grids using ONLY these words/clues, so every puzzle is made
// of vetted entries. Grouped by length. Keep clues free of the answer word.

export default {
  3: {
    ACE: ["The best in the business", "A serve the returner can't touch", "Top gun in the fighter cockpit"],
    ACT: ["One chunk of a stage play", "Put on a show for an audience", "Behave in a certain way"],
    ADD: ["Tally up a column of numbers", "Toss one more into the mix", "The opposite of subtract"],
    AGE: ["Number of candles on the cake", "Grow older year by year", "A long stretch of history"],
    AID: ["Lend a helping hand to someone", "Relief sent to those in need", "First-aid for a scraped knee"],
    AIM: ["Line up a shot before firing", "The goal you're working toward", "Steady the bow at the target"],
    AIR: ["The stuff that fills your lungs", "Put a show on the airwaves", "What you pump into a flat tire"],
    ANT: ["Tiny soldier at the picnic", "Hard worker in a backyard colony", "Aardvark's bite-sized snack"],
    APE: ["Big primate without a tail", "Copy someone's every move", "King Kong, famously"],
    ARC: ["The gentle curve of a rainbow", "Path a thrown ball traces", "A slice of a circle's edge"],
    ARM: ["Limb from shoulder to fingertips", "What you rest on a sofa's side", "Hand out weapons before battle"],
    ART: ["What fills a museum's walls", "Paintings, sculptures, and the like", "First word in 'liberal ___'"],
    ASH: ["What's left after the fire dies", "Gray dust a volcano spews out", "Burnt tip of a cigarette"],
    BAD: ["The opposite of good", "Up to no good, like a villain", "Gone off, like week-old milk"],
    BAG: ["What you lug groceries home in", "Reusable sack at the checkout", "Bring down, as a hunter does"],
    BAR: ["Where the bartender pours drinks", "A long rod of iron or gold", "Block someone from coming in"],
    BAT: ["Winged creature of the dark cave", "Wooden stick a slugger swings", "Flit about after nightfall"],
    BAY: ["Curved stretch of sheltered coast", "A hound's long, mournful howl", "Where a truck backs in to load"],
    BED: ["Where you turn in for the night", "A planted strip in the garden", "Settle down for the night"],
    BEE: ["Buzzing maker of golden honey", "Schoolkids' spelling showdown", "Get-together for shared work"],
    BIG: ["Taking up a whole lot of room", "Larger than life", "The opposite of teeny"],
    BIT: ["A small piece of something", "Tiny unit of computer data", "Wait just a little while"],
    BOX: ["Cardboard cube for shipping", "Throw punches in the ring", "Square you check on a form"],
    BOY: ["A young fellow, not yet a man", "One of the guys", "Lad playing in the yard"],
    BUD: ["A flower before it blooms", "Close pal, casually", "What sprouts on a tree in spring"],
    BUG: ["Creepy-crawly in the garden", "Annoy someone over and over", "Glitch in the computer code"],
    BUS: ["Big ride that makes many stops", "Clear the dishes off the table", "Yellow ride to school"],
    BUY: ["Pick it up at the store", "Swallow a story as true", "The opposite of sell"],
    CAB: ["Yellow car you hail downtown", "Where a truck driver sits", "Ride that runs a meter"],
    CAP: ["Twist-off top on a bottle", "Brimmed bit of headwear", "Put a limit on spending"],
    CAR: ["Four-wheeler in the driveway", "What you park in the garage", "It runs on gas or a battery"],
    CAT: ["Pet that purrs on your lap", "Whiskered chaser of mice", "Lion or tiger, in the wild"],
    COW: ["Farm animal that gives milk", "It says moo in the pasture", "Source of a juicy steak"],
    CRY: ["Let the tears roll down", "Shout at the top of your lungs", "A baby's late-night call"],
    CUP: ["What you sip your coffee from", "Half a pint, in a recipe", "Trophy the champions lift"],
    CUT: ["Snip with a pair of scissors", "Slice taken out of the cake", "Skip a class you should attend"],
    DAY: ["Sunup-to-sundown stretch", "One square on the calendar", "Twenty-four hours, all told"],
    DEN: ["Cozy room for relaxing at home", "A wild fox's hideaway", "Wolf's lair in the woods"],
    DIG: ["Turn over soil with a shovel", "Unearth buried treasure", "Really get into something"],
    DOG: ["Loyal pet that fetches the ball", "Best friend who wags its tail", "Pup at the end of a leash"],
    DOT: ["The little point over an 'i'", "One tiny speck on the page", "Period ending a sentence"],
    DRY: ["Without a single drop of moisture", "Crack a joke with a straight face", "The opposite of soaking wet"],
    EAR: ["What you hear the music with", "A single cob of corn", "Lend one to a friend in need"],
    EAT: ["Sit down to a hearty meal", "Dig into dinner", "What you do at the kitchen table"],
    EGG: ["What you crack for an omelet", "Oval thing a hen lays", "Urge someone on, with 'on'"],
    END: ["The very last part of a story", "Bring something to a close", "Finish line you finally cross"],
    FAN: ["Devoted follower of a team", "It whirs to keep you cool", "Spread out like a deck of cards"],
    FAR: ["A great distance away", "Not anywhere close by", "Way out on the horizon"],
    FEW: ["Only a small handful", "Not very many at all", "Just a couple, give or take"],
    FIG: ["Sweet fruit in a Newton cookie", "Soft fruit, dried or fresh", "Tree mentioned in the Bible"],
    FIN: ["What helps a fish steer", "A shark's telltale dorsal one", "Flipper a scuba diver wears"],
    FIT: ["In good shape from working out", "Just the right size for you", "A sudden burst of temper"],
    FIX: ["Patch up something that's broken", "Repair a leaky faucet", "Settle on, as a date and time"],
    FLY: ["Soar high above the clouds", "Pesky insect at a cookout", "Travel the friendly skies"],
    FOG: ["Thick mist that hides the road", "Low cloud that rolls off the bay", "Haze that clouds your thinking"],
    FOX: ["Sly, bushy-tailed woodland animal", "Clever creature of fairy tales", "Den-dwelling cousin of the wolf"],
    FUN: ["A good time", "What a day at the park should be", "The opposite of boring"],
    GAP: ["An empty space in between", "Hole in the fence to slip through", "Mind it on the train platform"],
    GAS: ["What you pump into the tank", "Step on it to speed up", "Not a solid or a liquid"],
    GEM: ["A polished, precious stone", "A real hidden treasure", "Diamond or ruby in a ring"],
    GUM: ["Chewy stuff you blow bubbles with", "Pink part that holds your teeth", "Stick of mint in your pocket"],
    GUN: ["Firearm in a Western showdown", "Rev the engine hard", "Squirt one filled with water"],
    GUY: ["A regular ordinary fellow", "One of the boys, casually", "Dude hanging with friends"],
    HAM: ["Pink meat sliced at the deli", "Overact wildly on stage", "Holiday roast, often glazed"],
    HAT: ["What tops off your outfit", "Cover for a chilly head", "Pull a rabbit out of one"],
    HEN: ["Clucking layer of breakfast eggs", "Mother of the little chicks", "Female bird in the coop"],
    HIP: ["Cool and right on trend", "Joint where leg meets your side", "Totally with-it and stylish"],
    HIT: ["A chart-topping smash song", "Give it a solid whack", "Box-office smash everyone's seeing"],
    HOT: ["Straight off a sizzling stove", "Way up on the thermometer", "All the rage right now"],
    HUG: ["Wrap your arms around someone", "Warm squeeze hello or goodbye", "What a teddy bear is good for"],
    ICE: ["Frozen cubes that chill a drink", "Slick stuff a skater glides on", "Give someone the cold shoulder"],
    ILL: ["Feeling under the weather", "Home sick from work or school", "Not at all well"],
    INK: ["What flows from a fountain pen", "A squid's cloudy defense", "Get a tattoo, slangily"],
    JAM: ["Sweet fruit spread for toast", "What rush hour traps you in", "Play music freely with friends"],
    JAR: ["Glass container for the pickles", "Rattle someone's nerves", "Cookie holder on the counter"],
    JET: ["Plane that streaks across the sky", "Zoom off on a fast trip", "Deep black, like polished coal"],
    JOB: ["The work you clock in for", "Task you've been handed to do", "Your nine-to-five gig"],
    JOY: ["Pure, beaming happiness", "What the holidays should bring", "Sheer delight and gladness"],
    KEY: ["What turns to open the lock", "The most crucial part of a plan", "Black-or-white piano part"],
    KID: ["A young boy or girl", "Pull someone's leg, joking around", "Baby goat on the farm"],
    LAP: ["Once around the racetrack", "Where a cat curls up to nap", "Lick up water, as a dog does"],
    LAW: ["A rule you have to follow", "What the police uphold", "A bill that finally passed"],
    LEG: ["Limb you stand and walk on", "One stretch of a long journey", "A table needs four of these"],
    LID: ["Cover that snaps onto a jar", "What you put back on the pot", "Flap that closes over the eye"],
    LIP: ["Upper or lower edge of the mouth", "Rim around the edge of a cup", "Sassy backtalk to a parent"],
    LOG: ["Fallen tree split for the fire", "Keep a daily written record", "Sleep like one, soundly"],
    LOT: ["A huge amount of stuff", "Empty plot where cars park", "Way more than just a few"],
    LOW: ["Down near the ground", "Feeling a little blue and glum", "The opposite of sky-high"],
    MAD: ["Steaming with anger", "Wild and a little bit crazy", "Hopping over the bad news"],
    MAN: ["A grown-up male", "Staff a station or a post", "The head of the household"],
    MAP: ["Folded guide for finding your way", "What the GPS replaced", "Chart out, as a road trip"],
    MAT: ["Wipe your feet at the door", "Where a gymnast tumbles", "Padded square for a yoga class"],
    MIX: ["Stir the ingredients together", "Blend two things into one", "What a DJ spins together"],
    MOM: ["The parent who isn't dad", "Who you call on her special day", "Mother, affectionately"],
    MUD: ["Squishy mix of dirt and water", "What pigs love to roll in", "Slippery mess after the rain"],
    MUG: ["Big cup for your morning coffee", "Make goofy faces for the camera", "Rob someone on the street"],
    NAP: ["A short snooze in the afternoon", "Quick recharge with eyes closed", "What a tired toddler needs"],
    NET: ["What a tennis ball must clear", "Catch fish or butterflies in one", "Final amount after deductions"],
    NEW: ["Fresh out of the box", "Never been used before", "Just hit the store shelves"],
    NOD: ["Tip your head to say yes", "Doze off with a little head bob", "A quiet sign of agreement"],
    NUT: ["Almond, cashew, or walnut", "A bolt's threaded partner", "A real fanatic about something"],
    OAK: ["Mighty tree that drops acorns", "Strong wood for the furniture", "Shade-giver in the park"],
    OAR: ["What you row the boat with", "Paddle dipped by the crew team", "Pull it through the water"],
    ODD: ["Strange and a bit unusual", "Not even, like three or five", "The one that doesn't fit in"],
    OIL: ["Slick base for a salad dressing", "What you change in the car", "Crude stuff pumped from a well"],
    OLD: ["Way up there in years", "Been around a very long time", "The opposite of brand new"],
    OWL: ["Wide-eyed hooter of the night", "Wise bird perched in a tree", "Who-who caller after dark"],
    PAN: ["What you fry the eggs in", "Trash a movie in a harsh review", "Sift for gold in the river"],
    PAW: ["A dog's or cat's soft foot", "Bear's clawed front foot", "Handle something too roughly"],
    PEA: ["Tiny green sphere in a pod", "Veggie a princess felt under mattresses", "Little green side dish"],
    PEN: ["What you sign your name with", "Fenced area for the pigs", "Author a novel, say"],
    PET: ["Furry friend living at home", "Stroke the cat gently", "A teacher's favorite student"],
    PIE: ["Round dessert with a flaky crust", "Slice of apple or pumpkin", "Something easy, as in 'as ___'"],
    PIG: ["Pink farm animal that says oink", "Roll-in-the-mud snorter", "One who eats way too much"],
    PIN: ["Sharp little point for sewing", "Knock them all down for a strike", "Tack a note to the board"],
    PIT: ["The hard stone inside a peach", "Deep hole dug in the ground", "Where race cars stop to refuel"],
    POT: ["Where the soup simmers away", "The pile of chips on the table", "Planter the flowers grow in"],
    PUP: ["A baby dog learning to bark", "Newborn at the kennel", "Little one with floppy ears"],
    RAG: ["Old cloth for wiping up spills", "Tease someone playfully", "Tattered scrap of fabric"],
    RAT: ["City rodent in the subway", "Snitch who tells on the others", "Lab runner in a maze"],
    RAW: ["Not cooked at all", "Rubbed sore and tender", "In its natural, untreated state"],
    RED: ["Color of a stop sign", "What you turn when embarrassed", "Losing money, financially"],
    RIB: ["One curved bone in your chest", "Tease a buddy good-naturedly", "Sticky barbecue cut on the grill"],
    RIM: ["The outer edge of a wheel", "Where the basketball hoop sits", "Lip around the top of a glass"],
    ROW: ["A line of seats at the theater", "Pull the oars across the lake", "Tidy line of planted corn"],
    RUG: ["Woven mat covering the floor", "Cozy thing before the fireplace", "What you sweep dust under"],
    RUN: ["Sprint down the track", "Manage a business day to day", "A score in a baseball game"],
    SAD: ["Down in the dumps", "Feeling blue and gloomy", "What a tearjerker makes you"],
    SEA: ["Vast body of salty water", "Out on the open one, sailing", "Where the waves roll to shore"],
    SET: ["One chunk of a tennis match", "Put it down on the table", "Group of matching dishes"],
    SIP: ["Take a small, careful drink", "Slowly nurse your hot tea", "A tiny taste of the soup"],
    SIT: ["Take a seat and relax", "What you tell the dog to do", "Park yourself in a chair"],
    SKY: ["Wide blue expanse overhead", "Where the clouds drift by", "The limit, as the saying goes"],
    SLY: ["Sneaky and clever, like a fox", "Cunning with a hidden motive", "Wearing a crafty little grin"],
    SON: ["A family's male child", "Father plays catch with him", "The boy of the family"],
    SPA: ["Where you go to be pampered", "Bubbling hot tub for soaking", "Day of massages and facials"],
    SUN: ["The blazing star we orbit", "What rises in the east each morning", "Soak up rays of it at the beach"],
    TAG: ["Playground game of chase", "Price label on a new shirt", "Add a label to something"],
    TAN: ["Bronzed color from beach sun", "Light brown, like khaki", "Catch some rays to get one"],
    TAP: ["Faucet you turn for water", "A light little knock or pat", "Clacking style of dance"],
    TAR: ["Black, sticky stuff on the road", "Gooey muck in the pits", "Coat a roof to seal it up"],
    TEA: ["Hot drink steeped from leaves", "Afternoon cup with biscuits", "Juicy gossip, slangily"],
    TEN: ["A perfect score from the judges", "How many fingers you've got", "One more than nine"],
    TIE: ["What you knot around your collar", "End a game all even, no winner", "Lace up and secure your shoes"],
    TIP: ["Extra you leave the waiter", "The pointy end of a pencil", "Handy little piece of advice"],
    TOE: ["One of ten at your feet", "Stub it on the table leg", "Big one wears the sandal strap"],
    TOP: ["Spinning toy that wobbles", "The very highest point", "Beat the previous best"],
    TOY: ["Plaything a kid unwraps", "What fills up the toy box", "Fiddle with, as with an idea"],
    TUB: ["Big basin you soak in", "Pint-sized container of butter", "Where the bubble bath goes"],
    TWO: ["A pair, like a set of shoes", "One plus one", "How many it takes to tango"],
    USE: ["Put something to good work", "Make the most of what you have", "Find a purpose for it"],
    VAN: ["Boxy vehicle for hauling cargo", "Moving truck for the furniture", "Out front, leading the way"],
    VET: ["The doctor who treats your pet", "Carefully check a background", "Former soldier, for short"],
    WAR: ["A long, armed conflict", "The opposite of peacetime", "Tug-of-___ on the field"],
    WAX: ["What a candle is made of", "Buff the car to a shine", "Build-up in your ears"],
    WEB: ["Sticky trap a spider spins", "The world-wide one, online", "Tangled network of links"],
    WET: ["Soaked clean through", "Fresh paint you shouldn't touch", "The opposite of bone-dry"],
    WIN: ["Come in first place", "Take home the trophy", "Pull off the big victory"],
    WOW: ["Knock someone's socks off", "Exclaim at the fireworks", "Truly impress the crowd"],
    YES: ["A nod of full agreement", "The opposite of no", "Sure thing, absolutely"],
    ZIP: ["Fastener on your jacket", "Zero, nothing at all", "Speed along with some pep"],
    ZOO: ["Where lions and bears live", "Wild place to see the animals", "Total scene of chaos"],
  },
  4: {
    ABLE: "Up to the task at hand",
    ACID: "Sour stuff that can burn",
    ACRE: "Chunk of farmland to measure",
    AREA: "A region on the map",
    ARMY: "Soldiers marching into battle",
    AUNT: "Your mom or dad's sister",
    AUTO: "Another word for a car",
    BABY: "Newborn in the nursery",
    BAKE: "Make cookies in the oven",
    BALL: "Round thing you bounce",
    BAND: "Group that plays on stage",
    BANK: "Where you stash your money",
    BARN: "Big red building on the farm",
    BASE: "The foundation it rests on",
    BATH: "A long soak in the tub",
    BEAD: "Little bauble on a necklace",
    BEAM: "Ray of light through a window",
    BEAN: "Coffee starts out as this",
    BEAR: "Honey-loving forest beast",
    BEAT: "The steady rhythm of a drum",
    BELL: "It rings to start class",
    BELT: "Strap that holds up pants",
    BEST: "Better than all the rest",
    BIKE: "Two-wheeler you pedal",
    BIRD: "Feathered friend that flies",
    BITE: "Take a chomp of an apple",
    BLUE: "Color of a clear sky",
    BOAT: "What you sail across a lake",
    BODY: "Your whole physical self",
    BOLD: "Daring and unafraid",
    BONE: "What the dog buries",
    BOOK: "Pages you curl up to read",
    BOOT: "Sturdy footwear for the rain",
    BORN: "Brought into the world",
    BOSS: "The one calling the shots",
    BOWL: "Where the cereal goes",
    CAGE: "Where the parakeet lives",
    CAKE: "Frosted treat with candles",
    CALM: "Cool, collected, at peace",
    CAMP: "Pitch a tent in the woods",
    CARD: "One from a deck of 52",
    CARE: "Look after someone",
    CART: "Push it down the grocery aisle",
    CASH: "Cold, hard paper money",
    CAVE: ["Underground hollow", "Finally give in after holding out"],
    CHEF: "The pro running the kitchen",
    CHIN: "Just below your mouth",
    CITY: "Bustling urban hub",
    CLAP: "Show applause with your hands",
    CLAW: "Sharp nail on a cat's paw",
    CLAY: "Squishy stuff for pottery",
    COAT: "Bundle up in it when cold",
    COIN: "Loose change in your pocket",
    COLD: "Chilly enough for a jacket",
    COOK: "Whip up dinner on the stove",
    COOL: "Effortlessly hip",
    CORN: "Crop you eat off the cob",
    COZY: "Snug as a bug in a rug",
    CREW: "The team that sails a ship",
    CROP: "What the farmer harvests",
    CUBE: "Six-sided dice shape",
    CURL: "A twist of hair",
    DARK: "When all the lights go out",
    DEAL: "A bargain too good to pass up",
    DEEP: "Way down at the bottom",
    DESK: "Where you sit to do work",
    DIAL: "Spin it on an old phone",
    DICE: "Roll these in a board game",
    DISH: "A plate or bowl at dinner",
    DOOR: "Open it to enter a room",
    DOVE: "White bird of peace",
    DRAW: "Sketch with a pencil",
    DROP: "Let it slip from your hand",
    DRUM: "Bang it to keep the beat",
    DUCK: "Quacking bird at the pond",
    DUST: "Film of grime on a shelf",
    EACH: "Every single one",
    EARN: "Bring home a paycheck",
    EAST: "Where the sun comes up",
    EASY: "A breeze to pull off",
    EDGE: "The very rim or border",
    FACE: "The front of your head",
    FACT: "Something known to be true",
    FAIR: "Square and even to all",
    FALL: "Season when the leaves drop",
    FARM: "Where the crops are grown",
    FAST: "Quick as a flash",
    FEAR: "What a scary movie stirs up",
    FERN: "Leafy, feathery houseplant",
    FILM: "What you catch at the cinema",
    FIRE: "Crackling blaze at the campsite",
    FISH: "Swimmer you catch on a hook",
    FIST: "Tightly clenched hand",
    FLAG: "A nation's striped symbol",
    FLAT: "Level, with no bumps",
    FLEA: "Tiny biter on the dog",
    FLEW: "Took off into the air",
    FOAM: "Frothy bubbles on a latte",
    FOLD: "Crease the laundry neatly",
    FOND: "Warm and affectionate",
    FOOD: "What's on the dinner plate",
    FOOT: "Twelve inches long",
    FORK: "Spear your dinner with it",
    FORM: "The shape something takes",
    FREE: "Yours at no cost at all",
    FROG: "Green hopper on a lily pad",
    FUEL: "What powers the engine",
    FULL: "Stuffed to the brim",
    GAME: "A match played to win",
    GATE: "Swing it open in the fence",
    GIFT: "Wrapped present with a bow",
    GIRL: "A young lass",
    GLAD: "Happy and pleased",
    GLOW: "Soft, warm light",
    GOAL: "What you're aiming for",
    GOAT: "Sure-footed mountain climber",
    GOLD: "Metal of a first-place medal",
    GOOD: "The opposite of bad",
    GRAB: "Snatch it up quickly",
    GRAY: "Color of a stormy sky",
    GROW: "Get bigger over time",
    HALF: "Fifty percent of the whole",
    HALL: "Long corridor between rooms",
    HAND: "What's at the end of your arm",
    HARD: "Tricky and tough to do",
    HEAD: "What sits atop your neck",
    HEAT: "Warmth from the furnace",
    HERD: "Group of cattle grazing",
    HERO: "Brave one who saves the day",
    HIDE: "Tuck out of sight",
    HIGH: "Way up above the ground",
    HILL: "Small mound you climb",
    HINT: "A little nudge toward the answer",
    HIVE: "Buzzing home for the bees",
    HOLD: "Keep a firm grip on",
    HOLE: "Gap dug in the ground",
    HOME: "Where you hang your hat",
    HOPE: "Wish for the best",
    HORN: "What you honk in traffic",
    HOUR: "Sixty minutes on the clock",
    ICON: "Little symbol on your phone",
    IDEA: "A bright thought that strikes",
    IRON: "Smooth out the wrinkles",
    ITEM: "One thing on the list",
    JOKE: "Tale that ends in a punchline",
    JUMP: "Leap up off the ground",
    KICK: "Boot the soccer ball",
    KIND: "Warm-hearted and caring",
    KING: "Crowned ruler of the realm",
    KISS: "Smooch on the cheek",
    KNEE: "Joint in the middle of your leg",
    KNOW: "Have it down pat",
    LACE: "String you tie your shoe with",
    LAKE: "Calm body of inland water",
    LAMP: "Light on the bedside table",
    LAND: "Touch down on the runway",
    LATE: "Showing up past the deadline",
    LAWN: "Grass you mow out front",
    LEAF: "Green flap on a tree branch",
    LEAP: "A great big jump",
    LEFT: ["Not right", "Already headed out the door"],
    LEND: "Loan it out for a while",
    LIFE: "Birth-to-death existence",
    LIFT: "Hoist it up off the floor",
    LIME: "Tart green citrus fruit",
    LINE: "Queue at the checkout",
    LION: "Mane-sporting king of beasts",
    LIST: "Rundown of to-do items",
    LOAF: "One whole baked bread",
    LOCK: "What a key turns open",
    LONG: "Stretching way out",
    LOOK: "Take a quick peek",
    LOUD: "Cranked up and noisy",
    LOVE: "Adore with all your heart",
    LUCK: "A bit of good fortune",
    MAIL: "What the postal carrier brings",
    MANY: "A whole bunch of them",
    MASK: "Cover worn over the face",
    MAZE: "Twisty puzzle of paths",
    MEAL: "Breakfast, lunch, or dinner",
    MEAT: "Steak from the butcher",
    MELT: "Turn from solid to liquid",
    MENU: "List of dishes to order",
    MILD: "Gentle and not too spicy",
    MILK: "Pour it over your cereal",
    MIND: "Where your thoughts happen",
    MINT: "Fresh herb in a mojito",
    MOON: "Glowing orb in the night sky",
    MOST: "The greatest share of all",
    MOTH: "Insect drawn to the porch light",
    NAME: "What you go by",
    NEAR: "Just a short distance away",
    NEAT: "Tidy and well-organized",
    NEST: "Twiggy home for the eggs",
    NICE: "Pleasant and friendly",
    NOON: "Twelve on the dot, midday",
    NOSE: "What you smell with",
    NOTE: "Quick message left behind",
    OPEN: "Unlocked and ready for business",
    OVEN: ["Baking box", "Where cookies catch their golden tan"],
    ECHO: ["Bounced-back sound", "The canyon's habit of repeating you"],
    BARK: ["Dog's sound", "Reputedly worse than the actual bite"],
    SEAL: ["Arctic swimmer", "Shut it so no air escapes"],
    NAIL: ["Hammer's target", "To absolutely crush it, slangily"],
    CLUB: ["Golfer's choice", "Night spot for dancing"],
    PACK: "Stuff a suitcase for a trip",
    PAGE: "One leaf in a book",
    PAIL: "Bucket for the sandcastle",
    PAIN: "A sharp ache",
    PAIR: "A matching set of two",
    PALM: "Swaying tree on the beach",
    PARK: "Green space for a picnic",
    PART: "One piece of the whole",
    PATH: "Trail winding through the woods",
    PEAK: "The tippy top of the mountain",
    PEAR: "Bell-shaped fruit on the tree",
    PILE: "Heap stacked up high",
    PINE: "Christmas-tree evergreen",
    PINK: "Soft shade of light red",
    PLAN: "A worked-out strategy",
    PLAY: "Romp around for fun",
    PLUM: "Sweet purple stone fruit",
    PLUS: "The little addition sign",
    POEM: "Verse that might rhyme",
    POND: "Little pool for the ducks",
    POOL: "Where you take a swim",
    POUR: "Tip the pitcher to fill a glass",
    PROP: "Object an actor uses on stage",
    PULL: "Tug it toward yourself",
    PUSH: "Shove it forward",
    QUIZ: "A short little test",
    RACE: "Contest to the finish line",
    RAFT: "Flat float on the river",
    RAIN: "Wet weather from the clouds",
    RARE: "Hard to come by",
    READ: "Page through a good book",
    REST: "Take a well-earned break",
    RICE: "Grain served with sushi",
    RICH: "Rolling in money",
    RIDE: "Hop in for a quick spin",
    RING: ["Finger band", "Boxer's battleground"],
    RIPE: "Ready to pick and eat",
    RISE: "Climb up higher",
    ROAD: "Paved route for the cars",
    ROCK: "A solid hunk of stone",
    ROLE: "The part an actor plays",
    ROOF: "What tops off the house",
    ROOM: "A space within the house",
    ROOT: "Part of a plant underground",
    ROPE: "Thick cord for tying",
    ROSE: "Thorny flower for a sweetheart",
    RUDE: "Lacking any manners",
    RUSH: "Move in a big hurry",
    SAFE: "Out of harm's way",
    SAIL: "Canvas that catches the wind",
    SALT: "Pepper's shaker partner",
    SAND: "Grains that fill the beach",
    SEAT: "Where you park yourself",
    SEED: "Tiny start of a plant",
    SEEK: "Go hunting for",
    SELL: "Offer up for money",
    SHIP: "Big vessel out at sea",
    SHOE: "What goes on your foot",
    SHOP: "Browse around the store",
    SHOW: "Put it on display",
    SHUT: "Close it tight",
    SICK: "Feeling poorly, home in bed",
    SIDE: "The left or right edge",
    SILK: "Smooth, luxurious fabric",
    SING: "Belt out a tune",
    SINK: "Basin in the kitchen",
    SITE: "A particular spot or location",
    SIZE: "How big something is",
    SKIN: "What covers your whole body",
    SLED: "Coast downhill on the snow",
    SLOW: "Moving at a crawl",
    SNOW: "White flakes of winter",
    SOAP: "Sudsy bar in the shower",
    SOCK: "Knit warmer for your foot",
    SOFT: "Squishy to the touch",
    SOIL: "Dirt the garden grows in",
    SONG: "Tune you hum along to",
    SOUP: "Warm bowl of broth",
    SOUR: "Puckery, like a lemon",
    STAR: ["Night sky twinkler", "The one with top billing tonight"],
    STAY: "Stick around a while",
    STEM: "Stalk holding up a flower",
    STEP: "One stair on the way up",
    STOP: "Come to a full halt",
    SWIM: "Glide through the water",
    TAIL: "What a happy dog wags",
    TALL: "Stretching way up high",
    TAME: "Gentle, not at all wild",
    TANK: "Where the goldfish swims",
    TAPE: "Sticky roll for wrapping",
    TASK: "A job to get done",
    TEAM: "Players working together",
    TEAR: "Drop that rolls down a cheek",
    TELL: "Let someone in on it",
    TENT: "Canvas shelter for camping",
    TEST: "Exam you study hard for",
    TIDE: ["Ocean's rise and fall", "It rolls in, then slips away"],
    TIDY: "Spick-and-span and neat",
    TIME: "What the clock keeps",
    TINY: "Itty-bitty and small",
    TIRE: "Rubber that meets the road",
    TONE: "The quality of a voice",
    TOOL: "A hammer or a wrench",
    TORN: "Ripped right down the middle",
    TOWN: "A small little city",
    TREE: "Tall plant with a trunk",
    TRIP: "A getaway vacation",
    TRUE: "Honest and not false",
    TUNE: "A catchy little melody",
    TURN: "Your go in the game",
    TWIN: "One of an identical pair",
    VASE: "Where you put the flowers",
    VAST: "Huge and wide open",
    VOTE: "Cast it on election day",
    WAIT: "Hang tight for a bit",
    WAKE: "Rise and shine in the morning",
    WALK: "Take a leisurely stroll",
    WALL: "What divides two rooms",
    WARM: "Toasty and comfortable",
    WASH: "Scrub it clean with water",
    WAVE: ["Ocean swell", "Stadium ripple"],
    WEAK: "Lacking any strength",
    WEAR: "Put on your clothes",
    WEEK: "Seven days in a row",
    WEST: "Where the sun goes down",
    WIDE: "Stretching far across",
    WILD: "Untamed and free",
    WIND: "Breeze that rustles the leaves",
    WING: "What a bird flaps to fly",
    WISE: "Full of good sense",
    WISH: "Make one on a candle",
    WOLF: "Howling pack hunter",
    WOOD: "Lumber from the forest",
    WORD: "What fills a crossword square",
    WORK: "Clock in for the day",
    WORM: "Wriggler in the garden soil",
    YARD: "Grassy space behind the house",
    YEAR: "365 days on the calendar",
    ZERO: "Nothing at all, zilch",
    ZONE: "A particular area or region",
  },
  5: {
    ABOVE: "Up over your head",
    ACTOR: "One always playing a part",
    ADULT: "No longer a kid",
    AGREE: "See eye to eye",
    ALARM: "It goes off at the crack of dawn",
    ALERT: "Wide awake and watchful",
    ALIVE: "Still kicking",
    ALONE: "Flying solo",
    ANGEL: "One with a halo and wings",
    ANGER: "What you count to ten to cool",
    ANGLE: "A right one is ninety degrees",
    APPLE: "It keeps the doctor away, they say",
    APRON: "It keeps the chef's shirt clean",
    ARENA: "Where gladiators once fought",
    ARROW: "Cupid's pointed tool",
    AWARD: "What the winner takes home",
    AWARE: "Hip to what's going on",
    BACON: "It brings home the paycheck, in a saying",
    BADGE: "A detective flashes it",
    BAKER: "A dozen-plus-one namesake",
    BASIC: "Nothing fancy about it",
    BEACH: "Where you build sandcastles",
    BEARD: "Santa's white whiskers",
    BEGIN: "Get the ball rolling",
    BENCH: "Where the subs sit",
    BERRY: "Straw- or blue- ender",
    BIRTH: "The very start of life",
    BLACK: "Color of a starless night",
    BLADE: "The sharp part of a razor",
    BLAME: "Pin the fault on",
    BLANK: "Fill-in-the-___ space",
    BLAST: "A real ball of a time",
    BLEND: "What a smoothie maker does",
    BLINK: "It happens in the ___ of an eye",
    BLOOM: "What a rose does in spring",
    BOARD: "Plank you might walk",
    BOAST: "Toot your own horn",
    BONUS: "A little extra in the paycheck",
    BOOST: "A leg up",
    BRAIN: "The body's command center",
    BRAND: "Nike or Apple, e.g.",
    BRAVE: "Not scared one bit",
    BREAD: "What you knead and bake",
    BREAK: "What you give a tired worker",
    BRICK: "One unit in a wall",
    BRIEF: "Over in no time",
    BRING: "Tote it along",
    BROAD: "Wide open",
    BROOM: "A witch's ride",
    BROWN: "UPS truck color",
    BRUSH: "What an artist wields",
    BUILD: "Raise from the ground up",
    BUNCH: "A whole slew of them",
    CABIN: "Log home in the woods",
    CANDY: "Halloween haul",
    CARGO: "What a freighter hauls",
    CHAIN: "Links joined together",
    CHAIR: "Musical ___s prize",
    CHALK: "It squeaks on the board",
    CHARM: "Bracelet dangler",
    CHART: "It tracks the ups and downs",
    CHASE: "Give hot pursuit",
    CHEAP: "Light on the wallet",
    CHEER: "What fans do for the home team",
    CHESS: "Game with a king and queen",
    CHEST: "Where the loot gets buried",
    CHILD: "Not yet grown",
    CHILL: "Kick back and relax",
    CIVIC: "___ duty, like jury service",
    CLAIM: "Stake your ___",
    CLASS: "Where the teacher teaches",
    CLEAN: "Squeaky and spotless",
    CLEAR: "See-through, like glass",
    CLICK: "Sound of the mouse",
    CLIFF: "Edge you don't go over",
    CLIMB: "Make your way up",
    CLOCK: "It's got hands but can't clap",
    CLOSE: "Shut tight",
    CLOTH: "What a tailor cuts",
    CLOUD: "It might have a silver lining",
    CLOWN: "Send in the ___s",
    COACH: "The one with the playbook",
    COAST: "Where the surfers head",
    COLOR: "A crayon's job",
    COUCH: "Where a potato might sit",
    COUNT: "What Dracula is, fittingly",
    COURT: "Where the judge presides",
    COVER: "Put a lid on it",
    CRACK: "Hairline split",
    CRAFT: "Etsy's specialty",
    CRANE: "Long-necked construction lifter",
    CRASH: "Fender-bender result",
    CRAWL: "Move at a snail's pace",
    CRAZY: "Off the wall",
    CREAM: "The ___ of the crop",
    CRISP: "Fresh and crunchy",
    CROSS: "Get to the other side",
    CROWD: "A real sea of people",
    CROWN: "It sits heavy, they say",
    CURVE: "Pitcher's breaking ball",
    DAISY: "Petal-plucking flower",
    DANCE: "Cut a rug",
    DEPTH: "How far down it goes",
    DOZEN: "Egg-carton count",
    DRAFT: "First crack at the essay",
    DREAM: "What you have while asleep",
    DRESS: "Ball gown",
    DRINK: "Wet your whistle",
    DRIVE: "Take the wheel",
    EAGER: "Champing at the bit",
    EAGLE: "Two under par, to a golfer",
    EARLY: "Beating the rush",
    EARTH: "The third rock from the sun",
    EMPTY: "Running on ___, no gas left",
    ENJOY: "Have a ball",
    ENTER: "Step inside",
    EQUAL: "Even-steven",
    ERROR: "What an eraser fixes",
    EVENT: "A big to-do",
    EVERY: "Each and all",
    EXTRA: "One to spare",
    FAITH: "Belief without proof",
    FANCY: "Dressed to the nines",
    FAULT: "Whose ___ is it",
    FEAST: "Big meal",
    FENCE: "Yard border",
    FIELD: "Open grassland",
    FIGHT: "Brawl",
    FINAL: "Last",
    FIRST: "Number one",
    FLAME: "Candle's fire",
    FLASH: "Quick burst of light",
    FLOAT: "Stay on water",
    FLOOR: "Room's bottom",
    FLOUR: "Baking powder",
    FLOWER: "Garden bloom",
    FOCUS: "Concentrate",
    FORCE: "Power",
    FRESH: "Just-picked",
    FRONT: "Opposite of back",
    FROST: "Window-pane ice",
    FRUIT: "Apple or pear",
    FUNNY: "Hilarious",
    GHOST: "Spooky spirit",
    GIANT: "Huge being",
    GLASS: "Window pane",
    GLOBE: "Earth model",
    GLOVE: "Hand warmer",
    GRACE: "Elegance",
    GRADE: "Report-card mark",
    GRAIN: "Wheat unit",
    GRAND: "Magnificent",
    GRAPE: "Wine fruit",
    GRASS: "Lawn green",
    GREAT: "Excellent",
    GREEN: "Grass color",
    GRILL: "Backyard cooker",
    GROUP: "Cluster",
    GUARD: "Protector",
    GUESS: "Take a stab",
    GUEST: "Visitor",
    HAPPY: "Joyful",
    HEART: "Love symbol",
    HEAVY: "Weighty",
    HONEY: "Bee's sweet output",
    HORSE: "Stable animal",
    HOTEL: "Travel lodging",
    HOUSE: "Family dwelling",
    HUMAN: "Person",
    HUMOR: "Sense of fun",
    IDEAL: "Perfect",
    IMAGE: "Picture",
    JEWEL: "Precious gem",
    JOINT: "Body's bend",
    JUICE: "Orange drink",
    KNIFE: "Cutting tool",
    LABEL: "Product tag",
    LARGE: "Big",
    LASER: "Focused beam",
    LAUGH: "React to a joke",
    LAYER: "Cake tier",
    LEARN: "Pick up knowledge",
    LEMON: "Sour yellow fruit",
    LEVEL: "Flat and even",
    LIGHT: "Lamp's output",
    LIVER: "Body organ",
    LODGE: "Ski cabin",
    LUCKY: "Fortunate",
    LUNCH: "Midday meal",
    MAGIC: "Wizard's craft",
    MAYOR: "City leader",
    MEDAL: "Winner's award",
    MERCY: "Compassion",
    METAL: "Iron or steel",
    METER: "Distance unit",
    MIGHT: "Power",
    MONEY: "Cash",
    MONTH: "April or May",
    MOUNT: "Climb up",
    MOUSE: "Cheese nibbler",
    MOUTH: "Where you eat",
    MOVIE: "Film",
    MUSIC: "Song and sound",
    NIGHT: "After sunset",
    NOISE: "Loud sound",
    NORTH: "Compass top",
    NOVEL: "Long story",
    NURSE: "Hospital helper",
    OCEAN: "Vast sea",
    OFFER: "Propose",
    ONION: "Tear-causing veggie",
    ORDER: "Restaurant request",
    ORGAN: "Church instrument",
    OTTER: "Playful river mammal",
    OWNER: "One who has it",
    PAINT: "Wall coating",
    PANIC: "Sudden fear",
    PAPER: "Notebook sheet",
    PARTY: "Celebration",
    PASTE: "Glue-like stuff",
    PATCH: "Repair piece",
    PAUSE: "Brief stop",
    PEACE: "Calm and quiet",
    PEACH: "Fuzzy fruit",
    PEARL: "Oyster gem",
    PHONE: "Pocket caller",
    PIANO: "Keyboard instrument",
    PILOT: "Plane flier",
    PIZZA: "Cheesy pie",
    PLACE: "Spot",
    PLAIN: "Simple",
    PLANE: "Sky traveler",
    PLANT: "Garden grower",
    PLATE: "Dinner dish",
    POINT: "Pencil's tip",
    PORCH: "Front step area",
    POUND: "Sixteen ounces",
    POWER: "Strength",
    PRESS: "Push down",
    PRICE: "Cost",
    PRIDE: "Self-respect",
    PRINT: "Newspaper output",
    PRIZE: "Award",
    PROUD: "Pleased with oneself",
    PROVE: "Show to be true",
    PUNCH: "Boxer's blow",
    PUPIL: ["Student", "It widens in the dark"],
    QUEEN: "King's partner",
    QUICK: "Speedy",
    QUIET: "Hushed",
    QUILT: "Patchwork blanket",
    QUITE: "Rather",
    RADIO: "Music box on the dash",
    RANCH: "Cattle spread",
    RANGE: "Mountain chain",
    RAPID: "Very fast",
    REACH: "Stretch toward",
    RELAX: "Unwind",
    REPLY: "Answer back",
    RHYME: "Poem's match",
    RIDGE: "Hill's crest",
    RIVER: "Flowing water",
    ROAST: "Cook in the oven",
    ROBIN: "Red-breasted bird",
    ROBOT: "Mechanical helper",
    ROUND: "Circular",
    ROUTE: "Travel path",
    ROYAL: "Of the crown",
    SALAD: "Leafy dish",
    SAUCE: "Pasta topping",
    SCALE: "Weight checker",
    SCARF: "Neck warmer",
    SCENE: "Movie segment",
    SCORE: "Game tally",
    SCOUT: "Badge earner",
    SENSE: "Sight or smell",
    SHACK: "Small hut",
    SHADE: ["Spot out of the sun", "Subtle dig, in slang"],
    SHAPE: "Form",
    SHARE: "Divide up",
    SHARK: "Ocean predator",
    SHARP: "Knife-like",
    SHEEP: "Wool provider",
    SHEET: "Bed cover",
    SHELF: "Wall ledge",
    SHELL: "Beach find",
    SHINE: "Gleam",
    SHIRT: "Torso wear",
    SHORE: "Beach edge",
    SHORT: "Not tall",
    SHOUT: "Yell",
    SIGHT: "Vision",
    SKATE: "Ice glider",
    SLEEP: "Nighttime rest",
    SLICE: "Pizza piece",
    SLIDE: "Playground feature",
    SMALL: "Little",
    SMART: "Clever",
    SMELL: "Use the nose",
    SMILE: "Happy face",
    SMOKE: "Fire's plume",
    SNACK: "Light bite",
    SNAKE: "Slithering reptile",
    SOLAR: "Of the sun",
    SOLID: "Not liquid",
    SOUND: "What ears detect",
    SOUTH: "Compass bottom",
    SPACE: "Final frontier",
    SPARE: "Extra",
    SPARK: "Tiny flash of fire",
    SPEAK: "Talk",
    SPEED: "Fast pace",
    SPELL: "Order the letters",
    SPEND: "Pay out",
    SPICE: "Cinnamon, e.g.",
    SPILL: "Knock over a drink",
    SPINE: "Backbone",
    SPLIT: "Divide",
    SPOON: "Soup utensil",
    SPORT: "Athletic game",
    STAFF: "Workers",
    STAGE: "Theater platform",
    STAIR: "Step up",
    STAMP: "Letter sticker",
    STAND: "Get on your feet",
    STARE: "Look long and hard",
    START: "Begin",
    STATE: "Texas or Ohio",
    STEAM: "Kettle's vapor",
    STEEL: "Strong metal",
    STERN: "Strict",
    STICK: "Tree twig",
    STING: "Bee's jab",
    STOCK: "Store's supply",
    STONE: "Rock",
    STORE: "Shop",
    STORM: ["Bad weather", "Burst in angrily"],
    STORY: "Tale",
    STOVE: "Kitchen cooker",
    STUDY: "Hit the books",
    STYLE: "Fashion sense",
    SUGAR: "Sweetener",
    SUNNY: "Cloudless",
    SUPER: "Fantastic",
    SWEET: "Sugary",
    SWING: "Playground seat",
    TABLE: "Dining furniture",
    TASTE: "Tongue's sense",
    TEACH: "Give lessons",
    THANK: "Show gratitude",
    THICK: "Not thin",
    THINK: "Use your head",
    THREE: "A trio",
    THROW: "Toss",
    TIGER: "Striped big cat",
    TIGHT: "Snug",
    TITLE: "Book's name",
    TOAST: "Browned bread",
    TODAY: "This very day",
    TOOTH: "Smile feature",
    TORCH: "Handheld flame",
    TOUCH: "Feel with a finger",
    TOWEL: "Beach drier",
    TOWER: "Tall structure",
    TRACK: "Runner's loop",
    TRADE: "Swap",
    TRAIL: "Hiking path",
    TRAIN: "Railway ride",
    TREAT: "Special goody",
    TREND: "Latest fad",
    TRICK: "Sneaky move",
    TRUCK: "Big hauler",
    TRUST: "Have faith in",
    TRUTH: "Honest fact",
    UNCLE: "Aunt's spouse",
    UNDER: "Below",
    UNITE: "Join together",
    UPPER: "Higher one",
    VALUE: "Worth",
    VIDEO: "Recorded clip",
    VOICE: "Speaking sound",
    WAGON: "Pull-along cart",
    WATCH: "Wrist clock",
    WATER: "H2O",
    WHALE: "Ocean giant",
    WHEAT: "Bread grain",
    WHEEL: "Round roller",
    WHITE: "Snow's color",
    WHOLE: "Entire",
    WOMAN: "Adult female",
    WORLD: "The globe",
    WORTH: "Value",
    WOUND: "Injury",
    WRIST: "Hand joint",
    WRITE: "Put on paper",
    YOUNG: "Not old",
    YOUTH: "Young person",
    ZEBRA: "Striped grazer",
    ADOBE: "Sun-dried brick",
    AGENT: "Spy or rep",
    AISLE: "Store walkway",
    ALBUM: "Photo collection",
    ALLOW: "Permit",
    ALONG: "Beside",
    ALPHA: "First Greek letter",
    AMUSE: "Make laugh",
    ANKLE: "Foot joint",
    APART: "Separated",
    ARGUE: "Bicker",
    ARISE: "Get up",
    ASIDE: "Off to one side",
    ATTIC: "Top-floor storage",
    AUDIO: "Sound part",
    AVOID: "Steer clear of",
    AWAKE: "Not asleep",
    BARGE: "Flat cargo boat",
    BASIN: "Sink bowl",
    BATCH: "Group baked at once",
    BLOCK: "City square",
    BLUSH: "Cheek redness",
    BOOTH: "Diner seat",
    BOUND: "Tied up",
    BRACE: "Support beam",
    BRAKE: "Pedal to stop",
    BRASS: "Trumpet's metal",
    BREED: "Dog type",
    BROKE: "Out of cash",
    BUGLE: "Army horn",
    BUNNY: "Easter hopper",
    CABLE: "TV wire",
    CANAL: "Boat channel",
    CARVE: "Cut a turkey",
    CHIME: "Doorbell sound",
    CHOIR: "Singing group",
    CHORD: "Musical notes together",
    CHUNK: "Big piece",
    CIDER: "Apple drink",
    CLASP: "Necklace catch",
    CLOAK: "Hooded wrap",
    CLUMP: "Cluster",
    COMET: ["Tailed space rock", "Halley's, famously"],
    CORAL: "Reef builder",
    COUGH: "Cold symptom",
    CRANK: "Hand turner",
    CRATE: "Wooden box",
    CREEK: "Small stream",
    CREST: "Wave's top",
    CRUMB: "Cookie bit",
    CURRY: "Spiced dish",
    DAIRY: "Milk section",
    DECAY: "Rot",
    DELTA: "River mouth",
    DENIM: "Jeans fabric",
    DIGIT: "0 through 9",
    DITCH: "Roadside trench",
    DODGE: "Dart away from",
    DOUGH: "Bread base",
    DRAIN: "Sink hole",
    DRIFT: "Float aimlessly",
    DUSTY: "Needing a cleaning",
    DWELL: "Live somewhere",
    ELBOW: "Arm joint",
    ELDER: "Older one",
    ELECT: "Vote in",
    ELITE: "Top tier",
    EXILE: "Banish",
    FABLE: "Moral tale",
    FETCH: "Go get",
    FIBER: "Diet roughage",
    FINCH: "Small songbird",
    FLOCK: "Sheep group",
    FLUSH: "Toilet action",
    FORTY: "Four times ten",
    FROWN: "Unhappy face",
    GLOOM: "Darkness",
    GRIEF: "Deep sorrow",
    GRIND: "Crush to bits",
    GROAN: "Moan",
    HATCH: "Egg opening",
    HAVEN: "Safe place",
    HEDGE: "Bush row",
    HOVER: "Float in place",
    HUMID: "Muggy",
    IGLOO: "Ice dome",
    INDEX: "Book's word list",
    INLET: "Small bay",
    IVORY: "Elephant tusk",
    KOALA: "Eucalyptus muncher",
    LATCH: "Gate fastener",
    LEDGE: "Narrow shelf",
    LINEN: "Bed fabric",
    LLAMA: "Andes pack animal",
    LOYAL: "Faithful",
    MAPLE: "Syrup tree",
    MARSH: "Wetland",
    MEDIA: "Press and TV",
    MELON: "Cantaloupe, e.g.",
    MERIT: "Deserve",
    MOTEL: "Roadside inn",
    MOTOR: "Engine",
    MOUND: "Pile of dirt",
    MOURN: "Grieve",
    MOVER: "Furniture hauler",
    NIECE: "Brother's daughter",
    NOBLE: "Honorable",
    NUDGE: "Gentle push",
    OLIVE: "Martini garnish",
    PADDLE: "Canoe oar",
    PEDAL: "Bike pusher",
    PERCH: "Bird's roost",
    PETAL: "Flower leaf",
    PILOT: "Cockpit pro",
    PIVOT: "Turn on a point",
    PLUMP: "Chubby",
    POLAR: "Of the icy ends",
    PRINT: "Newspaper output",
    PRONG: "Fork tine",
    PROWL: "Sneak around",
    PULSE: "Heartbeat",
    PUREE: "Blended food",
    QUACK: "Duck's call",
    QUARK: "Tiny particle",
    RAVEN: "Black bird",
    REBEL: "One who revolts",
    REIGN: "Rule as king",
    RINSE: "Wash lightly",
    RIVAL: "Competitor",
    ROOST: "Hen's perch",
    ROUGH: "Not smooth",
    SCALP: "Top of the head",
    SCENT: "Aroma",
    SCOLD: "Tell off",
    SCOOP: "Ice cream serving",
    SCRAP: "Leftover bit",
    SCRUB: "Clean hard",
    SHALE: "Layered rock",
    SHELF: "Wall ledge",
    SHRUB: "Small bush",
    SKULL: "Head bone",
    SLEET: "Icy rain",
    SLOPE: "Ski hill",
    SMELT: "A small fish",
    SNAIL: "Slow shelled crawler",
    SNORE: "Sleep sound",
    SNOUT: "Pig's nose",
    SPADE: "Digging tool",
    SPRAY: "Fine mist",
    SQUID: "Inky sea creature",
    STALK: "Plant stem",
    STASH: "Hidden supply",
    STEEP: "Sharply sloped",
    STILT: "Tall leg pole",
    STOOL: "Backless seat",
    STRAW: "Sipping tube",
    STRIP: "Long thin piece",
    STUMP: "Tree base",
    SWEAT: "Workout drip",
    SWEEP: "Use a broom",
    SWIRL: "Spiral pattern",
    SWORD: "Knight's blade",
    THORN: "Rose's prickle",
    THUMB: "Hand's stubby digit",
    TIMER: "Countdown clock",
    TONIC: "Gin's partner",
    TOPIC: "Subject",
    TRACE: "Faint mark",
    TRAIT: "Characteristic",
    TRIBE: "People group",
    TROUT: "Stream fish",
    TULIP: "Spring bulb flower",
    TUTOR: "Private teacher",
    TWIST: "Turn sharply",
    USHER: "Theater guide",
    VAPOR: "Mist",
    VIGOR: "Energy",
    VINYL: "Old record material",
    VOWEL: "A, E, I, O, or U",
    WAGER: "Bet",
    WALTZ: "Ballroom dance",
    WEARY: "Tired out",
    WEAVE: "Make cloth",
    WEDGE: "Door stopper",
    WHARF: "Boat dock",
    WHISK: "Egg beater",
    WIDOW: "She lost her husband",
    WINCE: "Flinch in pain",
    WOVEN: "Made on a loom",
    YACHT: "Luxury boat",
    YEAST: "Bread riser",
    YIELD: "Give way",
    PITCH: ["Throw to the batter", "A salesperson's spiel"],
    TRUNK: ["Elephant's nose", "Road-trip packing spot"],
  },
  6: {
    ANIMAL: "Zoo creature",
    ANSWER: "Reply to a question",
    AUTUMN: "Fall season",
    BANANA: "Yellow peel fruit",
    BASKET: "Woven carrier",
    BEAUTY: "Loveliness",
    BLOSSOM: "Spring flower",
    BOTTLE: "Drink container",
    BRANCH: "Tree limb",
    BREATH: "Lungful of air",
    BRIDGE: "River crosser",
    BRIGHT: "Full of light",
    BROKEN: "In pieces",
    BUBBLE: "Soap sphere",
    BUCKET: "Pail",
    BUTTER: "Toast spread",
    BUTTON: "Shirt fastener",
    CAMERA: "Photo taker",
    CANDLE: "Wax light",
    CANYON: "Deep gorge",
    CARPET: "Floor rug",
    CASTLE: "Royal fortress",
    CHANCE: "Opportunity",
    CHANGE: "Make different",
    CHARGE: ["Rush forward", "What's on your credit card"],
    CHEESE: "Pizza topping",
    CHERRY: "Pie fruit",
    CIRCLE: "Round shape",
    CLEVER: "Smart",
    CLOSET: "Clothes storage",
    COFFEE: "Morning brew",
    COOKIE: "Sweet baked disc",
    CORNER: "Where walls meet",
    COTTON: "Soft fabric fiber",
    COUSIN: "Aunt's child",
    DANGER: "Risk",
    DECIDE: "Make a choice",
    DESERT: "Sandy expanse",
    DINNER: "Evening meal",
    DOLLAR: "Greenback",
    DONKEY: "Stubborn pack animal",
    DRAGON: "Fire-breathing beast",
    DREAMS: "Sleep visions",
    EASILY: "Without trouble",
    ENGINE: "Car's motor",
    ESCAPE: "Break free",
    FAMILY: "Kin",
    FATHER: "Male parent",
    FELLOW: "Guy",
    FINGER: "Hand digit",
    FLOWER: "Garden bloom",
    FOREST: "Wooded area",
    FRIEND: "Pal",
    FROZEN: "Iced over",
    GARAGE: "Car shelter",
    GARDEN: "Flower plot",
    GENTLE: "Soft and mild",
    GOLDEN: "Made of gold",
    GROUND: "Earth underfoot",
    GUITAR: "Strummed instrument",
    HAMMER: "Nail driver",
    HANDLE: "Door grip",
    HAPPEN: "Take place",
    HEALTH: "Wellness",
    HEAVEN: "Sky paradise",
    HELMET: "Head protector",
    HONEST: "Truthful",
    ISLAND: "Land in the sea",
    JACKET: "Light coat",
    JUNGLE: "Dense forest",
    KETTLE: "Tea boiler",
    KITTEN: "Baby cat",
    LADDER: "Climbing rungs",
    LETTER: "Mailed note",
    LISTEN: "Pay attention to sound",
    LITTLE: "Small",
    MARBLE: "Shooter in a game",
    MARKET: "Place to shop",
    MASTER: "Expert",
    MIDDLE: "Center",
    MINUTE: "Sixty seconds",
    MIRROR: "Reflecting glass",
    MODERN: "Up-to-date",
    MONKEY: "Banana lover",
    MOTHER: "Female parent",
    MUFFIN: "Breakfast cake",
    NEEDLE: "Sewing point",
    NIGHTS: "Evenings",
    ORANGE: "Citrus fruit",
    PALACE: "Royal home",
    PARENT: "Mom or dad",
    PARROT: "Talking bird",
    PEANUT: "Ballpark snack",
    PEBBLE: "Small stone",
    PENCIL: "Writing stick",
    PEOPLE: "Folks",
    PEPPER: "Salt's partner",
    PILLOW: "Head cushion",
    PLANET: "Mars or Venus",
    PLENTY: "More than enough",
    POCKET: "Pants pouch",
    POTATO: "Mashed spud",
    PRETTY: "Attractive",
    PURPLE: "Grape color",
    PUZZLE: "Brain teaser",
    RABBIT: "Hopping pet",
    REASON: "The why",
    REMOTE: "Channel changer",
    RESCUE: "Save",
    RIBBON: "Gift bow material",
    RIVERS: "Flowing waters",
    ROCKET: "Space launcher",
    SADDLE: "Horse seat",
    SAFELY: "Without harm",
    SALMON: "Pink fish",
    SAUCER: "Cup's plate",
    SCHOOL: "Place to learn",
    SEASON: "Spring or fall",
    SECOND: "Right after first",
    SECRET: "Hidden info",
    SHADOW: "Cast outline",
    SILENT: "Making no sound",
    SILVER: "Shiny gray metal",
    SIMPLE: "Easy",
    SINGER: "Vocalist",
    SISTER: "Female sibling",
    SMOOTH: "Not bumpy",
    SPIDER: "Eight-legged spinner",
    SPRING: ["Bouncy season", "Suddenly leap up from a crouch"],
    SQUARE: "Four equal sides",
    STREET: "Paved road",
    STRONG: "Powerful",
    SUMMER: "Beach season",
    SUNSET: "Dusk sky show",
    TEMPLE: "Place of worship",
    TENNIS: "Racket sport",
    THIRTY: "Three times ten",
    THREAD: "Sewing strand",
    TICKET: "Show pass",
    TISSUE: "Nose wiper",
    TOMATO: "Salad red",
    TONGUE: "Taste organ",
    TURTLE: "Shelled reptile",
    VALLEY: "Low land between hills",
    VELVET: "Plush fabric",
    WALLET: "Cash holder",
    WALNUT: "Hard-shelled nut",
    WINDOW: "Glass pane",
    WINNER: "Contest victor",
    WINTER: "Cold season",
    WISDOM: "Deep knowledge",
    WIZARD: "Spell caster",
    WONDER: "Marvel",
    YELLOW: "Banana color",
    ZIPPER: "Jacket fastener",
  },
  7: {
    ACTIONS: "Things done",
    AIRPORT: "Plane hub",
    ANCIENT: "Very old",
    ANIMALS: "Zoo dwellers",
    ANOTHER: "One more",
    BALLOON: "Party floater",
    BEDROOM: "Sleeping space",
    BICYCLE: "Pedal-powered ride",
    BLANKET: "Bed cover",
    BROTHER: "Male sibling",
    CABBAGE: "Leafy green head",
    CAPTAIN: "Ship's leader",
    CEILING: "Room's top",
    CHEETAH: "Fastest land animal",
    CHICKEN: "Coop bird",
    CLIMATE: "Region's weather",
    COMPANY: "Business firm",
    COMPUTE: "Do the math",
    CONCERT: "Live music show",
    COTTAGE: "Small country house",
    COUNTRY: "Nation",
    COURAGE: "Bravery",
    CRAYONS: "Coloring sticks",
    CRYSTAL: "Clear gem",
    CULTURE: "Way of life",
    CUPCAKE: "Frosted small cake",
    CURTAIN: "Window cover",
    DENTIST: "Tooth doctor",
    DESSERT: "Sweet course",
    DIAMOND: "Hard gem",
    DOLPHIN: "Smart sea mammal",
    DRAWING: "Pencil art",
    EVENING: "After dusk",
    FACTORY: "Goods maker",
    FEATHER: "Bird's plume",
    FORTUNE: "Great wealth",
    FREEDOM: "Liberty",
    GARDENS: "Flower plots",
    GENERAL: "Top officer",
    GIRAFFE: "Long-necked grazer",
    HARVEST: "Crop gathering",
    HEALTHY: "In good shape",
    HISTORY: "Study of the past",
    HOLIDAY: "Day off",
    JOURNEY: "Long trip",
    JUSTICE: "Fairness",
    KITCHEN: "Cooking room",
    LANTERN: "Carried light",
    LIBRARY: "Book hall",
    MACHINE: "Mechanical device",
    MEASURE: "Take dimensions of",
    MINUTES: "Hour's parts",
    MORNING: "Day's start",
    MOUNTED: "Got on a horse",
    MUSTARD: "Hot-dog topping",
    NATURAL: "From nature",
    NETWORK: "Linked system",
    NOTHING: "Zilch",
    OCTOPUS: "Eight-armed sea creature",
    OUTDOOR: "Open-air",
    PACKAGE: "Mailed parcel",
    PAINTER: "One with a brush",
    PARTNER: "Teammate",
    PATTERN: "Repeating design",
    PENGUIN: "Tuxedoed bird",
    PERFECT: "Flawless",
    PICTURE: "Photo",
    PILLOWS: "Bed cushions",
    POPCORN: "Movie snack",
    PRESENT: "Wrapped gift",
    PROBLEM: "Math question",
    PROMISE: "Solemn vow",
    PROTECT: "Keep safe",
    PUMPKIN: "Halloween gourd",
    RAINBOW: "Sky's color arch",
    READING: "Book time",
    RECIPES: "Cooking guides",
    RESPECT: "High regard",
    SANDALS: "Summer footwear",
    SCIENCE: "Lab study",
    SEASONS: "Spring, summer, fall, winter",
    SERVICE: "Help provided",
    SHELTER: "Place of safety",
    SOLDIER: "Army member",
    SPARKLE: "Glitter",
    STATION: "Train stop",
    STORAGE: "Where things are kept",
    STUDENT: "Class attendee",
    SUNRISE: "Dawn",
    SUNSHINE: "Bright daylight",
    TEACHER: "Class leader",
    THUNDER: "Storm's boom",
    TONIGHT: "This evening",
    TROPHY: "Winner's cup",
    USEFUL: "Handy",
    VICTORY: "A big win",
    VILLAGE: "Small town",
    WEATHER: "Rain or shine",
    WEEKEND: "Saturday and Sunday",
    WELCOME: "Greeting at the door",
    WHISPER: "Soft speech",
    WINNERS: "First-place finishers",
  },
};
